{
 "title": "eDNS / GTM",
 "description": "Explore DNS queries to Edge DNS and Global Traffic Manager.",
 "tags": [
  "V1.0",
  "Required table: edns_summary_hour"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "edns", "query": "${VAR_EDNS}" },
   { "name": "edns_summary_hour", "query": "${VAR_EDNS_SUMMARY_HOUR}" },
   {
    "name": "duration",
    "query": "SELECT datediff('h', $__fromTime, $__toTime)"
   },
   { "name": "filter" },
   {
    "name": "table",
    "query": "SELECT CASE\nWHEN ${duration} <= 72 THEN '${edns}'\nWHEN ${duration} > 72 THEN '${edns_summary_hour}'\nEND"
   },
   { "name": "timestamp", "query": "timeStamp" },
   {
    "name": "uniq_requestIP",
    "query": "SELECT IF (\n'${table}' = '${edns}',\n'uniq(requestIP)',\n'uniq_requestIP'\n)"
   },
   {
    "name": "uniq_requestPort",
    "query": "SELECT IF (\n'${table}' = '${edns}',\n'uniq(requestPort)',\n'uniq_requestPort'\n)"
   },
   {
    "name": "cnt_all",
    "query": "SELECT IF (\n'${table}' = '${edns}',\n'count()',\n'cnt_all'\n)"
   },
   {
    "name": "edns_size",
    "query": "SELECT IF (\n'${table}' = '${edns}',\n'\ncountIf(edns0Size>=000 and edns0Size<=499) as \"0 - 499\",\ncountIf(edns0Size>=500 and edns0Size<=999) as \"500 - 999\",\ncountIf(edns0Size>=1000 and edns0Size<=1499) as \"1000 - 1499\",\ncountIf(edns0Size>=1500 and edns0Size<=1999) as \"1500 - 1999\",\ncountIf(edns0Size>=2000 and edns0Size<=2999) as \"2000 - 2999\",\ncountIf(edns0Size>=3000 and edns0Size<=3999) as \"3000 - 3999\",\ncountIf(edns0Size>=4000 and edns0Size<=4999) as \"4000 - 4999\",\ncountIf(edns0Size>=5000 and edns0Size<=5999) as \"5000 - 5999\",\ncountIf(edns0Size>=6000 and edns0Size<=6999) as \"6000 - 6999\",\ncountIf(edns0Size>=7000 and edns0Size<=7999) as \"7000 - 7999\",\ncountIf(edns0Size>=8000 and edns0Size<=8999) as \"8000 - 8999\",\ncountIf(edns0Size>=9000 and edns0Size<=9999) as \"9000 - 9999\"\n',\n'\nedns_size[1] AS \"0 - 499\",\nedns_size[2] AS \"500 - 999\",\nedns_size[3] AS \"1000 - 1499\",\nedns_size[4] AS  \"1500 - 1999\",\nedns_size[5] AS \"2000 - 2999\",\nedns_size[6] AS \"3000 - 3999\",\nedns_size[7] AS \"4000 - 4999\",\nedns_size[8] AS  \"5000 - 5999\",\nedns_size[9] AS \"6000 - 6999\",\nedns_size[10] AS \"7000 - 7999\",\nedns_size[11] AS \"8000 - 8999\",\nedns_size[12] AS \"9000 - 9999\"\n'\n)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h3>eDNS / GTM</h3>\n<p>A dashboard to explore DNS queries to Edge DNS and Global Traffic Manager.</p>"
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "description": "Total number of requests in the selected time range.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n${cnt_all} as count\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n    AND $__adHocFilter() \nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Total Requests; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Requests Over Time per Request Name",
   "type": "timeseries",
   "description": "Shows count for selected requestName. ",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with (\n  select topK(20)(requestName) \n  FROM ${table}\n  WHERE $__timeFilter(${timestamp})\n      AND $__adHocFilter() \n) as top_items\n\nSELECT \nrequestName,\n${cnt_all} as count,\n$__timeInterval(timeStamp) as time\nFROM ${table}\n  WHERE $__timeFilter(${timestamp})\n      AND $__adHocFilter() \ngroup by time,requestName\norder by time asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Requests Over Time per; du=${__user.login}'"
    }
   ]
  },
  { "title": "Pie Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "DNS Sec Flag",
   "type": "piechart",
   "description": "Percentage of DNS Flags.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    dnssecFlag, \n    ${cnt_all} as count\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n    AND $__adHocFilter() \ngroup by dnssecFlag\norder by count desc\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=DNS Sec Flag; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Country",
   "type": "piechart",
   "description": "Top 100 Countries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    country, \n    ${cnt_all} as count\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n    AND $__adHocFilter() \ngroup by country\norder by count desc\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Country; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "edns0Flag Class",
   "type": "piechart",
   "description": "Percentage of ECS Flags.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    edns0Flag,\n    ${cnt_all} as count\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n    AND $__adHocFilter() \ngroup by edns0Flag\norder by count desc\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=edns0Flag Class; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Answers",
   "type": "piechart",
   "description": "Top 100 Answer.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    answer, \n    ${cnt_all} as count\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n    AND $__adHocFilter() \ngroup by answer\norder by count desc\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Answers; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "TCP Flag",
   "type": "piechart",
   "description": "Percentage of TCP Flags.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    tcpFlag,\n    ${cnt_all} as count\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n    AND $__adHocFilter() \ngroup by tcpFlag\norder by count desc\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=TCP Flag; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Request Types",
   "type": "piechart",
   "description": "Number of requests per Requests Type.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    requestType, \n    ${cnt_all} as count\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n    AND $__adHocFilter() \ngroup by requestType\norder by count desc\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Request Types; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Distinct RequestIPs",
   "type": "stat",
   "description": "Overall count of unique Request Ups in this time period.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    ${uniq_requestIP} as uniqIPs\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n    AND $__adHocFilter() \nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Distinct RequestIPs; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "eDNS Size",
   "type": "bargauge",
   "description": "The ECS (Edge DNS Client Subnet) field size in bytes.",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  ${edns_size}\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n    AND $__adHocFilter()\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=eDNS Size; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Distinct Ports",
   "type": "stat",
   "description": "Overall count of unique Ports in this time period.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    ${uniq_requestPort} as uniqPorts\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n    AND $__adHocFilter() \nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Distinct Ports; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Hostname Distribution by Country",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }
  },
  {
   "title": "Requests per Country",
   "type": "table",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT \ncountry, \n${cnt_all} as count\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter() \ngroup by country\norder by count desc\nLIMIT 1000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Requests per Country; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Hostname distribution by Country",
   "type": "table",
   "gridPos": { "h": 14, "w": 19, "x": 5, "y": 45 },
   "targets": [
    {
     "rawSql": "WITH country_totals AS (\n    SELECT\n        country,\n        ${cnt_all} AS total_count\n    FROM ${table}\n    WHERE $__timeFilter(${timestamp})\n        AND $__adHocFilter() \nGROUP BY country\n),\n\ncountry_hostname_counts AS (\n    SELECT\n        country,\n        answer as hostname,\n        ${cnt_all} AS hostname_count\n    FROM ${table}\n    WHERE $__timeFilter(${timestamp})\n        AND $__adHocFilter() \nGROUP BY country, hostname\n)\n    SELECT\n        chc.country,\n        chc.hostname,\n        chc.hostname_count,\n        ct.total_count,\n        (chc.hostname_count / ct.total_count) * 100 AS hostname_percentage\n    FROM country_hostname_counts chc\n    JOIN country_totals ct ON chc.country = ct.country\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Hostname distribution by Country; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Hostname Distribution by Region",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 }
  },
  {
   "title": "Requests per Region",
   "type": "table",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT \nstate, \n${cnt_all} as count\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n    AND $__adHocFilter() \ngroup by state\norder by count desc\nLIMIT 200\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Requests per Region; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Hostname distribution by Region",
   "type": "table",
   "gridPos": { "h": 14, "w": 19, "x": 5, "y": 60 },
   "targets": [
    {
     "rawSql": "WITH state_totals AS (\n    SELECT\n        state,\n        ${cnt_all} AS total_count\n    FROM ${table}\n    WHERE $__timeFilter(${timestamp})\n        AND $__adHocFilter() \n    GROUP BY state\n),\n\nstate_hostname_counts AS (\n    SELECT\n        state,\n        answer as hostname,\n        ${cnt_all} AS hostname_count\n    FROM ${table}\n    WHERE $__timeFilter(${timestamp})\n        AND $__adHocFilter() \n    GROUP BY state, hostname\n)\n    SELECT\n        chc.state,\n        chc.hostname,\n        chc.hostname_count,\n        ct.total_count,\n        (chc.hostname_count / ct.total_count) * 100 AS hostname_percentage\n    FROM state_hostname_counts chc\n    JOIN state_totals ct ON chc.state = ct.state\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Hostname distribution by Region; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "Help & Docs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Field Definitions",
     "type": "text",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 100 },
     "options": {
      "content": "\nLink to Akamai TechDocs Field Definitions <a href=\"https://techdocs.akamai.com/datastream2/v3/docs/data-set-parameters#edge-dns-and-global-traffic-management-fields\" target=\"0\">here </a>\n<br><br>\n<table style=\"width: 100%; border-collapse: collapse;\">\n    <tr>\n        <th style=\"background-color: darkblue; border: 1px solid #000; padding: 8px; text-align: left;\">Data element</th>\n        <th style=\"background-color: darkblue; border: 1px solid #000; padding: 8px; text-align: left;\">Examples</th>\n        <th style=\"background-color: darkblue; border: 1px solid #000; padding: 8px; text-align: left;\">Description</th>\n    </tr>\n    <tr>\n        <td style=\"border: 1px solid #000; padding: 8px;\">Epoch timestamp</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">1710167865</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">The Unix epoch timestamp of the log entry and its transaction.</td>\n    </tr>\n    <tr>\n        <td style=\"border: 1px solid #000; padding: 8px;\">Date</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">07/12/2020</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">The UTC date for log entry and its transaction.</td>\n    </tr>\n    <tr>\n        <td style=\"border: 1px solid #000; padding: 8px;\">Resolver IP</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">2600:141b:b000::1736:a142</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">The IP address of the DNS resolver making the request.</td>\n    </tr>\n    <tr>\n        <td style=\"border: 1px solid #000; padding: 8px;\">Request port</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">37041</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">The port number of the DNS resolver making the request.</td>\n    </tr>\n    <tr>\n        <td style=\"border: 1px solid #000; padding: 8px;\">Request name</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">nxdomain.edgedns.zone</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">The query name of the request.</td>\n    </tr>\n    <tr>\n        <td style=\"border: 1px solid #000; padding: 8px;\">Class</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">IN</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">The DNS class of the request. <br> A : Internet <br> CH : Chaos <br>HS : Hesiod <br> Any : Any other <br> (Note: almost exclusively it's A></td>\n    </tr>\n    <tr>\n        <td style=\"border: 1px solid #000; padding: 8px;\">Request type</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">A : Request Record <br> AAAA : IPv6 Request Record <br> CNAME : Canonical Name which redirects to another name <br> MX : Mail Exchange <br> TXT : Text record <br> NS : Indicates which DNS server is authoritative for the domain <br> SRV : Service Record. Specifies ports for service <br> PTR : Pointer - maps IP address to domain name for reverse lookups <br> SOA : Start of Authority - provides information about the domain and primary DNS server</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">The request's DNS record type.</td>\n    </tr>\n    <tr>\n        <td style=\"border: 1px solid #000; padding: 8px;\">EDNS0 flag</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">## E</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">The EDNS0 Client Subnet (ECS) indicator, either E or blank. This is used to provide more accurate routing information by augmenting information about the resolver IP with information about the client subnet Akamai can make more informed resolution decisions.</td>\n    </tr>\n    <tr>\n        <td style=\"border: 1px solid #000; padding: 8px;\">EDNS0 size</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">1220</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">The ECS (Edge DNS Client Subnet) field size in bytes.</td>\n    </tr>\n    <tr>\n        <td style=\"border: 1px solid #000; padding: 8px;\">DNSSEC flag</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">## D</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">The DNSSEC indicator, either D or blank.</td>\n    </tr>\n    <tr>\n        <td style=\"border: 1px solid #000; padding: 8px;\">TCP flag</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">## T</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">The TCP indicator, either T or blank.</td>\n    </tr>\n    <tr>\n        <td style=\"border: 1px solid #000; padding: 8px;\">Answers</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">3:NXDOMAIN</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">The request answers for a request query name.</td>\n    </tr>\n    <tr>\n        <td style=\"border: 1px solid #000; padding: 8px;\">Time</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">14:37:45 GMT</td>\n        <td style=\"border: 1px solid #000; padding: 8px;\">The UTC time for log entry and its transaction.</td>\n    </tr>\n</table>\n<br>\n<br>\n<h3> Other Links</h3>\n<ul>\n    <li><h6>Article in ECS (Edge DNS Client Subnet) <a href=\"https://community.akamai.com/customers/s/article/What-is-ECS-EDNS0-Client-Subnet?language=en_US\" target=\"_blank\"> here </a></h6></li>\n    <li> <h6>RFC Standard on ECS <a href=\"https://datatracker.ietf.org/doc/rfc7871/\" target=\"_blank\"> here </a> </h6></li>\n</ul>"
     }
    }
   ]
  }
 ]
}