folders:
  hdx-main-folder:
    name: TrafficPeak Certified Reference Dashboards
    children: {}
dashboards:
  hdx-edns_gtm:
    dashboard:
      __extend__: dashboards/edns_gtm.json
    folderUid: hdx-main-folder
    inputs:
      DS_HYDROLIX-HYDROLIX-DATASOURCE: hdx-hydrolix-datasource
      VAR_EDNS: akamai.edns
      VAR_EDNS_SUMMARY_HOUR: akamai.edns_summary_hour
