{
 "title": "Error Analysis",
 "description": "Quickly identify where you are experiencing status code and network errors.",
 "tags": [
  "Required tables: summary_hour/summary_sampled_day",
  "v1.1"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "raw_table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   },
   { "name": "timestamp", "query": "reqTimeSec" },
   {
    "name": "duration",
    "query": "SELECT datediff('h', $__fromTime, $__toTime)"
   },
   {
    "name": "ds2",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   },
   {
    "name": "summary_hour",
    "query": "__PROJECT_NAME__.__SUMMARY_TABLE_NAME_1__"
   },
   {
    "name": "summary_day",
    "query": "__PROJECT_NAME__.__SUMMARY_TABLE_NAME_2__"
   },
   {
    "name": "table",
    "label": "Table used",
    "query": "SELECT  CASE\nWHEN ${duration} < 6 THEN '${ds2}'\nWHEN ${duration} >= 6 AND ${duration} < 72 THEN '${summary_hour}'\nWHEN ${duration} >= 72 THEN '${summary_day}'\nEND"
   },
   {
    "name": "cnt_all_var",
    "query": "SELECT\nIF('${table}' = '${ds2}', 'count()', 'cnt_all')"
   },
   {
    "name": "errorRate_var",
    "query": "SELECT \nIF('${table}' = '${ds2}', 'countIf(statusCode>=400)/count(statusCode)', '(cnt_4xx_status_code+cnt_5xx_status_code)/cnt_all')"
   },
   {
    "name": "percentError_var",
    "query": "SELECT \nIF('${table}' = '${ds2}', 'countIf(isNotNull(errorCode))/count(*)', 'cnt_error/cnt_all')"
   },
   {
    "name": "uniq_reqPath_var",
    "query": "SELECT  \nIF('${table}' = '${ds2}', 'uniq(reqPath)', 'uniq_req_path')"
   },
   {
    "name": "uniq_cliIP_var",
    "query": "SELECT  \nIF('${table}' = '${ds2}', 'uniq(cliIP)', 'uniq_client_ip')"
   },
   { "name": "treemapCells", "query": "500" },
   {
    "name": "treeMapGroupBy",
    "label": "Focus On:",
    "query": "Hostname : reqHost , Path : reqPath , Client IP : cliIP , ASN : asn , UA : UA , Country : country , State : state , City : city , referer : referer , Content Type : rspContentType , Status Code : statusCode , Edge IP : Edge_IP , Error Code : errorCode"
   },
   {
    "name": "sampledFields_banner",
    "query": "SELECT IF('${table}' = '${summary_day}', 'Please note: \nDue to the current time range selection (>= 3 days), the fields asn, cliIP, referer, reqPath and UA have been sampled', 'Error Analysis\nQuickly identify where you are experiencing status code and network errors.')"
   },
   {
    "name": "drill_chain",
    "query": "SELECT $$[${customize_drilldown_order:singlequote}]$$"
   },
   {
    "name": "next_dim",
    "query": "WITH\n    '${filter:raw}' AS flt,\n    ${drill_chain} as drill_chain,\n    arrayFilter(dim -> '${treeMapGroupBy}' != dim, drill_chain) as filtered,\n    arrayConcat(['${treeMapGroupBy}'], filtered) as reordered,\n    arrayFilter(dim -> position(flt, dim) = 0, reordered) AS remaining\nSELECT \nif(\n    (if(empty(remaining), '${treeMapGroupBy}', remaining[1])) = 'statusCode', 'toString(statusCode)',\n    (if(empty(remaining), '${treeMapGroupBy}', remaining[1]))\n  ) AS result"
   },
   {
    "name": "item_formatted_for_display",
    "query": "SELECT $$\n  CASE\n    WHEN ${next_dim} IS NULL THEN '__null__'\n    WHEN ${next_dim} = '' THEN '__empty__'\n    ELSE REPLACE(${next_dim}, 'undefined', 'undef')\n  END\n$$"
   },
   {
    "name": "item_formatted_for_filter",
    "query": "SELECT $$\n  CASE\n    WHEN ${next_dim} IS NULL THEN '__null__'\n    WHEN ${next_dim} = '' THEN '__empty__'\n    ELSE\n      REPLACE(\n        REPLACE(\n          COALESCE(${next_dim}, '__null__'),\n          ',', '__gfc__'\n        ),\n        '|', '__gfp__'\n      )\n  END\n$$"
   },
   {
    "name": "next_dim_for_display",
    "query": "WITH map(\n    'reqHost', 'Hostname',\n    'reqPath', 'Path',\n    'cliIP', 'Client IP',\n    'asn', 'ASN',\n    'referer', 'Referer',\n    'UA', 'User Agent',\n    'country', 'Country',\n    'state', 'State',\n    'city', 'City',\n    'rspContentType', 'Content Type',\n    'statusCode', 'Status Code',\n    'Edge_IP', 'Edge IP',\n    'errorCode', 'Error Code',\n    'cp', 'CP'\n) AS display_name_map\nSELECT display_name_map['${next_dim}']"
   },
   {
    "name": "customize_drilldown_order",
    "label": "Customize \"Drilldown Path\" Order",
    "query": "Hostname : reqHost , Path : reqPath , Client IP : cliIP , ASN : asn , UA : UA , Country : country , State : state , City : city , referer : referer , Content Type : rspContentType , Status Code : statusCode , Edge IP : Edge_IP , Error Code : errorCode"
   },
   { "name": "minErrorRate", "label": "Min Error Rate", "query": "0.00" },
   {
    "name": "drill_chain_for_display",
    "query": "WITH map(\n    'reqHost', 'Hostname',\n    'reqPath', 'Path',\n    'cliIP', 'Client IP',\n    'asn', 'ASN',\n    'referer', 'Referer',\n    'UA', 'User Agent',\n    'country', 'Country',\n    'state', 'State',\n    'city', 'City',\n    'rspContentType', 'Content Type',\n    'statusCode', 'Status Code',\n    'Edge_IP', 'Edge IP',\n    'errorCode', 'Error Code'\n) AS display_name_map\nSELECT arrayStringConcat(\n    arrayMap(\n        x -> if(x = '${next_dim}',\n                concat('<span style=\"display: inline-block; vertical-align: middle; background-color: #3787F3; color: white; padding: 3px 8px; border-radius: 4px;\">', display_name_map[x], '</span>'),\n                concat('<span style=\"display: inline-block; vertical-align: middle; background-color: #202226; border: 1px solid #333740; color: #9FA9B8; padding: 3px 8px; border-radius: 4px;\">', display_name_map[x], '</span>')\n        ),\n        ${drill_chain}\n    ),\n    ' <span style=\"color:#565a64;\">→</span> '\n)"
   },
   {
    "name": "lineChartGrouping",
    "query": "Hostname : reqHost , Client IP : cliIP , ASN : asn , Country : country , State : state , City : city , Content Type : rspContentType , Status Code : toString(statusCode) , Edge IP : Edge_IP"
   },
   { "name": "filter" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "#### ${sampledFields_banner}" } },
  { "title": "Summary Panels ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total requests ",
   "type": "stat",
   "description": "Shows top of selected domains. Summary tables only allow grouping by Hostname, Country, state, region, statusCode and errorCode.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 54 }
   ]
  },
  {
   "title": "Requests Over Time per ${lineChartGrouping} ",
   "type": "timeseries",
   "description": "Shows count for selected domains. Summary tables only allow grouping by Hostname, Country, state, region, statusCode and errorCode. This is using the hourly summary",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT ${lineChartGrouping} AS item,\n${cnt_all_var} AS count,\n$__timeInterval(${timestamp}) AS time\nFROM  ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter() \nGROUP BY time, item\nORDER BY time ASC, count DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Requests Over Time per Hostname - Summary; du=${__user.login}'"
    }
   ]
  },
  { "title": "Error Treemaps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Drilldown Path:",
   "type": "text",
   "description": "The bolded item is the dimension currently displayed in the TreeMaps. Click any TreeMap cell to filter by that value and advance to the next step. Use the \"Customize Drilldown Order\" dropdown above to change the order of the dimensions.\nTo inspect the \"Raw Logs\", click on any square in the Treemap and select \"View Raw Logs\".",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "options": {
    "content": "\n${drill_chain_for_display:text}\n\n💡 *Use the \"Customize \"Drilldown Path\" Order\" dropdown above to change the drilldown order of the dimensions.*"
   }
  },
  {
   "title": "Top ${treemapCells} ${next_dim_for_display} by HTTP Error Rate (>${minErrorRate})",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT \n  ${item_formatted_for_display} as item,\n  ${item_formatted_for_filter} as filter_item,\n  ${cnt_all_var} AS count,\n  ${errorRate_var} AS errorRate, /*HTTP STATUS CODE ERRORS*/\n  ${percentError_var} AS percentError  /*NETWORK ERRORS */\nFROM  ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter() \n  AND item NOT IN '~~~SAMPLED_OUT~~~'\nGROUP BY item, filter_item\nHAVING errorRate>=${minErrorRate}\nORDER BY count DESC\nLIMIT ${treemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Error Rate for top; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top ${treemapCells} ${next_dim_for_display} by Network Error Rate (>${minErrorRate})",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "panelId": 48 }
   ]
  },
  {
   "title": "Piecharts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unique Resources",
     "type": "stat",
     "description": "Overall count of unique userIDs where a userID is first match in the queryString on regex: /id=(ac\\d+)/",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  ${uniq_reqPath_var}\nFROM  ${table} \nWHERE $__timeFilter(${timestamp})\n    AND $__adHocFilter() \nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Unique Resources; du=${__user.login}'\n"
      }
     ]
    },
    {
     "title": "Status Codes",
     "type": "piechart",
     "description": "Percentage share of each HTTP Status Code",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT toString(statusCode) as statusCode, ${cnt_all_var} AS count\nFROM  ${table}\nWHERE $__timeFilter(${timestamp}) \n  AND $__adHocFilter() \nGROUP BY statusCode\nORDER BY count DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Status Code; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Error Codes",
     "type": "piechart",
     "description": "Top 50 error codes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT ${cnt_all_var} AS count, errorCode, REPLACE(errorCode, '|', '__gfp__') AS escaped_errorCode\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n    AND $__adHocFilter() \n    AND errorCode IS NOT NULL\nGROUP BY errorCode\nORDER BY count DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Error Codes; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Unique IPs Overall",
     "type": "stat",
     "description": "Overall count of unique Client IPs in this time period",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  ${uniq_cliIP_var}\nFROM  ${table} \nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter() \nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Unique IPs Overall; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Countries",
     "type": "piechart",
     "description": "Top 50 Countries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT ${cnt_all_var} AS count, country\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n    AND $__adHocFilter() \nGROUP BY country\nORDER BY count DESC\nLIMIT 50\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Countries; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Resources",
     "type": "piechart",
     "description": "Top 50 resources",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT ${cnt_all_var} AS count, reqPath as item\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n    AND $__adHocFilter() \n    AND item NOT IN '~~~SAMPLED_OUT~~~'\nGROUP BY item\nORDER BY count DESC\nLIMIT 50\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Resources; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Content Types",
     "type": "piechart",
     "description": "Number of requests per streaming format",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT ${cnt_all_var} AS count, rspContentType as item\nFROM ${table}\nWHERE $__timeFilter(${timestamp}) \nAND $__adHocFilter() \nGROUP BY item\nORDER BY count\nLIMIT 20\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Content Types; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Referer",
     "type": "table",
     "description": "Top 50 referers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "rawSql": "SELECT ${cnt_all_var} AS count, referer as item \nFROM ${table} \nWHERE $__timeFilter(${timestamp}) \nAND $__adHocFilter() \nAND item NOT IN '~~~SAMPLED_OUT~~~' \nGROUP BY item \nORDER BY count DESC \nLIMIT 50 \nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Referer; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Help and Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Analysis Dashboard",
     "type": "text",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
     "options": {
      "content": "<h1 style=\"color:orange;\"> Using Error Analysis Dashboard </h1>\n<h2> Usage Overview</h2>\nThe Error Analysis dashboard helps users quickly find and remediate errors: \n<ul>\n  <li>The top two Summary panels provide an overview timeline of the data. You can use the 'lineChartGrouping' variable to decide how you'd like to see the data grouped. \n    Then drag a rectangle around a time period of interest to 'zoom in' to that time period. \n    </li>\n  <li>After you've 'zoomed in', expand the other 'rows' in the dashboard to explore the data.</li>\n  <li>To view raw data, click on a panel in the treemap to see a 'View Raw Logs' menu option. Note, this will open in a new window.</li>\n  <li>Alternatively, you can select the 'Filter to this item' menu option, which will add that variable value to the control filters at the top of the page. </li>\n</ul>\n\n<h2> Controls</h2>\n<ol>\n    <li>The 'Focus on' selection allows you to select the primary data attribute you want to group your data around and focus on for your investigation or research. \n  </li>\n<li>The 'Customize 'Drilldown Path' order' allows you to modify the default order of data attributes used when drilling into the data in the panels below. You can see the 'Drilldown path' presented in the 'Error Treemaps' panel. Being able to adjust the default order allows for quicker investigation of incidents\n  </li>\n   <li> Use the 'Min Error Rate' filter to filter out items that have a low error rate. For example, enter .05 in the 'Min Error Rate' filter to only show items that have a 5% or higher error rate </li>\n  <li>\n    You can jump to any element in the 'Drilldown path' section of the 'Error Tree' panel\n    </li> \n  <li>You can click 'reset all variables' at any point to discard any changes you have made to the filters and start again.\n    </li> \n\n</ol>\n\n\n"
     }
    },
    {
     "title": "All TrafficPeak Videos",
     "type": "text",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
     "options": {
      "content": "<h1 style=\"color:orange;\"> All TrafficPeak VIDS </h1>\n<table>\n  <tr>\n    <td> Video </td>\n    <td> Description </td>\n  </tr>\n  <tr>\n    <td> <a href=\"https://youtu.be/xofU9fJZY0c?si=LSumL_RhgD9tuFP8\" target=\"_blank\">\n      <img src=\"https://img.youtube.com/vi/xofU9fJZY0c/mqdefault.jpg\" alt=\"Watch Error Analysis Video\" style=\"width: 100%; min-width: 300px; height: auto; border: 3px solid #ccc; border-radius: 15px;\">\n      </a>\n    </td>\n    <td>\n      TrafficPeak Error Analysis Video <a href=\"https://youtu.be/xofU9fJZY0c?si=LSumL_RhgD9tuFP8\" target=\"_blank\">(here)</a> (10 min) An overview on how to use the Error Analysis Dashboard to find errors that users are experiencing when requesting content.\n    </td>\n  </tr>\n   <tr>\n    <td> <a href=\"https://www.youtube.com/watch?v=3CTwE24Izic\" target=\"_blank\">\n      <img src=\"https://img.youtube.com/vi/3CTwE24Izic/mqdefault.jpg\" alt=\"Watch Error Analysis Video\" style=\"width: 100%; min-width: 300px; height: auto; border: 3px solid #ccc; border-radius: 15px;\">\n      </a>\n    </td>\n    <td>\n      Cache & URL Analysis Video <a href=\"https://www.youtube.com/watch?v=3CTwE24Izic\" target=\"_blank\">(here)</a> (14 min) An overview on how to use TrafficPeak to identify resources which are having low caching rates.\n    </td>\n  </tr>\n  <tr>\n    <td> <a href=\"https://www.youtube.com/watch?v=6yOL59ARuSQ\" target=\"_blank\">\n      <img src=\"https://img.youtube.com/vi/6yOL59ARuSQ/mqdefault.jpg\" alt=\"Creating and Customizing TrafficPeak Dashboards\" style=\"width: 100%; min-width: 300px; height: auto; border: 3px solid #ccc; border-radius: 15px;\">\n      </a>\n    </td>\n    <td>\n      Creating and Customizing TrafficPeak Dashboards Video <a href=\"https://www.youtube.com/watch?v=6yOL59ARuSQ\" target=\"_blank\">(here)</a> (37 min) An overview on how to create and customize TrafficPeak Dashboards.\n    </td>\n  </tr>\n  <tr>\n    <td> <a href=\"https://www.youtube.com/watch?v=WcxWl_IBklM\" target=\"_blank\">\n      <img src=\"https://img.youtube.com/vi/WcxWl_IBklM/mqdefault.jpg\" alt=\"Creating and Customizing TrafficPeak Dashboards\" style=\"width: 100%; min-width: 300px; height: auto; border: 3px solid #ccc; border-radius: 15px;\">\n      </a>\n    </td>\n    <td>\n      Sending DataStream data to TrafficPeak <a href=\"https://www.youtube.com/watch?v=WcxWl_IBklM\" target=\"_blank\">(here)</a> (10 min) An overview on how to set Akamai DataStream and properties to send data to TrafficPeak.\n    </td>\n  </tr>\n \n</table>\n\n"
     }
    }
   ]
  }
 ]
}