{
 "title": "Explore Data",
 "tags": [ "v1.1" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "raw_table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   },
   {
    "name": "table",
    "query": "SELECT concat(project,'.',name) as table FROM (SELECT database as project, name FROM system.tables WHERE engine = 'TurbineStorage' AND (project != 'sample_project'  AND project != 'hdx'))"
   },
   {
    "name": "timestamp",
    "query": " SELECT primary_key FROM system.tables WHERE database = splitByChar('.','${table}')[1] AND table = splitByChar('.','${table}')[2]"
   },
   {
    "name": "sql",
    "label": "SQL Editor",
    "query": " SELECT name FROM system.columns WHERE database = splitByChar('.','${table}')[1] AND table = splitByChar('.','${table}')[2] LIMIT 1"
   },
   { "name": "filter", "label": "filter" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "#### Explore data\n\nThis dashboard is designed to help understand the ingested data; it provides a description of the schema and allows users to explore the data.  The time range is fixed to use the last 6 hours of available raw log data; changing the time range via the Grafana UI will not have any effect."
   }
  },
  {
   "title": "Log Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(${timestamp}) as time, count() as count\nFROM ${table}\nWHERE ${timestamp} > now() - INTERVAL 6 HOUR \nAND $__adHocFilter() \nGROUP BY time\nORDER BY time ASC, count"
    }
   ]
  },
  { "title": "Schema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Table",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 11 },
   "targets": [
    { "rawSql": "DESCRIBE ${table}" }
   ]
  },
  {
   "title": "View Top 100 value for Column ${sql}",
   "type": "table",
   "gridPos": { "h": 14, "w": 15, "x": 9, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT count() as count, toString(${sql}) as value, replaceAll(value, ',', '__gfc__') AS escaped_value, '+' as include, '-' as exclude\nFROM ${table}\nWHERE ${timestamp} > now() - INTERVAL 6 HOUR\nAND $__adHocFilter() \nGROUP BY value\nORDER BY count DESC\nLIMIT 100\n"
    }
   ]
  }
 ]
}