folders:
  hdx-main-folder:
    name: TrafficPeak Certified Reference Dashboards
    children:
      hdx-security-folder:
        name: Security
dashboards:
  hdx-cdn-global-view-1778175165375:
    dashboard:
      __extend__: dashboards/cdn_global_view_1778175165375.json
    folderUid: hdx-security-folder
    inputs:
      DS_HYDROLIX-HYDROLIX-DATASOURCE: hdx-hydrolix-datasource
      VAR_RAW_TABLE: hdxevolution372418430567260505.logs
      VAR_SUMMARY_MIN: hdxevolution372418430567260505.mcdn_summary_min
      VAR_SUMMARY_HOUR: hdxevolution372418430567260505.mcdn_summary_hour
      VAR_CDN1: ${VAR_CDN1}
      VAR_RAW_LOGS: c44c5f0c-badf-4794-94a7-2ca3c6f37ade/raw-logs
      VAR_CDN_PANEL: 550e97ed-779f-411e-b72d-3562d6a962a8/cdn-dashboard-default
  hdx-cdn-dashboard-default-1778175158928:
    dashboard:
      __extend__: dashboards/cdn_dashboard_default_1778175158928.json
    folderUid: hdx-security-folder
    inputs:
      DS_HYDROLIX-HYDROLIX-DATASOURCE: hdx-hydrolix-datasource
      VAR_RAW_TABLE: hdxevolution372418430567260505.logs
      VAR_SUMMARY_MIN: hdxevolution372418430567260505.mcdn_summary_min
      VAR_SUMMARY_HOUR: hdxevolution372418430567260505.mcdn_summary_hour
      VAR_QUANTILES_RESPONSE_TTFB_50: quantiles_response_ttfb_ms[2]
      VAR_QUANTILES_RESPONSE_TTFB_95: quantiles_response_ttfb_ms[5]
      VAR_QUANTILES_RESPONSE_TTLB_50: quantiles_response_ttlb_ms[2]
      VAR_QUANTILES_RESPONSE_TTLB_95: quantiles_response_ttlb_ms[5]
      VAR_QUANTILES_ORIGIN_TTFB_50: quantiles_origin_ttfb_ms[2]
      VAR_QUANTILES_ORIGIN_TTFB_95: quantiles_origin_ttfb_ms[5]
      VAR_QUANTILES_ORIGIN_TTLB_50: quantiles_origin_ttlb_ms[2]
      VAR_QUANTILES_ORIGIN_TTLB_95: quantiles_origin_ttlb_ms[5]
  hdx-raw-logs-1778175171305:
    dashboard:
      __extend__: dashboards/raw_logs_1778175171305.json
    folderUid: hdx-security-folder
    inputs:
      DS_HYDROLIX-HYDROLIX-DATASOURCE: hdx-hydrolix-datasource
      VAR_TABLE: hdxevolution372418430567260505.logs
      VAR_TIMESTAMP: timestamp
