folders:
  hdx-main-folder:
    name: TrafficPeak Certified Reference Dashboards
    children: {}
dashboards:
  hdx-cdn-dashboard-default:
    dashboard:
      __extend__: dashboards/cdn_dashboard_default.json
    folderUid: hdx-main-folder
  hdx-raw-logs:
    dashboard:
      __extend__: dashboards/raw_logs.json
    folderUid: hdx-main-folder
  hdx-cdn-global-view:
    dashboard:
      __extend__: dashboards/cdn_global_view.json
    folderUid: hdx-main-folder
