SELECT
  toStartOfHour (timestamp) AS timestamp,
  method,
  status,
  country,
  IF(
    cityHash64 (clientIP) % 100 < 10,
    clientIP,
    '~~~SAMPLED_OUT~~~'
  ) AS clientIP,
  IF(
    cityHash64 (host) % 100 < 10,
    host,
    '~~~SAMPLED_OUT~~~'
  ) AS host,
  IF(
    cityHash64 (path) % 100 < 10,
    path,
    '~~~SAMPLED_OUT~~~'
  ) AS path,
  ruleMessages,
  ruleTags,
  ruleActions,
  attackTypes,
  ruleTagsWAF,
  attack_waf,
  ruleTagsDOS,
  attack_dos,
  ruleTagsBot,
  attack_bot,
  rules,
  asn,
  CH_UA,
  has_CH_UA,
  UA,
  attack_reputation,
  ruleMessage,
  protocol,
  requestId,
  ruleSelectors,
  ruleData,
  count() AS request_count
FROM
  akamai.siem
GROUP BY
  timestamp,
  method,
  status,
  country,
  clientIP,
  host,
  path,
  ruleMessages,
  ruleTags,
  ruleActions,
  attackTypes,
  ruleTagsWAF,
  attack_waf,
  ruleTagsDOS,
  attack_dos,
  ruleTagsBot,
  attack_bot,
  rules,
  asn,
  CH_UA,
  has_CH_UA,
  UA,
  attack_reputation,
  ruleMessage,
  protocol,
  requestId,
  ruleSelectors,
  ruleData SETTINGS hdx_primary_key = 'timestamp'
