{
 "title": "CDN Dashboard Default",
 "tags": [ "v1.0" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "SELECT  CASE\nWHEN ${duration} <= 24 THEN '${summary_min}'\nWHEN ${duration} > 24 THEN '${summary_hour}'\nEND"
   },
   {
    "name": "seconds",
    "query": "SELECT  CASE\nWHEN ${duration} <= 24 THEN 60\nWHEN ${duration} > 24 THEN 3600\nEND"
   },
   {
    "name": "duration",
    "query": "SELECT datediff('h', $__fromTime, $__toTime)"
   },
   { "name": "summary_min", "query": "${VAR_SUMMARY_MIN}" },
   { "name": "summary_hour", "query": "${VAR_SUMMARY_HOUR}" },
   { "name": "filter" },
   {
    "name": "cdn",
    "query": "SELECT extractAll('${filter}', 'hdx_cdn[^\"]*\"([^\"]+)\"')[1] as value"
   },
   {
    "name": "cdn_filter",
    "query": "SELECT DISTINCT hdx_cdn \nFROM ${table} \nWHERE CASE\nWHEN position('${filter:raw}', 'hdx_cdn') = 0 THEN hdx_cdn = '${cdn_default}'\nWHEN length(trim('${filter:raw}')) = 0 THEN hdx_cdn = '${cdn_default}'\nELSE hdx_cdn = '${cdn}'\nEND\nORDER BY hdx_cdn"
   },
   {
    "name": "cdn_default",
    "query": "SELECT hdx_cdn\nFROM ${table}\nWHERE hdx_cdn != ''\nGROUP BY hdx_cdn\nORDER BY hdx_cdn ASC\nLIMIT 1"
   },
   { "name": "adhoc_state", "query": "empty,filtered" },
   {
    "name": "quantiles_response_ttfb_50",
    "query": "${VAR_QUANTILES_RESPONSE_TTFB_50}"
   },
   {
    "name": "quantiles_response_ttfb_95",
    "query": "${VAR_QUANTILES_RESPONSE_TTFB_95}"
   },
   {
    "name": "quantiles_response_ttlb_50",
    "query": "${VAR_QUANTILES_RESPONSE_TTLB_50}"
   },
   {
    "name": "quantiles_response_ttlb_95",
    "query": "${VAR_QUANTILES_RESPONSE_TTLB_95}"
   },
   {
    "name": "quantiles_origin_ttfb_50",
    "query": "${VAR_QUANTILES_ORIGIN_TTFB_50}"
   },
   {
    "name": "quantiles_origin_ttfb_95",
    "query": "${VAR_QUANTILES_ORIGIN_TTFB_95}"
   },
   {
    "name": "quantiles_origin_ttlb_50",
    "query": "${VAR_QUANTILES_ORIGIN_TTLB_50}"
   },
   {
    "name": "quantiles_origin_ttlb_95",
    "query": "${VAR_QUANTILES_ORIGIN_TTLB_95}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"\n  position: absolute;\n  top: 0;\n  left: 0;\n  right: 0;\n  bottom: 0;\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  width: 100%;\n  height: 100%;\n\">\n  <div style=\"background: linear-gradient(45deg, #1f77b4, #2ca02c); padding: 20px; border-radius: 10px; text-align: center; border: 3px solid #fff;\">\n  <h1 style=\"color: white; text-shadow: 2px 2px 4px rgba(0,0,0,0.8); margin: 0; font-size: 2.2em;\">\n    <b>${cdn_filter}</b>\n  </h1>\n</div>\n</div>"
   }
  },
  {
   "title": "${cdn_filter} CDN Hit Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  hdx_cdn as cdn, \n  count(*) AS Total\nFROM ${table} \nWHERE $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY cdn\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Cache Hit Total %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    (SUM(cache_hit) / (SUM(cache_hit) + SUM(cache_miss))) AS total\nFROM \n(\n    SELECT \n        countMergeIf(`count()`, cache_was_cached = 1) AS cache_hit,\n        countMergeIf(`count()`, cache_was_cached = 0) as cache_miss\n    FROM \n        ${table}\n    WHERE \n        $__timeFilter(timestamp)\n        AND $__adHocFilter()\n        AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\n)\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Akamai Cache Hit Total %; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Cache Hit Rate %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum(cache_was_cached) / cnt_all AS cache_hit_rate,\n  timestamp AS time,\n  hdx_cdn\nFROM ${table}\nWHERE \n  $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY time, hdx_cdn\nORDER BY time\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Cache Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    timestamp AS time,\n    (CASE WHEN cache_was_cached = 1 THEN response_total_bytes ELSE 0 END * 8) /${seconds} AS cache_throughput_bps,\n    hdx_cdn\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY time, hdx_cdn, cache_was_cached\nORDER BY time\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Latest Throughput Rate (BPS)",
   "type": "stat",
   "description": "value from the last sum(response_total_bytes) / second",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    response_total_bytes*8/${seconds} AS theBytes,\n    timestamp AS theMinute\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n    AND $__adHocFilter()\n    AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY theMinute\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Peak Throughput Rate (BPS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    response_total_bytes*8/${seconds} AS theBytes,\n    timestamp as theMinute\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n    AND $__adHocFilter()\n    AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY theMinute\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Mean Throughput Rate (BPS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    response_total_bytes*8/${seconds} AS theBytes,\n    timestamp as theMinute\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n    AND $__adHocFilter()\n    AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY theMinute\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Latest Throughput (Bytes Delivered)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    response_total_bytes AS theBytes,\n    timestamp, \n    hdx_cdn\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY timestamp, hdx_cdn\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Peak Throughput (Bytes Delivered)",
   "type": "stat",
   "description": "5 Minute Peak",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    response_total_bytes AS theBytes,\n    hdx_cdn,\n    timestamp\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY timestamp, hdx_cdn\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Mean Throughput (Bytes Delivered)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    response_total_bytes AS theBytes,\n    timestamp, \n    hdx_cdn\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY timestamp, hdx_cdn\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Hits per Status Code (All)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n  toStartOfInterval(timestamp, INTERVAL 1 MINUTE) AS time,\n  toString(response_status_code) as HTTP_Status_Code,\n  COUNT(*) as http\nFROM ${table}\nWHERE $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY \n  HTTP_Status_Code, time\nORDER BY time\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Delivered Bytes by ASN",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    toString(client_asn),\n    response_total_bytes AS Total\nFROM\n   ${table}\nWHERE \n    $__timeFilter(timestamp) \n    AND $__adHocFilter()\n    AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\n    AND notEmpty(client_asn)\nGROUP BY\n    client_asn\nORDER BY\n    Total DESC\nLIMIT 100\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Top 100 Requests by ASN",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  client_asn,\n  COUNT(*) as Total\nFROM ${table}\nWHERE \n  $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY client_asn\nORDER BY Total DESC\nLIMIT 100\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Country Hit / Throughput",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  client_country_iso_code,\n  (response_total_bytes * 8) / (60 * 1000000) AS throughput_mbps\nFROM ${table}\nWHERE \n  $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY client_country_iso_code\nORDER BY throughput_mbps DESC\nLIMIT 100\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Top 100 Requests by Country",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  client_country_iso_code,\n  COUNT(*) as Total\nFROM ${table}\nWHERE \n  $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY client_country_iso_code\nORDER BY Total DESC\nLIMIT 100\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Top 100 Errors by ASN",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n    toString(client_asn) as ASN,\n    response_status_code as Status,\n    COUNT(*) as Total\nFROM\n   ${table}\nWHERE \n    $__timeFilter(timestamp) \n    AND $__adHocFilter()\n    AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\n    AND notEmpty(client_asn)\n    AND response_status_code > '399'\nGROUP BY ASN, response_status_code\nORDER BY Total DESC\nLIMIT 100\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Errors by Host",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    request_host as Host,\n    response_status_code as Status,\n    COUNT(*) as Total\nFROM\n   ${table}\nWHERE \n    $__timeFilter(timestamp) \n    AND $__adHocFilter()\n    AND response_status_code > '399'\n    AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY response_status_code, Host\nORDER BY Total DESC"
    }
   ]
  },
  {
   "title": "${cdn_filter} Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "rawSql": "SELECT \n    toStartOfInterval(timestamp, INTERVAL 1 MINUTE) AS time,\n    response_total_bytes AS Average,\n    hdx_cdn\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n    AND $__adHocFilter()\n    AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY \n    time, hdx_cdn\nORDER BY \n    time    \nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Akamai Current Traffic; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Bytes Delievered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT \n  toStartOfInterval(timestamp, INTERVAL 1 MINUTE) AS time,\n  hdx_cdn,\n  response_total_bytes as Bytes\nFROM ${table}\nWHERE $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY time, hdx_cdn\nORDER BY time\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Top 100 Requests by Country",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  client_country_iso_code,\n  COUNT(*) as Total,\n  hdx_cdn\nFROM ${table}\nWHERE \n  $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY client_country_iso_code, hdx_cdn\nORDER BY Total DESC\nLIMIT 100\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} CDN Data Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \n    timestamp AS time,\n    response_ttfb_ms AS avg_ttfb_ms,\n    ${quantiles_response_ttfb_50} AS p50_ttfb_ms,\n    ${quantiles_response_ttfb_95} AS p95_ttfb_ms\nFROM ${table}\nWHERE $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY time\nORDER BY time\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Edge P50, P95, Avg TTFB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp AS time,\n  ${quantiles_response_ttfb_50} AS p50_ttfb_ms,\n  ${quantiles_response_ttfb_95} AS p95_ttfb_ms,\n  response_ttfb_ms AS avg_ttfb_ms\nFROM ${table}\nWHERE $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY time\nORDER BY time\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Edge P50, P95, Avg TTLB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp AS time,\n  ${quantiles_response_ttlb_50} AS p50_ttlb_ms,\n  ${quantiles_response_ttlb_95} AS p95_ttlb_ms,\n  response_ttlb_ms AS avg_ttlb_ms\nFROM ${table}\nWHERE $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY time\nORDER BY time\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Origin Response p50, p95  TTFB ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp AS time,\n  ${quantiles_origin_ttfb_50} AS p50_origin_ms,\n  ${quantiles_origin_ttfb_95} AS p95_origin_ms\nFROM ${table}\nWHERE $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY time\nORDER BY time\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Origin Response p50, p95  TTLB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp AS time,\n  ${quantiles_origin_ttlb_50} AS p50_origin_ms,\n  ${quantiles_origin_ttlb_95} AS p95_origin_ms\nFROM ${table}\nWHERE $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY time\nORDER BY time\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Hits % per Status Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    toStartOfInterval(timestamp, INTERVAL 1 MINUTE) AS time,\n    (100.0 * countMergeIf(`count()`, response_status_code >= '200' AND response_status_code < '300')) / COUNT(*) AS \"2xx_Percent\",\n    (100.0 * countMergeIf(`count()`, response_status_code >= '300' AND response_status_code < '400')) / COUNT(*) AS \"3xx_Percent\",\n    (100.0 * countMergeIf(`count()`, response_status_code >= '400' AND response_status_code < '500')) / COUNT(*) AS \"4xx_Percent\",\n    (100.0 * countMergeIf(`count()`, response_status_code >= '500' AND response_status_code < '600')) / COUNT(*) AS \"5xx_Percent\"\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n    AND $__adHocFilter()\n    AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY \n    time\nORDER BY \n    time    \nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Status Code Percentages; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Global Traffic by Hit",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "rawSql": "SELECT \n    client_country_iso_code AS Country,\n    COUNT(*) AS Total\nFROM \n    ${table}\nWHERE $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY Country\nORDER BY Total DESC\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload by Hostname; du=${__user.login}'"
    }
   ]
  },
  { "title": "General panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "${cdn_filter} 2xx Response Status Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n    timestamp,\n    countMergeIf(`count()`, response_status_code > '199' and response_status_code < '300') AS Total\nFROM \n    ${table}\nWHERE \n      $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY \n    timestamp\nORDER BY \n    timestamp\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=2xx Response Status Count (US Only); du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} 4xx Response Status Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \n    timestamp,\n    countMergeIf(`count()`, response_status_code > '399' and response_status_code < '500') AS Total\nFROM \n    ${table}\nWHERE \n      $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY \n    timestamp\nORDER BY \n    timestamp\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=4xx Response Status Count (US Only); du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} 5xx Response Status Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \n    timestamp,\n    countMergeIf(`count()`, response_status_code > '499' and response_status_code < '600') as Total\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY \n    timestamp\nORDER BY \n    timestamp\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=5xx Response Status Count (US Only); du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Median Latency by CDN",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n    timestamp,\n    ${quantiles_response_ttfb_50} AS Median\nFROM\n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY\n    timestamp\nORDER BY\n    timestamp asc\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Manifest Latency by CDN (p95/p99); du=${__user.login}'"
    }
   ]
  },
  {
   "title": "${cdn_filter} Total Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp,\n  response_total_bytes AS TotalThroughput\nFROM ${table}\nWHERE $__timeFilter(timestamp)\n  AND $__adHocFilter()\n  AND IF(position('${filter:raw}', 'hdx_cdn') = 0 OR length(trim('${filter:raw}')) = 0, hdx_cdn = '${cdn_default}', 1=1)\nGROUP BY timestamp\nORDER BY timestamp\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Total Edge Traffic; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 100 Global Requests by Country - All CDNs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n    request_host AS Host,\n    client_country_iso_code AS Country,\n    count() AS Total\nFROM ${table}\nWHERE $__timeFilter(timestamp)\n  AND notEmpty(request_host)\n  AND $__adHocFilter()\nGROUP BY request_host, client_country_iso_code\nORDER BY Total DESC\nLIMIT 100\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Global Requests by Country - All CDNs; du=${__user.login}'"
    }
   ]
  }
 ]
}