SELECT
    decodeURLComponent(requestHeadersStr) AS requestHeadersStr,
    decodeURLComponent(responseHeadersStr) AS responseHeadersStr,
    akamai_siem_extract(rulesStr) AS rules,
    akamai_siem_extract(ruleTagsStr) AS ruleTags,
    arrayResize(akamai_siem_extract(ruleDataStr), length(ruleTags), '') AS ruleData,
    akamai_siem_extract(ruleActionsStr) AS ruleActions,
    akamai_siem_extract(ruleMessagesStr) AS ruleMessages,
    akamai_siem_extract(ruleVersionsStr) AS ruleVersions,
    arrayResize(akamai_siem_extract(ruleSelectorsStr), length(ruleTags), '') AS ruleSelectors,
    akamai_extract_key_pair(requestHeadersStr,'
', ':') AS requestHeaders,
    akamai_extract_key_pair(responseHeadersStr,'
', ':') AS responseHeaders,
arrayExists(x -> multiSearchAny(x, ['AKAMAI/BOT/','BOT/','CUSTOM/BOT/','MBS_CL', 'AKAMAI/BOT/CUST_DEFINED_BOTS']), ruleTags) AS attack_bot,
arrayExists(x -> multiSearchAny(x, ['ASE/','AKAMAI/POLICY/','OWASP_CRS/','AKAMAI/WAF','AKAMAI/WEB_ATTACK/']), ruleTags) as attack_waf,
arrayExists(x -> x = 'REPUTATION', ruleTags) as attack_reputation,
arrayExists(x -> startsWith(x, '6'), rules) as attack_custom,
arrayExists(x -> multiSearchAny(x, ['USER-RISK']), rules) as attack_risk,
arrayExists(x -> x = 'IPBLOCK', ruleTags) AS attack_firewall,
arrayExists(x -> positionCaseInsensitive(x, 'BLOCK/') > 0, ruleTags) AS attack_dos,
arrayFilter((x, y) -> y = 1, ['Bot','WAF', 'Reputation','Custom','DoS', 'User Risk', 'Network Firewall'], [attack_bot, attack_waf,attack_reputation,attack_custom,attack_dos, attack_risk, attack_firewall]) AS attackTypes,
    multiIf(
 arrayExists(x -> startsWith(x, 'Web Scrapers'), ruleMessages), 'Web Scrapers', 
 arrayExists(x -> startsWith(x, 'Scanning Tools'), ruleMessages), 'Scanning Tools', 
 arrayExists(x -> startsWith(x, 'Web Attackers'), ruleMessages), 'Web Attackers', 
 arrayExists(x -> startsWith(x, 'DOS Attacker'), ruleMessages), 'DOS Attacker', 
Null) AS ruleMessage,
arrayDistinct(arrayFilter(x -> multiSearchAny(x, ['AKAMAI/BOT/','BOT/','CUSTOM/BOT/','MBS_CL',':']), ruleTags)) AS ruleTagsBot,
arrayDistinct(arrayFilter(x -> multiSearchAny(x, ['ASE/','AKAMAI/POLICY/','OWASP_CRS/','AKAMAI/WAF','AKAMAI/WEB_ATTACK/',':']), ruleTags)) AS ruleTagsWAF,
arrayDistinct(arrayFilter(x -> multiSearchAny(x, ['IPBLOCK',':']), ruleTags)) AS ruleTagsDOS,
requestHeaders['Sec-CH-UA'] AS CH_UA,
requestHeaders['User-Agent'] AS UA,
notEmpty(CH_UA) AS has_CH_UA,
datediff('s', timestamp, now64(3)) AS hdx_source_latency,
regexpExtract(requestHeadersStr, 'Referer:\s*(\S+)', 1) AS referer,
multiIf(
 arrayExists(x -> multiSearchAny(x, ['AKAMAI_CATEGORIZED']), ruleTags), 'Akamai',
 arrayExists(x -> multiSearchAny(x, ['CUST_DEFINED_BOTS']), ruleTags), 'Customer',
 'Unknown') AS bot_type,
multiIf(
 botData_responseSegment = 0, 'Human', 
 botData_responseSegment > 0, 'Bot', 
 'empty') AS responseSegment,
multiIf(
 botData_responseSegment = 0, 'Human',
 botData_responseSegment = 1, 'Cautious response', botData_responseSegment = 2, 'Strict response', 
 botData_responseSegment = 3, 'Aggressive response', botData_responseSegment = 4, 'Safeguard',
 'empty') AS responseSegmentDetails,
multiIf(
 clientData_telemetryType = 0, 'Web client (standard telemetry)',
 clientData_telemetryType = 1, 'Web client (inline telemetry)',
 clientData_telemetryType = 2, 'Native app (SDK)',
 'empty') AS telemetryType,
multiIf( bot_type = 'Akamai', arrayFilter(x -> multiSearchAny(x, ['3991']), rules),
         bot_type = 'Customer', arrayFilter(x -> multiSearchAny(x, ['BOT-6']), rules),
         bot_type = 'Unknown', arrayFilter(x -> multiSearchAny(x, ['3900','3903','3910','3912','3990']), rules), ['']) as BotCategoryAkamai,
arrayMap(x -> (indexOf(rules, x)), BotCategoryAkamai) as arrayMapIndex,
arrayStringConcat(arrayMap(x -> (ruleData[x] ), arrayMapIndex)) as botnet_id,
arrayStringConcat(arrayMap(x -> (ruleMessages[x] ), arrayMapIndex)) as bot_category, 
* 
FROM {STREAM}