SELECT
decodeURLComponent(requestHeadersStr) as requestHeadersStr, 
decodeURLComponent(responseHeadersStr) as responseHeadersStr, 
akamai_siem_extract(rulesStr) as rules,
akamai_siem_extract(ruleTagsStr) as ruleTags,
arrayResize(akamai_siem_extract(ruleDataStr), length(ruleTags), '') as ruleData, 
akamai_siem_extract(ruleActionsStr) as ruleActions,
akamai_siem_extract(ruleMessagesStr) as ruleMessages,
akamai_siem_extract(ruleVersionsStr) as ruleVersions,
arrayResize(akamai_siem_extract(ruleSelectorsStr), length(ruleTags), '') as ruleSelectors, 
akamai_extract_key_pair(requestHeadersStr,'\r\n', ':') as requestHeaders,
akamai_extract_key_pair(responseHeadersStr,'\r\n', ':') as responseHeaders,
arrayExists(x -> multiSearchAny(x, ['AKAMAI/BOT/','BOT/','CUSTOM/BOT/','MBS_CL']), ruleTags) as attack_bot, 
arrayExists(x -> multiSearchAny(x, ['ASE/','AKAMAI/POLICY/','OWASP_CRS/','AKAMAI/WAF','AKAMAI/WEB_ATTACK/']), ruleTags) as attack_waf,
arrayExists(x -> x = 'REPUTATION', ruleTags) as attack_reputation,
arrayExists(x -> startsWith(x, 'AKAMAI/CUSTOM'), ruleTags) as attack_custom,
arrayExists(x -> position(x, 'IPBLOCK') !=0, ruleTags) as attack_dos,
multiIf(
 arrayExists(x -> startsWith(x, 'Web Scrapers'), ruleMessages), 'Web Scrapers', 
 arrayExists(x -> startsWith(x, 'Scanning Tools'), ruleMessages), 'Scanning Tools', 
 arrayExists(x -> startsWith(x, 'Web Attackers'), ruleMessages), 'Web Attackers', 
 arrayExists(x -> startsWith(x, 'DOS Attacker'), ruleMessages), 'DOS Attacker', 
 Null) as ruleMessage,
 arrayFilter((x, y) -> y = 1, ['Bot','WAF', 'Reputation','Custom','DoS'], [attack_bot, attack_waf,attack_reputation,attack_custom,attack_dos]) AS attackTypes,
 arrayDistinct(arrayFilter(x -> multiSearchAny(x, ['AKAMAI/BOT/','BOT/','CUSTOM/BOT/','MBS_CL',':']), ruleTags)) as ruleTagsBot,
arrayDistinct(arrayFilter(x -> multiSearchAny(x, ['ASE/','AKAMAI/POLICY/','OWASP_CRS/','AKAMAI/WAF','AKAMAI/WEB_ATTACK/',':']), ruleTags)) as ruleTagsWAF,
arrayDistinct(arrayFilter(x -> multiSearchAny(x, ['IPBLOCK',':']), ruleTags)) as ruleTagsDOS,
requestHeaders['Sec-CH-UA'] AS CH_UA,
requestHeaders['User-Agent'] AS UA,
notEmpty(CH_UA) as has_CH_UA,
datediff('s', timestamp, now64(3)) as hdx_source_latency, 
regexpExtract(requestHeadersStr, 'Referer:\s*(\S+)', 1) as referer,
*
FROM
{STREAM}