{
 "title": "API observability",
 "tags": [
  "v1.0",
  "Required tables: apicontext_sampled_day"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "SELECT  CASE\nWHEN ${duration} <= 6 THEN '${logs}'\nWHEN ${duration} > 6 THEN '${apicontext_sampled_day}'\nEND"
   },
   { "name": "timestamp", "query": "startTime" },
   { "name": "filter" },
   {
    "name": "duration",
    "query": "SELECT dateDiff('hour', toDateTime(${__from:date:seconds}), toDateTime(${__to:date:seconds}))"
   },
   { "name": "apicontext_sampled_day", "query": "__SUMMARY_TABLE_NAME_1__" },
   {
    "name": "logs",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   },
   {
    "name": "cnt_all",
    "query": "SELECT IF(\n'${table}' = '${logs}',\n'COUNT()',\n'cnt_all'\n)"
   },
   {
    "name": "avg_responseTime",
    "query": "SELECT IF(\n'${table}' = '${logs}',\n'AVG(responseTime)',\n'avg_responseTime'\n)"
   },
   {
    "name": "avg_dns_lookup_time",
    "query": "SELECT IF(\n'${table}' = '${logs}',\n'AVG(dns)',\n'avg_dns_lookup_time'\n)"
   },
   {
    "name": "avg_tcp_connect_time",
    "query": "SELECT IF(\n'${table}' = '${logs}',\n'AVG(connect)',\n'avg_tcp_connect_time'\n)"
   },
   {
    "name": "avg_tls_handshake_time",
    "query": "SELECT IF(\n'${table}' = '${logs}',\n'AVG(tlsHandshake)',\n'avg_tls_handshake_time'\n)"
   },
   {
    "name": "avg_upload_time",
    "query": "SELECT IF(\n'${table}' = '${logs}',\n'AVG(upload)',\n'avg_upload_time'\n)"
   },
   {
    "name": "avg_processing_time",
    "query": "SELECT IF(\n'${table}' = '${logs}',\n'AVG(processing)',\n'avg_processing_time'\n)"
   },
   {
    "name": "avg_download_time",
    "query": "SELECT IF(\n'${table}' = '${logs}',\n'AVG(download)',\n'avg_download_time'\n)"
   },
   {
    "name": "raw_table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   }
  ]
 },
 "panels": [
  {
   "title": "API Observability",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Reports on network times, number of requests by categories, status codes, and location ID's."
   }
  },
  {
   "title": "All data within this dashboard is from public endpoints of various domains",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "HTTP codes",
   "type": "timeseries",
   "description": "Number of request group by HTTP Status Code.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \n  toStartOfInterval(${timestamp}, INTERVAL $__interval_s SECOND) AS time,\n  toString(httpCode),\n  ${cnt_all} as http\nFROM ${table}\nWHERE ${timestamp} >= toDateTime(${__from:date:seconds}) AND ${timestamp} <= toDateTime(${__to:date:seconds})\n  AND $__adHocFilter()\nGROUP BY time, httpCode\nLIMIT 10000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=HTTP codes; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Categories",
   "type": "timeseries",
   "description": "Number of requests per Context Category.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \n  toStartOfInterval(${timestamp}, INTERVAL $__interval_s SECOND) AS time,\n  toString(contextCategory),\n${cnt_all} AS Category\nFROM ${table}\nWHERE ${timestamp} >= toDateTime(${__from:date:seconds}) AND ${timestamp} <= toDateTime(${__to:date:seconds})\n  AND $__adHocFilter()\nGROUP BY time, contextCategory\nLIMIT 10000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Categories; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "description": "Average Response Time Along Time.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \n  toStartOfInterval(${timestamp}, INTERVAL $__interval_s SECOND) AS time,\n  ${avg_responseTime} AS \"Response Time\"\nFROM ${table}\nWHERE ${timestamp} >= toDateTime(${__from:date:seconds}) AND ${timestamp} <= toDateTime(${__to:date:seconds})\n  AND $__adHocFilter()\nGROUP BY time\nLIMIT 10000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Average response time; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top location IDs",
   "type": "piechart",
   "description": "Total Count and Percentage per Localtion ID.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  locationID,\n  ${cnt_all}\nFROM ${table}\nWHERE ${timestamp} >= toDateTime(${__from:date:seconds}) AND ${timestamp} <= toDateTime(${__to:date:seconds})\n  AND $__adHocFilter()\nGROUP BY locationID\nLIMIT 10000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top location IDs; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Average DNS lookup time",
   "type": "timeseries",
   "description": "Average DNS Time Along Time.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \n  toStartOfInterval(${timestamp}, INTERVAL $__interval_s SECOND) AS time,\n  ${avg_dns_lookup_time} AS \"DNS Lookup Time\"\nFROM ${table}\nWHERE ${timestamp} >= toDateTime(${__from:date:seconds}) AND ${timestamp} <= toDateTime(${__to:date:seconds})\n  AND $__adHocFilter()\nGROUP BY time\nLIMIT 10000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Average DNS lookup time; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Average TCP connect time",
   "type": "timeseries",
   "description": "Shows the Connect average time along time.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \n  toStartOfInterval(${timestamp}, INTERVAL $__interval_s SECOND) AS time,\n  ${avg_tcp_connect_time} AS \"TCP connect Time\"\nFROM ${table}\nWHERE ${timestamp} >= toDateTime(${__from:date:seconds}) AND ${timestamp} <= toDateTime(${__to:date:seconds})\n  AND $__adHocFilter()\nGROUP BY time\nLIMIT 10000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Average TCP connect time; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Average SSL handshake time",
   "type": "timeseries",
   "description": "Shows the average time for tlsHandshake.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \n  toStartOfInterval(${timestamp}, INTERVAL $__interval_s SECOND) AS time,\n  ${avg_tls_handshake_time} AS \"SSL handshake Time\"\nFROM ${table}\nWHERE ${timestamp} >= toDateTime(${__from:date:seconds}) AND ${timestamp} <= toDateTime(${__to:date:seconds})\n  AND $__adHocFilter()\nGROUP BY time\nLIMIT 10000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Average SSL handshake time; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Total networking time (DNS + TCP + SSL)",
   "type": "timeseries",
   "description": "Shows the sum of the averages of tlsHandshake, connect, and dns times.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \n  toStartOfInterval(${timestamp}, INTERVAL $__interval_s SECOND) AS time,\n  ${avg_tls_handshake_time} + ${avg_tcp_connect_time} + ${avg_dns_lookup_time} AS \"Networking Time\"\nFROM ${table}\nWHERE ${timestamp} >= toDateTime(${__from:date:seconds}) AND ${timestamp} <= toDateTime(${__to:date:seconds})\n  AND $__adHocFilter()\nGROUP BY time\nLIMIT 10000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Total networking time (DNS + TCP + SSL); du=${__user.login}'"
    }
   ]
  },
  {
   "title": "It shows the sum of the averages of tlsHandshake, connect, and dns.",
   "type": "timeseries",
   "description": "Shows the sum of the averages of connect, tlsHandshake, and upload times.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(${timestamp}, INTERVAL $__interval_s SECOND) AS time,\n  ${avg_tcp_connect_time} + ${avg_tls_handshake_time} + ${avg_upload_time} AS \"Networking Time\"\nFROM ${table}\nWHERE ${timestamp} >= toDateTime(${__from:date:seconds}) AND ${timestamp} <= toDateTime(${__to:date:seconds})\n  AND $__adHocFilter()\nGROUP BY time\nLIMIT 10000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Networking time excluding DNS; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Total time until first byte (including networking time)",
   "type": "timeseries",
   "description": "Shows the sum of the averages of dns, connect, tlsHandshake, and upload times.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(${timestamp}, INTERVAL $__interval_s SECOND) AS time,\n${avg_dns_lookup_time} + ${avg_tcp_connect_time} + ${avg_tls_handshake_time} + ${avg_upload_time} AS \"Networking Time\"\nFROM ${table}\nWHERE ${timestamp} >= toDateTime(${__from:date:seconds}) AND ${timestamp} <= toDateTime(${__to:date:seconds})\n  AND $__adHocFilter()\nGROUP BY time\nLIMIT 10000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Total time until first byte (including networking time); du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Total time until first byte (excluding DNS)",
   "type": "timeseries",
   "description": "Shows the sum of the averages of connect, tlsHandshake, and upload times.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(${timestamp}, INTERVAL $__interval_s SECOND) AS time,\n${avg_tcp_connect_time} + ${avg_tls_handshake_time} + ${avg_upload_time} AS \"Networking Time\"\nFROM ${table}\nWHERE ${timestamp} >= toDateTime(${__from:date:seconds}) AND ${timestamp} <= toDateTime(${__to:date:seconds})\n  AND $__adHocFilter()\nGROUP BY time\nLIMIT 10000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Total time until first byte (excluding DNS); du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Total time (excluding DNS)",
   "type": "timeseries",
   "description": "Shows the sum of the averages of connect, tlsHandshake,upload, and processing times.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(${timestamp}, INTERVAL $__interval_s SECOND) AS time,\n${avg_tcp_connect_time} + ${avg_tls_handshake_time} + ${avg_upload_time} + ${avg_processing_time} + ${avg_download_time} AS \"Networking Time\"\nFROM ${table}\nWHERE ${timestamp} >= toDateTime(${__from:date:seconds}) AND ${timestamp} <= toDateTime(${__to:date:seconds})\n  AND $__adHocFilter()\nGROUP BY time\nLIMIT 10000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Total time (excluding DNS); du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Total time (including DNS)",
   "type": "timeseries",
   "description": "Shows the sum of the averages of dns, connect, tlsHandshake,  and download times.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(${timestamp}, INTERVAL $__interval_s SECOND) AS time,\n  ${avg_dns_lookup_time} + ${avg_tcp_connect_time} + ${avg_tls_handshake_time} + ${avg_download_time} as \"Networking Time\"\nFROM ${table}\nWHERE ${timestamp} >= toDateTime(${__from:date:seconds}) AND ${timestamp} <= toDateTime(${__to:date:seconds})\n  AND $__adHocFilter()\nGROUP BY time\nLIMIT 10000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Total time (including DNS); du=${__user.login}'"
    }
   ]
  }
 ]
}