SELECT
toUnixTimestamp(toDateTime (toStartOfSecond (reqTimeSec)))::UInt32 as ts_sec_idx,
datediff('s', reqTimeSec, now64(3)) as hdx_source_latency,
decodeURLComponent(assumeNotNull(UA)) as UA,
decodeURLComponent(assumeNotNull(referer)) as referer,
decodeURLComponent(assumeNotNull(queryStr)) as queryStr,
extract(decodeURLComponent(assumeNotNull(breadcrumbs)), '\/\/BC\/(\S*)') as breadcrumbs,
akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=g[^]]*\])', 'a=([^,\]]+)') as Edge_IP,
akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=g[^]]*\])', 'b=([^,\]]+)') as Edge_RequestID,
akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=g[^]]*\])', 'k=([^,\]]+)') as Edge_RequestEndTime,
akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=g[^]]*\])', 'l=([^,\]]+)') as Edge_TurnAroundTime,
akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=g[^]]*\])', 'm=([^,\]]+)') as Edge_DNSLookupTime,
akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=g[^]]*\])', 'n=([^,\]]+)') as Edge_GeoInfo,
akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=g[^]]*\])', 'o=([^,\]]+)') as Edge_ASN,
akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=o[^]]*\])', 'a=([^,\]]+)') as Origin_IP,
akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=o[^]]*\])', 'b=([^,\]]+)') as Origin_RequestID,
akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=o[^]]*\])', 'k=([^,\]]+)') as Origin_RequestEndTime,
akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=o[^]]*\])', 'l=([^,\]]+)') as Origin_TurnAroundTime,
akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=o[^]]*\])', 'm=([^,\]]+)') as Origin_DNSLookupTime,
akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=o[^]]*\])', 'n=([^,\]]+)') as Origin_GeoInfo,
akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=o[^]]*\])', 'o=([^,\]]+)') as Origin_ASN,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=p[^]]*\])', 'a=([^,\]]+)') as Peer_IP,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=p[^]]*\])', 'b=([^,\]]+)') as Peer_RequestID,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=p[^]]*\])', 'k=([^,\]]+)') as Peer_RequestEndTime,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=p[^]]*\])', 'l=([^,\]]+)') as Peer_TurnAroundTime,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=p[^]]*\])', 'm=([^,\]]+)') as Peer_DNSLookupTime,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=p[^]]*\])', 'n=([^,\]]+)') as Peer_GeoInfo,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=p[^]]*\])', 'o=([^,\]]+)') as Peer_ASN,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=c[^]]*\])', 'a=([^,\]]+)') as Parent_IP,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=c[^]]*\])', 'b=([^,\]]+)') as Parent_RequestID,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=c[^]]*\])', 'k=([^,\]]+)') as Parent_RequestEndTime,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=c[^]]*\])', 'l=([^,\]]+)') as Parent_TurnAroundTime,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=c[^]]*\])', 'm=([^,\]]+)') as Parent_DNSLookupTime,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=c[^]]*\])', 'n=([^,\]]+)') as Parent_GeoInfo,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=c[^]]*\])', 'o=([^,\]]+)') as Parent_ASN,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=w[^]]*\])', 'a=([^,\]]+)') as CloudWrapper_IP,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=w[^]]*\])', 'b=([^,\]]+)') as CloudWrapper_RequestID,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=w[^]]*\])', 'k=([^,\]]+)') as CloudWrapper_RequestEndTime,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=w[^]]*\])', 'l=([^,\]]+)') as CloudWrapper_TurnAroundTime,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=w[^]]*\])', 'm=([^,\]]+)') as CloudWrapper_DNSLookupTime,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=w[^]]*\])', 'n=([^,\]]+)') as CloudWrapper_GeoInfo,
akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=w[^]]*\])', 'o=([^,\]]+)') as CloudWrapper_ASN,
assumeNotNull(decodeURLComponent(cmcd)) as url_cmcd,
concat('/', assumeNotNull(reqPath)) as reqPath,
if(startsWith(url_cmcd, '//x.x@U/'), substring(url_cmcd, 9), url_cmcd) as url,
flatten(extractAllGroupsVertical(assumeNotNull(url), '([^=,"]+)="?([^,="]+)"? ?')) as groups,
akamai_cmcd_query_param('bl', groups) as cmcd_buffer_length,
akamai_cmcd_query_param('br', groups) as cmcd_encoded_bitrate,
url LIKE '%,bs,%' ? 1 : 0 as cmcd_buffer_starvation,
akamai_cmcd_query_param('cid', groups) as cmcd_content_id,
akamai_cmcd_query_param('d', groups) as cmcd_object_duration,
akamai_cmcd_query_param('dl', groups) as cmcd_deadline,
akamai_cmcd_query_param('mtp', groups) as cmcd_measured_throughput,
akamai_cmcd_query_param('nor', groups) as cmcd_next_object_requests,
akamai_cmcd_query_param('nrr', groups) as cmcd_next_range_request,
akamai_cmcd_object_type(akamai_cmcd_query_param('ot', groups)) as cmcd_object_type,
akamai_cmcd_query_param('pr', groups) as cmcd_playback_rate,
akamai_cmcd_query_param('rtp', groups) as cmcd_requested_max_throughput,
akamai_cmcd_streaming_format(akamai_cmcd_query_param('sf', groups)) as cmcd_streaming_format,
akamai_cmcd_query_param('sid', groups) as cmcd_session_id,
akamai_cmcd_stream_type(akamai_cmcd_query_param('st', groups)) as cmcd_stream_type,
url LIKE '%,su,%' ? 1 : 0 as cmcd_startup,
akamai_cmcd_query_param('tb', groups) as cmcd_top_bitrate,
akamai_cmcd_query_param('v', groups) as cmcd_version,
akamai_cmcd_query_param('d', groups) as cmcd_playback_duration,
splitByChar(':', lower(assumeNotNull(reqHost)))[1] as reqHost,
position(assumeNotNull(contentProtectionInfo), 'epd') >= 1 as epd_Match,
splitByString('/', assumeNotNull(contentProtectionInfo))[5] as epd_Code,
splitByString('/', assumeNotNull(contentProtectionInfo))[6] as epd_ActionCode,
multiIf(epd_Code='av', 'Anonymous VPN',
    epd_Code='pp','Public Proxy',
    epd_Code='hp','Hosting Provder',
    epd_Code='tr','TOR Exit Node',
    epd_Code='dp','Smart DNS Proxy',
    epd_Code='rp','Residential Proxy',
    epd_Code='vc','VPN Data Centre','')
as epd_Category,
multiIf(epd_ActionCode='0', 'Request Denied',
    epd_ActionCode='1', 'Request Allowed(override)',
    epd_ActionCode='2', 'Request Redirected', '')
as epd_ActionName,
splitByChar('|',assumeNotNull(securityRules))[1] as policy,
splitByChar('|',assumeNotNull(securityRules))[3] as denyRule,
if(empty(splitByChar('|',assumeNotNull(securityRules))[3]),0,1) as denied,
multiIf(denyRule like '%REP%','Reputation',
	denyRule like '3%' or denyRule like 'BOT-%', 'BOT',
	denyRule like 'IP%', 'DOS',
	denyRule like 'XSS%' or denyRule like 'WAT-%' or denyRule like 'RFI-ANOMALY%' or denyRule like 'PLATFORM-ANOMALY' or  denyRule like 'SQL%' or denyRule like 'LFI%' or denyRule like 'CMD-INJECTION%' or denyRule like 'PROTOCOL-ANOMALY%'  or denyRule like 'ADAPTIVE_UA_IP_BLOCK%' or denyRule like '6%', 'WAF Rule',
	''
	) as denyGroup,
splitByChar('|',assumeNotNull(earlyHints))[1] as userHints,
splitByChar('|',assumeNotNull(earlyHints))[2] as userHintsBytes,
splitByChar('|',assumeNotNull(earlyHints))[3] as akamaiHints,
splitByChar('|',assumeNotNull(earlyHints))[4] as akamaiHintsBytes,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[1] as ew_stageInformation,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[2] as ew_ID,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[3] as ew_processTime,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[4] as ew_totalTime,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[5] as ew_totalStageTime,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[6] as ew_usedMemory,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[7] as ew_edgeServerFlow,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[8] as ew_errorCode,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[9] as ew_httpStatus,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[10] as ew_cpuFlits,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[11] as ew_tierID,
akamai_edge_worker(assumeNotNull(ewUsageInfo))[1] as ew_uID,
akamai_edge_worker(assumeNotNull(ewUsageInfo))[2] as ew_version,
akamai_edge_worker(assumeNotNull(ewUsageInfo))[3] as ew_eventHandler,
akamai_edge_worker(assumeNotNull(ewUsageInfo))[4] as ew_offReason,
akamai_edge_worker(assumeNotNull(ewUsageInfo))[5] as ew_logicExecuted,
akamai_edge_worker(assumeNotNull(ewUsageInfo))[6] as ew_status,
akamai_edge_worker(assumeNotNull(ewUsageInfo))[7] as ew_revisionID,
akamai_edge_worker(assumeNotNull(ewUsageInfo))[8] as ew_metrics,
splitByChar(':',splitByChar('|',coalesce(assumeNotNull(securityRules),'||'))[2]) as rulesTriggered,
concat(reqHost, reqPath) as URL,
multiIf(
cacheStatus=1,1,
breadcrumbs IS NULL OR empty(breadcrumbs),0,
Origin_IP IS NULL OR empty(Origin_IP),1,0
) as cacheStatus,
*,
    'Akamai' AS hdx_cdn,
    dictGet('ua_cat_dict', 'ua_category', assumeNotNull(UA)) AS userAgentCategory,
    dictGet('ua_cat_dict', 'ua_category_key', assumeNotNull(UA)) AS userAgentCategoryKey,
    dictGet('ua_cat_dict', 'ai_category', assumeNotNull(UA)) AS aiCategory,
    dictGet('ua_cat_dict', 'is_bot', assumeNotNull(UA)) AS isBotTraffic,
    dictGet('ua_cat_dict', 'bot_class', assumeNotNull(UA)) AS botClass,
    dictGet('ua_cat_dict', 'bot_intent', assumeNotNull(UA)) AS botIntent,
    dictGet('ua_cat_dict', 'producer', assumeNotNull(UA)) AS botProducer,
    multiIf(positionCaseInsensitive(assumeNotNull(reqPath), 'robots.txt') > 0, 'robots.txt', positionCaseInsensitive(assumeNotNull(reqPath), 'sitemap.xml') > 0, 'sitemap.xml', positionCaseInsensitive(assumeNotNull(reqPath), 'ads.txt') > 0, 'ads.txt', positionCaseInsensitive(assumeNotNull(reqPath), 'llms.txt') > 0, 'llms.txt', match(assumeNotNull(reqPath), '^/api/') OR match(assumeNotNull(reqPath), '/api/'), 'api', match(assumeNotNull(reqPath), '\\.(css|js|png|jpg|jpeg|gif|svg|ico|woff2?|ttf|eot)$'), 'static', match(assumeNotNull(reqPath), '\\.(html?|php|asp|jsp)$') OR assumeNotNull(reqPath) = '/' OR NOT match(assumeNotNull(reqPath), '\\.'), 'page', 'other') AS resourceCategory,
    dictGetOrDefault('asn_type_dict', 'asn_type', toUInt32OrZero(toString(asn)), 'unknown') AS asnType,
    dictGetOrDefault('bot_ip_dict', 'bot_owner', toIPv4OrDefault(assumeNotNull(cliIP)), '') AS verifiedBotOwner,
    multiIf(isBotTraffic = 1 AND verifiedBotOwner != '', 'verified', isBotTraffic = 1 AND asnType = 'isp', 'declared_unverified', isBotTraffic = 1, 'unverified', 'not_bot') AS botVerificationTier,
    multiIf(isBotTraffic = 1 AND verifiedBotOwner != '', 'verified', isBotTraffic = 1 AND asnType = 'isp', 'suspicious', isBotTraffic = 1 AND asnType IN ('hosting', 'business'), 'plausible', isBotTraffic = 1, 'unverified', 'not_bot') AS botConfidence,
    lower(cutQueryString(coalesce(reqPath, ''))) AS requestPathNorm,
if(arrayStringConcat(arrayMap(seg -> multiIf(seg IN (':num', ':version', ':hex', ':asset', ':token'), seg, has(['api', 'graphql', 'checkout', 'login', 'auth', 'oauth', 'sso', 'account', 'accounts', 'user', 'users', 'profile', 'customer', 'customers', 'search', 'cart', 'product', 'products', 'pd', 'category', 'categories', 'content', 'static', 'assets', 'asset', 'images', 'image', 'img', 'media', 'dist', 'js', 'css', 'json', 'fonts', 'font', 'store', 'stores', 'shop', 'catalog', 'collections', 'collection', 'loyalty', 'rates', 'rooms', 'blogs', 'wp-admin', 'admin', '_sec', '_bm', 'akam', 'm', 'mobile', 'web', 'app', 'client-api', 'internal', 'live', 'vod', 'hls', 'cmaf', 'feeds', 'feed', 'logos', 'logo', 'scoreboard', 'channels', 'channel', 'event', 'events', 'card', 'cards', 'leagues', 'league', 'teams', 'team', 'public', 'latest', 'client', 'tabs', 'subscriber', 'manage', 'include', 'redirect_flags', 'traffic', 'exchange', 'chunks', 'chunk', 'whitelist', 'livedata', 'odds'], seg), seg, match(seg, '^[a-z]{2}(-[a-z]{2})?$'), ':locale', ':slug'), arrayMap(seg -> multiIf(seg = '', '', match(seg, '^[0-9]+$'), ':num', match(seg, '^v?[0-9]+(\\.[0-9]+)+$'), ':version', match(seg, '^[0-9a-f]{8,}$'), ':hex', match(seg, '\\.(css|js|png|jpe?g|gif|svg|ico|woff2?|ttf|eot|map|json|xml|webp|avif|mp4|m3u8|ts|pdf)$'), ':asset', length(seg) >= 6 AND match(seg, '[0-9]') AND match(seg, '[a-z]') AND match(seg, '^[a-z0-9_-]+$'), ':token', seg), splitByChar('/', trim(BOTH '/' FROM lower(ifNull(requestPathNorm, '')))))), '/') = '', '/', concat('/', arrayStringConcat(arrayMap(seg -> multiIf(seg IN (':num', ':version', ':hex', ':asset', ':token'), seg, has(['api', 'graphql', 'checkout', 'login', 'auth', 'oauth', 'sso', 'account', 'accounts', 'user', 'users', 'profile', 'customer', 'customers', 'search', 'cart', 'product', 'products', 'pd', 'category', 'categories', 'content', 'static', 'assets', 'asset', 'images', 'image', 'img', 'media', 'dist', 'js', 'css', 'json', 'fonts', 'font', 'store', 'stores', 'shop', 'catalog', 'collections', 'collection', 'loyalty', 'rates', 'rooms', 'blogs', 'wp-admin', 'admin', '_sec', '_bm', 'akam', 'm', 'mobile', 'web', 'app', 'client-api', 'internal', 'live', 'vod', 'hls', 'cmaf', 'feeds', 'feed', 'logos', 'logo', 'scoreboard', 'channels', 'channel', 'event', 'events', 'card', 'cards', 'leagues', 'league', 'teams', 'team', 'public', 'latest', 'client', 'tabs', 'subscriber', 'manage', 'include', 'redirect_flags', 'traffic', 'exchange', 'chunks', 'chunk', 'whitelist', 'livedata', 'odds'], seg), seg, match(seg, '^[a-z]{2}(-[a-z]{2})?$'), ':locale', ':slug'), arrayMap(seg -> multiIf(seg = '', '', match(seg, '^[0-9]+$'), ':num', match(seg, '^v?[0-9]+(\\.[0-9]+)+$'), ':version', match(seg, '^[0-9a-f]{8,}$'), ':hex', match(seg, '\\.(css|js|png|jpe?g|gif|svg|ico|woff2?|ttf|eot|map|json|xml|webp|avif|mp4|m3u8|ts|pdf)$'), ':asset', length(seg) >= 6 AND match(seg, '[0-9]') AND match(seg, '[a-z]') AND match(seg, '^[a-z0-9_-]+$'), ':token', seg), splitByChar('/', trim(BOTH '/' FROM lower(ifNull(requestPathNorm, '')))))), '/'))) AS requestPathPattern,
    if(notEmpty(aiCategory), botProducer, '') AS aiSource,
    multiIf(isBotTraffic = 0, 'Human', notEmpty(aiCategory), 'AI', 'Bot') AS trafficCohort
FROM {STREAM}
