folders:
  hdx-main-folder:
    name: TrafficPeak Certified Reference Dashboards
    children:
      hdx-security-folder:
        name: Security
dashboards:
  hdx-raw-logs:
    dashboard:
      __extend__: dashboards/raw_logs.json
    folderUid: hdx-security-folder
    inputs:
      DS_HYDROLIX-HYDROLIX-DATASOURCE: hdx-hydrolix-datasource
      VAR_TABLE: __PROJECT_NAME__.__TABLE_NAME__
      VAR_TIMESTAMP: timestamp
  hdx-cdn-dashboard-default:
    dashboard:
      __extend__: dashboards/cdn_dashboard_default.json
    folderUid: hdx-security-folder
    inputs:
      DS_HYDROLIX-HYDROLIX-DATASOURCE: hdx-hydrolix-datasource
      VAR_SUMMARY_MIN: __SUMMARY_TABLE_NAME_2__
      VAR_SUMMARY_HOUR: __SUMMARY_TABLE_NAME_1__
      VAR_QUANTILES_RESPONSE_TTFB_50: quantiles_response_ttfb_ms[2]
      VAR_QUANTILES_RESPONSE_TTFB_95: quantiles_response_ttfb_ms[5]
      VAR_QUANTILES_RESPONSE_TTLB_50: quantiles_response_ttlb_ms[2]
      VAR_QUANTILES_RESPONSE_TTLB_95: quantiles_response_ttlb_ms[5]
      VAR_QUANTILES_ORIGIN_TTFB_50: quantiles_origin_ttfb_ms[2]
      VAR_QUANTILES_ORIGIN_TTFB_95: quantiles_origin_ttfb_ms[5]
      VAR_QUANTILES_ORIGIN_TTLB_50: quantiles_origin_ttlb_ms[2]
      VAR_QUANTILES_ORIGIN_TTLB_95: quantiles_origin_ttlb_ms[5]
      VAR_RAW_LOGS: UUID_HERE/NAME
      VAR_CDN_PANEL: UUID_HERE/NAME
  hdx-cdn-global-view:
    dashboard:
      __extend__: dashboards/cdn_global_view.json
    folderUid: hdx-security-folder
    inputs:
      DS_HYDROLIX-HYDROLIX-DATASOURCE: hdx-hydrolix-datasource
      VAR_SUMMARY_MIN: __PROJECT_NAME__.__SUMMARY_TABLE_NAME_2__
      VAR_SUMMARY_HOUR: __PROJECT_NAME__.__SUMMARY_TABLE_NAME_1__
      VAR_CDN1: Akamai
      VAR_RAW_LOGS: UUID_HERE/raw-logs
      VAR_CDN_PANEL: UUID_HERE/cdn-dashboard-default-v1-0-5
