{
 "title": "mPulse Performance by Group",
 "tags": [
  "core analysis",
  "v1.0",
  "add-on"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "mpulse", "query": "${VAR_MPULSE}" },
   {
    "name": "groupBy",
    "query": "Hostname : pageDomainName , Page Group : pageGroupName , URL : paramsU , Country : countryCode , Beacon Type : beaconTypeName"
   },
   { "name": "topN", "query": "${VAR_TOPN}" },
   {
    "name": "timer",
    "query": " DNS : dnsTimer  , SSL : sslTimer , TTFB : firstByteTimer ,  DOM Loaded : timersTDomloaded , LCP : largestContentfulPaint ,  PageLoad : timersLoaded "
   },
   {
    "name": "aggregation",
    "query": "Average : avg , Median : quantile(0.5) , P75 : quantile(0.75) , P90 : quantile(0.90) , P95 : quantile(0.95) , P99 : quantile(0.99)"
   },
   { "name": "maxTreemapCells", "query": "${VAR_MAXTREEMAPCELLS}" },
   {
    "name": "pageDomainName",
    "label": "Hostname",
    "query": "SELECT pageDomainName FROM ${mpulse} WHERE $__timeFilter(timestamp) AND notEmpty(pageDomainName) GROUP BY pageDomainName ORDER BY count() DESC LIMIT 50"
   },
   {
    "name": "pageGroupName",
    "label": "Page Group Name",
    "query": "SELECT pageGroupName FROM ${mpulse} WHERE $__timeFilter(timestamp) AND notEmpty(pageGroupName) GROUP BY pageGroupName ORDER BY count() DESC LIMIT 50"
   },
   {
    "name": "beaconTypeName",
    "label": "Beacon Type",
    "query": "SELECT beaconTypeName FROM ${mpulse} WHERE $__timeFilter(timestamp) AND notEmpty(beaconTypeName) GROUP BY beaconTypeName ORDER BY count() DESC LIMIT 50"
   },
   {
    "name": "isp",
    "query": "SELECT isp FROM ${mpulse} WHERE $__timeFilter(timestamp) AND notEmpty(isp) GROUP BY isp ORDER BY count() DESC LIMIT 50"
   },
   {
    "name": "countryCode",
    "label": "Country",
    "query": "SELECT countryCode FROM ${mpulse} WHERE $__timeFilter(timestamp) AND notEmpty(countryCode) GROUP BY countryCode ORDER BY count() DESC LIMIT 50"
   },
   {
    "name": "regionCode",
    "label": "State",
    "query": "SELECT regionCode FROM ${mpulse} WHERE $__timeFilter(timestamp) AND notEmpty(regionCode) GROUP BY regionCode ORDER BY count() DESC LIMIT 50"
   },
   {
    "name": "geoCity",
    "label": "City",
    "query": "SELECT geoCity FROM ${mpulse} WHERE $__timeFilter(timestamp) AND notEmpty(geoCity) GROUP BY geoCity ORDER BY count() DESC LIMIT 50"
   },
   {
    "name": "deviceTypeName",
    "query": "SELECT deviceTypeName FROM ${mpulse} WHERE $__timeFilter(timestamp) AND notEmpty(deviceTypeName) GROUP BY deviceTypeName ORDER BY count() DESC LIMIT 50"
   },
   { "name": "paramsULike", "label": "URL like" },
   { "name": "omniFilter", "label": "Omni Filter" },
   {
    "name": "paramsU",
    "label": "URL",
    "query": "SELECT paramsU FROM ${mpulse} WHERE $__timeFilter(timestamp) AND notEmpty(paramsU) GROUP BY paramsU ORDER BY count() DESC LIMIT 50"
   },
   {
    "name": "raw_table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Understand how any performance measurement (LCP, PageLoad, Backend Time, INP, etc) varies across multiple dimensions (Page Group, Device Type, Country, Browser, URL etc)"
   }
  },
  {
   "title": "Timers Over Time (use 'GroupBy filter to pick grouping)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "Page Views per ${groupBy}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "WITH top10 AS (\n  SELECT ${groupBy}\n  FROM ${mpulse}\n  WHERE $__timeFilter(timestamp)\n   AND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n    ${omniFilter}\n  GROUP BY ${groupBy}\n  ORDER BY COUNT(*) DESC\n  LIMIT ${topN}\n)\n\nSELECT ${groupBy}, \n       COUNT(*) AS \"-\",\n       $__timeInterval(timestamp) AS time\nFROM ${mpulse}\nWHERE $__timeFilter(timestamp)\n  AND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n  ${omniFilter}\nGROUP BY time, ${groupBy}\nORDER BY time ASC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Page Views per ...; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Timer Treemaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "${timer} by Hostname(${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT \n  coalesce(pageDomainName,'(None)') as item, \n  count(*) as count,\n  ${aggregation}(${timer}) as metric\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\n AND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n${omniFilter}\ngroup  by item\norder by count desc \nlimit ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=...by Hostname(...); du=${__user.login}'"
      }
     ]
    },
    {
     "title": "${timer} by Page Group(${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT coalesce(pageGroupName,'(None)') as item, \n  count(*) as count,\n  ${aggregation}(${timer}) as metric\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n${omniFilter}\ngroup  by item\norder by count desc \nlimit ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=...by Page Group(...); du=${__user.login}'"
      }
     ]
    },
    {
     "title": "${timer} by URL (${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT replaceOne(coalesce(paramsU,'(None)'),'undefined','undefine_d') as item, \n  count(*) as count,\n  ${aggregation}(${timer}) as metric\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n${omniFilter}\ngroup  by item\norder by count desc \nlimit ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=...by URL(...); du=${__user.login}'"
      }
     ]
    },
    {
     "title": "${timer} by Device Type (${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 37 },
     "targets": [
      {
       "rawSql": "SELECT coalesce(deviceTypeName,'(None)') as item, \n  count(*) as count,\n  ${aggregation}(${timer}) as metric\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n${omniFilter}\ngroup  by item\norder by count desc \nlimit ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=...by Device Type(...); du=${__user.login}'"
      }
     ]
    },
    {
     "title": "${timer} by Beacon Type (${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 37 },
     "targets": [
      {
       "rawSql": "SELECT coalesce(beaconTypeName,'(None)') as item, \n  count(*) as count,\n  ${aggregation}(${timer}) as metric\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n${omniFilter}\ngroup  by item\norder by count desc \nlimit ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=...by Beacon Type(...); du=${__user.login}'"
      }
     ]
    },
    {
     "title": "${timer} by ISP (${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 37 },
     "targets": [
      {
       "rawSql": "SELECT coalesce(isp,'(None)') as item, \n  count(*) as count,\n  ${aggregation}(${timer}) as metric\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n${omniFilter}\ngroup  by item\norder by count desc \nlimit ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=...by ISP(...); du=${__user.login}'"
      }
     ]
    },
    {
     "title": "${timer} by Country (${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 48 },
     "targets": [
      {
       "rawSql": "SELECT coalesce(countryCode,'(None)') as item, \n  count(*) as count,\n  ${aggregation}(${timer}) as metric\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n${omniFilter}\ngroup  by item\norder by count desc \nlimit ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=...by Country(...); du=${__user.login}'"
      }
     ]
    },
    {
     "title": "${timer} by State (${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 48 },
     "targets": [
      {
       "rawSql": "SELECT coalesce(regionCode,'(None)') as item, \n  count(*) as count,\n  ${aggregation}(${timer}) as metric\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n${omniFilter}\ngroup  by item\norder by count desc \nlimit ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=...by State(...); du=${__user.login}'"
      }
     ]
    },
    {
     "title": "${timer} by City (${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 48 },
     "targets": [
      {
       "rawSql": "SELECT coalesce(geoCity,'(None)') as item, \n  count(*) as count,\n  ${aggregation}(${timer}) as metric\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n${omniFilter}\ngroup  by item\norder by count desc \nlimit ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=...by City(...); du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Raw Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "SELECT concat(toString(timestamp), ' - ', beaconTypeName,' - ', pageGroupName) , * \nFROM  ${mpulse}\nwhere $__timeFilter(timestamp)\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n${omniFilter}\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Raw; du=${__user.login}'"
      }
     ]
    }
   ]
  }
 ]
}