folders:
  hdx-main-folder:
    name: TrafficPeak Certified Reference Dashboards
    children: {}
dashboards:
  hdx-siem-raw-logs:
    dashboard:
      __extend__: dashboards/SIEM Raw Logs.json
    folderUid: hdx-main-folder
  hdx-security-analysis:
    dashboard:
      __extend__: dashboards/Security Analysis.json
    folderUid: hdx-main-folder
  hdx-akamai-siem:
    dashboard:
      __extend__: dashboards/Akamai SIEM.json
    folderUid: hdx-main-folder
