{
 "title": "CDN Insights- Global View",
 "tags": [
  "v1.0",
  "mcdn"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "raw_table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   },
   {
    "name": "table",
    "query": "SELECT  CASE\nWHEN ${duration} <= 24 THEN '${summary_min}'\nWHEN ${duration} > 24 THEN '${summary_hour}'\nEND"
   },
   {
    "name": "seconds",
    "query": "SELECT  CASE\nWHEN ${duration} <= 24 THEN 60\nWHEN ${duration} > 24 THEN 3600\nEND"
   },
   {
    "name": "summary_min",
    "query": "__PROJECT_NAME__.mcdn_summary_min"
   },
   {
    "name": "summary_hour",
    "query": "__PROJECT_NAME__.mcdn_summary_hour"
   },
   { "name": "cdn1", "query": "Akamai" },
   {
    "name": "item_formatted_for_display",
    "query": "SELECT $$\n  CASE\n    WHEN ${next_dim} IS NULL THEN '__null__'\n    WHEN ${next_dim} = '' THEN '__empty__'\n    ELSE REPLACE(${next_dim}, 'undefined', 'undef')\n  END\n$$"
   },
   {
    "name": "item_formatted_for_filter",
    "query": "SELECT $$\n  CASE\n    WHEN ${next_dim} IS NULL THEN '__null__'\n    WHEN ${next_dim} = '' THEN '__empty__'\n    ELSE\n      REPLACE(\n        REPLACE(\n          COALESCE(${next_dim}, '__null__'),\n          ',', '__gfc__'\n        ),\n        '|', '__gfp__'\n      )\n  END\n$$"
   },
   {
    "name": "next_dim",
    "query": "WITH\n    '${filter:raw}' AS flt,\n    ${drill_chain} as drill_chain,\n    arrayFilter(dim -> '${treeMapGroupBy}' != dim, drill_chain) as filtered,\n    arrayConcat(['${treeMapGroupBy}'], filtered) as reordered,\n    arrayFilter(dim -> position(flt, dim) = 0, reordered) AS remaining\nSELECT \nif(\n    (if(empty(remaining), '${treeMapGroupBy}', remaining[1])) = 'statusCode', 'toString(statusCode)',\n    (if(empty(remaining), '${treeMapGroupBy}', remaining[1]))\n  ) AS result"
   },
   { "name": "filter" },
   {
    "name": "drill_chain",
    "query": "SELECT $$[${customize_drilldown_order:singlequote}]$$"
   },
   {
    "name": "treeMapGroupBy",
    "label": "Focus On:",
    "query": "CDN : hdx_cdn, ASN : client_asn, Hostname : request_host, Edge pop : edge_pop"
   },
   {
    "name": "drill_chain_for_display",
    "query": "WITH map(\n    'hdx_cdn', 'CDN',\n    'client_asn', 'ASN',\n    'request_host', 'Hostname',\n    'edge_pop', 'Edge pop'\n) AS display_name_map\nSELECT arrayStringConcat(\n    arrayMap(\n        x -> if(x = '${next_dim}',\n                concat('<span style=\"display: inline-block; vertical-align: middle; background-color: #3787F3; color: white; padding: 3px 8px; border-radius: 4px;\">', display_name_map[x], '</span>'),\n                concat('<span style=\"display: inline-block; vertical-align: middle; background-color: #202226; border: 1px solid #333740; color: #9FA9B8; padding: 3px 8px; border-radius: 4px;\">', display_name_map[x], '</span>')\n        ),\n        ${drill_chain}\n    ),\n    ' <span style=\"color:#565a64;\">→</span> '\n)"
   },
   {
    "name": "next_dim_for_display",
    "query": "WITH map(\n    'hdx_cdn', 'CDN',\n    'client_asn', 'ASN',\n    'request_host', 'Hostname',\n    'request_host', 'Edge pop'\n) AS display_name_map\nSELECT display_name_map['${next_dim}']"
   },
   {
    "name": "customize_drilldown_order",
    "label": "Customize \"Drilldown Path\" Order",
    "query": "CDN : hdx_cdn, ASN : client_asn, Hostname : request_host, Edge pop : edge_pop"
   },
   { "name": "minErrorRate", "label": "Min Error Rate", "query": "0.00" },
   {
    "name": "duration",
    "query": "SELECT datediff('h', $__fromTime, $__toTime)"
   }
  ]
 },
 "panels": [
  {
   "title": "Drilldown Path:",
   "type": "text",
   "description": "The bolded item is the dimension currently displayed in the TreeMaps. Click any TreeMap cell to filter by that value and advance to the next step. Use the \"Customize Drilldown Order\" dropdown above to change the order of the dimensions.\nTo inspect the \"Raw Logs\", click on any square in the Treemap and select \"View Raw Logs\".",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n${drill_chain_for_display:text}\n\n💡 *Use the \"Customize \"Drilldown Path\" Order\" dropdown above to change the drilldown order of the dimensions.*"
   }
  },
  {
   "title": "${next_dim_for_display} by HTTP Error Rate (>${minErrorRate})",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT  \r\n    ${item_formatted_for_display} as item,\r\n    ${item_formatted_for_filter} as filter_item, \r\n    cnt_all as count,\r\n    countMergeIf(\r\n        `count()`,\r\n        response_status_code >= '400'\r\n        AND response_status_code < '600'\r\n    ) as errorcount,\r\n    errorcount / cnt_all AS error_ratio\r\nFROM ${table}\r\nWHERE $__timeFilter(timestamp)\r\n    AND $__adHocFilter() \r\nGROUP BY item, filter_item\r\nORDER BY count DESC\r\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Treemap; du=${__user.login}'"
    }
   ]
  },
  { "title": "CDN Rollup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Edge Cache Hit Total %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    (SUM(cache_hit) / (SUM(cache_hit) + SUM(cache_miss))) AS total,\n    hdx_cdn\nFROM \n(\n    SELECT \n        countMergeIf(`count()`,cache_was_cached = 1) AS cache_hit,\n        countMergeIf(`count()`,cache_was_cached = 0) AS cache_miss,\n        hdx_cdn\n    FROM \n        ${table}\n    WHERE \n        $__timeFilter(timestamp)\n        AND $__adHocFilter()\n        GROUP BY \n            hdx_cdn\n)\nGROUP BY \n    hdx_cdn\nORDER BY hdx_cdn\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Akamai Cache Hit Total %; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Peak Throughput Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    response_total_bytes AS theBytes,\n    timestamp as time,\n    hdx_cdn\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n    AND $__adHocFilter()\nGROUP BY \n    timestamp, hdx_cdn\nORDER BY hdx_cdn\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Akamai Current Traffic; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp,\n  response_total_bytes*8/${seconds} AS TotalThroughput\nFROM\n  ${table}\nWHERE\n  $__timeFilter(timestamp)\n  AND $__adHocFilter()\nGROUP BY timestamp\nORDER BY timestamp\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Total Edge Traffic; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Throughput by CDN",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "rawSql": "SELECT \n    timestamp as time,\n    response_total_bytes*8/${seconds} AS Throughput,\n    hdx_cdn AS CDN\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n  AND $__adHocFilter()\nGROUP BY \n    time, CDN \nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Akamai Current Traffic; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Throughput by CDN",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "rawSql": "SELECT \n    timestamp as time,\n    response_total_bytes*8/${seconds} AS Throughput,\n    hdx_cdn AS CDN\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n  AND $__adHocFilter()\nGROUP BY \n    time, CDN \nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Akamai Current Traffic; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "4xx-5xx Response Status Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n    timestamp as time,\n    countMergeIf(`count()`,response_status_code >= '400' AND response_status_code < '500') AS \"4xx\", \n    countMergeIf(`count()`,response_status_code >= '500' AND response_status_code < '600') AS \"5xx\",\n    hdx_cdn\nFROM ${table}\nWHERE $__timeFilter(timestamp)\n    AND $__adHocFilter()\nGROUP BY time, hdx_cdn\nORDER BY time, hdx_cdn\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=5xx Response Status Count (US Only); du=${__user.login}'"
    }
   ]
  },
  { "title": "General panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "2xx Response Status Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \n    timestamp as time,\n    hdx_cdn as CDN,\n    countMergeIf(`count()`,response_status_code >= '200'AND response_status_code < '300') AS Total\nFROM \n    ${table}\nWHERE $__timeFilter(timestamp)\n    AND $__adHocFilter()\nGROUP BY \n    time, CDN\nORDER BY \n    time\n    \nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=2xx Response Status Count (US Only); du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Traffic percentage (bytes) per CDN",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    hdx_cdn,\n    response_total_bytes as total_bytes,\n    round(response_total_bytes * 100.0 / sum(response_total_bytes) OVER(), 2) as percentage\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n    AND $__adHocFilter()\nGROUP BY hdx_cdn\nORDER BY percentage DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; asd; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Traffic percentage (bytes) per user agent category",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    user_agent_category,\n    response_total_bytes as total_bytes,\n    round(response_total_bytes * 100.0 / sum(response_total_bytes) OVER(), 2) as percentage\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n    AND $__adHocFilter()\nGROUP BY user_agent_category\nORDER BY percentage DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; asd; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "4xx Response Status Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \n    timestamp as time,\n    hdx_cdn as CDN,\n    countMergeIf(`count()`,response_status_code > '399' AND response_status_code < '500') AS Total\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n    AND $__adHocFilter()\nGROUP BY \n    time, CDN\nORDER BY \n    time\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=4xx Response Status Count (US Only); du=${__user.login}'"
    }
   ]
  },
  {
   "title": "5xx Response Status Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \n    timestamp as time,\n    hdx_cdn as CDN,\n    countMergeIf(`count()`,response_status_code > '499' AND response_status_code < '600') AS Total\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n    AND $__adHocFilter()\nGROUP BY \n    time, CDN\nORDER BY \n    time\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=5xx Response Status Count (US Only); du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Median TTFB by CDN",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n    timestamp AS time,\n    quantiles_response_ttfb_ms[2] AS TTFB,\n    hdx_cdn AS CDN\nFROM\n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n    AND $__adHocFilter()\nGROUP BY\n    time, hdx_cdn\nORDER BY\n    time asc\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Manifest Latency by CDN (p95/p99); du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 100 Global Requests by Country - All CDNs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n    request_host AS Host,\n    client_country_iso_code AS Country,\n    SUM(Total) AS Total\nFROM (\n    SELECT \n        request_host,\n        client_country_iso_code,\n        cnt_all AS Total,\n        hdx_cdn as CDN\n    FROM ${table}\n    WHERE $__timeFilter(timestamp)\n      AND notEmpty(request_host)\n      AND $__adHocFilter()\n    GROUP BY hdx_cdn, request_host, client_country_iso_code\n)\nGROUP BY Host, Country\nORDER BY Total DESC\nLIMIT 100\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Global Requests by Country - All CDNs; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 100 Edge Pop by 2xx-5xx",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n    edge_pop AS POP,\n    countMergeIf(`count()`,response_status_code >= '200'AND response_status_code < '300') AS \"2xx\",\n    countMergeIf(`count()`,response_status_code >= '300'AND response_status_code < '400') AS \"3xx\",\n    countMergeIf(`count()`,response_status_code >= '400'AND response_status_code < '500') AS \"4xx\",\n    countMergeIf(`count()`,response_status_code >= '500'AND response_status_code < '600') AS \"5xx\",\n    cnt_all AS Total\nFROM ${table}\nWHERE $__timeFilter(timestamp)\n  AND $__adHocFilter()\nGROUP BY \n    edge_pop\nORDER BY \n    edge_pop\nLIMIT 100\n\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Global Requests by Country - All CDNs; du=${__user.login}'"
    }
   ]
  }
 ]
}