{
 "title": "Bot Insights (SIEM)",
 "tags": [
  "SUMMARY",
  "v1.0",
  "Limited Availability"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "SELECT  CASE\nWHEN ${duration} <= 24 THEN '${siem_summary_hour}'\nWHEN ${duration} > 24 AND ${duration} <= 744 THEN '${siem_summary_day}'\nWHEN ${duration} > 744 THEN '${siem_summary_month}'\nEND"
   },
   { "name": "filter", "label": "Filter" },
   {
    "name": "duration",
    "query": "SELECT datediff('h', $__fromTime, $__toTime)"
   },
   { "name": "siem_raw", "query": "${VAR_SIEM_RAW}" },
   { "name": "siem_summary_hour", "query": "${VAR_SIEM_SUMMARY_HOUR}" },
   { "name": "siem_summary_day", "query": "${VAR_SIEM_SUMMARY_DAY}" },
   { "name": "siem_summary_month", "query": "${VAR_SIEM_SUMMARY_MONTH}" },
   {
    "name": "interval",
    "query": " SELECT CASE \nWHEN ${duration} < 6 THEN 'INTERVAL 1 MINUTE'\nWHEN ${duration} >= 6 AND ${duration} < 72 THEN 'INTERVAL 1 HOUR' \nELSE 'INTERVAL 1 DAY'\nEND"
   },
   {
    "name": "cnt_all_var",
    "query": "SELECT IF('${table}' = '${siem_raw}', 'count(*)', 'cnt_all')"
   },
   {
    "name": "time",
    "query": "SELECT  CASE\nWHEN ${duration} <= 24 THEN 'timestamp < toDateTime($__to/1000) AND timestamp > toDateTime($__to/1000) - INTERVAL 24 HOUR'\nWHEN ${duration} > 24 THEN '$__timeFilter(timestamp)'\nEND"
   }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "## Bot Visibility\n\n**Provides visibility into how bots are interacting with your websites.**\n\nUnderstand high-level trends in bot traffic and which AI bots are requesting resources from your site."
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Comparing Request Volumes",
   "type": "stat",
   "description": "Understand how much of total request volume is originating from all bots as well as AI bots specifically",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    ${cnt_all_var} as \"Total Requests\",\n    countMergeIf(`count()`, notEmpty(bot_type) = 1) AS \"Total Bot Requests\",\n    countMergeIf(`count()`, notEmpty(bot_type) = 1 AND bot_category = 'Artificial Intelligence (AI) Bots') AS \"AI Bot Requests\"\nFROM \n    ${table}\nWHERE ${time}\n    AND $__adHocFilter()\n    \nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Traffic breakdown; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Bot Request Volume by Category ",
   "type": "piechart",
   "description": "Understand the volume of requests from bots, broken down by category",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    bot_category,\n    ${cnt_all_var}\nFROM \n    ${table}\nWHERE ${time}\n    AND $__adHocFilter()\n    AND notEmpty(bot_type) = 1\nGROUP BY bot_category\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Bot traffic percentage per category; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Bot Request Volume by Category Over Time",
   "type": "timeseries",
   "description": "Understand the volume of requests from bots, broken down by category over time",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfInterval(toDateTime(timestamp), toIntervalSecond($__interval_ms / 1000)) AS time,\n    ${cnt_all_var} AS \"All Bot Requests\",\n    bot_category\nFROM ${table}\nWHERE ${time}\n    AND $__adHocFilter()\n    AND notEmpty(bot_type) = 1\nGROUP BY time, bot_category\nORDER BY time ASC, bot_category\nLIMIT 50000\nSETTINGS hdx_query_max_execution_time=60,\n    hdx_query_admin_comment='db=${__dashboard}; dp=Bot Request Volume by Category Over Time; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "AI Bot Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "AI Bot Request Volume by Category Over Time",
     "type": "timeseries",
     "description": "Understand AI bot request volume by major vendors over time",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    toStartOfInterval(toDateTime(timestamp), toIntervalSecond($__interval_ms / 1000)) AS time,\n    ${cnt_all_var},\n    bot_category\nFROM ${table}\nWHERE ${time}\n    AND $__adHocFilter()\n    AND notEmpty(bot_type) = 1\n    AND bot_category = 'Artificial Intelligence (AI) Bots'\nGROUP BY time, bot_category\nORDER BY time ASC\nSETTINGS hdx_query_max_execution_time=60,\n    hdx_query_admin_comment='db=${__dashboard}; dp=AI traffic by bot; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "AI Bots: Requested Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bot Request Volume by Target File & Vendor",
     "type": "table",
     "description": "Understand the files bots are requesting",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "targets": [
      {
       "rawSql": "SELECT \n    bot_category as \"Bot Category\",\n    resource_category as \"Resource category\",\n    ${cnt_all_var} as \"Count\"\nFROM \n    ${table}\nWHERE ${time}\n    AND $__adHocFilter()\n    AND notEmpty(bot_type) = 1\n    AND bot_category = 'Artificial Intelligence (AI) Bots'\nGROUP BY \n    bot_category, resource_category\nORDER BY\n    ${cnt_all_var} DESC\n  \nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Resource request by bot; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Bot Request Volume by Target File & Vendor Over Time",
     "type": "timeseries",
     "description": "Understand the files bots are requesting and how they're changing over time",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT \n    toStartOfInterval(toDateTime(timestamp), toIntervalSecond($__interval_ms / 1000)) AS time,\n    bot_category,\n    resource_category,\n    count() as count\nFROM \n    ${table}\nWHERE $__timeFilter(timestamp)\n    AND $__adHocFilter()\n    AND notEmpty(bot_type) = 1\n    AND bot_category = 'Artificial Intelligence (AI) Bots'\nGROUP BY \n    time, bot_category, resource_category\nORDER BY\n    time ASC, count DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Timeseries Resoruce request by bot ; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Additional Bot Insights from Web Security Analytics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Line: Attack Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "WITH cte AS (\n  SELECT  \n    timestamp,\n    attackTypes\n  FROM ${table}\n  WHERE $__timeFilter(timestamp)\n    AND $__adHocFilter() \n)\nSELECT  \n  toStartOfInterval(toDateTime(timestamp), ${interval}) AS time,  \n  attackTypes, \n  count(*) as \"Request Count\"\nFROM cte\nARRAY JOIN attackTypes\nGROUP BY attackTypes, time  \nORDER BY count(*) desc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Time Line: Attack Type; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Bot Category",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  toStartOfInterval(toDateTime(timestamp), toIntervalSecond($__interval_ms / 1000)) AS time,\n  bot_category,\n  bot_type,\n  count(*) AS request_count\nFROM ${table}\nWHERE $__timeFilter(timestamp)\n    AND notEmpty(bot_type)\n    AND $__adHocFilter()\nGROUP BY time, bot_category, bot_type\nORDER BY time ASC\nSETTINGS hdx_query_max_execution_time=60,\n    hdx_query_admin_comment='db=${__dashboard}; dp=Bot Category; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Bot Type",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  toStartOfInterval(toDateTime(timestamp), toIntervalSecond($__interval_ms / 1000)) AS time,\n  bot_type,\n  count(*) AS \"Count Requests Bot Type\"\nFROM ${table}\nWHERE $__timeFilter(timestamp)\n    AND notEmpty(bot_type)\n    AND $__adHocFilter()\nGROUP BY time, bot_type\nORDER BY time ASC\nSETTINGS hdx_query_max_execution_time=60,\n    hdx_query_admin_comment='db=${__dashboard}; dp=Bot Type; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Bot Score",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT  \n    botScoreRange, timestamp,${cnt_all_var}  \n  FROM ${table}\n  WHERE $__timeFilter(timestamp)\n    AND notEmpty(botScoreRange)\n    AND $__adHocFilter() \nGROUP BY botScoreRange, timestamp\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Bot Score; du=${__user.login}'"
      }
     ]
    }
   ]
  }
 ]
}