SELECT
  toStartOfHour (timestamp) as timestamp,
  method,
  status,
  country,
  IF(
    cityHash64 (clientIP, timestamp, requestId) % 100 < 10,
    clientIP,
    '~~~SAMPLED_OUT~~~'
  ) as clientIP,
  IF(
    cityHash64 (host, timestamp, requestId) % 100 < 10,
    host,
    '~~~SAMPLED_OUT~~~'
  ) as host,
  IF(
    cityHash64 (path, timestamp, requestId) % 100 < 10,
    path,
    '~~~SAMPLED_OUT~~~'
  ) as path,
  ruleMessages,
  ruleTags,
  ruleActions,
  attackTypes,
  ruleTagsWAF,
  attack_waf,
  ruleTagsDOS,
  attack_dos,
  ruleTagsBot,
  attack_bot,
  rules,
  asn,
  CH_UA,
  has_CH_UA,
  UA,
  attack_reputation,
  ruleMessage,
  protocol,
  requestId,
  ruleSelectors,
  ruleData,
  count() as request_count
FROM
  __PROJECT_NAME__.__TABLE_NAME__
GROUP BY
  timestamp,
  method,
  status,
  country,
  clientIP,
  host,
  path,
  ruleMessages,
  ruleTags,
  ruleActions,
  attackTypes,
  ruleTagsWAF,
  attack_waf,
  ruleTagsDOS,
  attack_dos,
  ruleTagsBot,
  attack_bot,
  rules,
  asn,
  CH_UA,
  has_CH_UA,
  UA,
  attack_reputation,
  ruleMessage,
  protocol,
  requestId,
  ruleSelectors,
  ruleData SETTINGS hdx_primary_key = 'timestamp'
