folders:
  hdx-main-folder:
    name: TrafficPeak Certified Reference Dashboards
    children: {}
dashboards:
  hdx-bot-insights-cdn-1770227511016:
    dashboard:
      __extend__: dashboards/Bot Insights (CDN)-1770227511016.json
    folderUid: hdx-main-folder
