SELECT
    decodeURLComponent(requestHeadersStr) AS requestHeadersStr,
    decodeURLComponent(responseHeadersStr) AS responseHeadersStr,
    akamai_siem_extract(rulesStr) AS rules,
    akamai_siem_extract(ruleTagsStr) AS ruleTags,
    arrayResize(akamai_siem_extract(ruleDataStr), length(ruleTags), '') AS ruleData,
    akamai_siem_extract(ruleActionsStr) AS ruleActions,
    akamai_siem_extract(ruleMessagesStr) AS ruleMessages,
    akamai_siem_extract(ruleVersionsStr) AS ruleVersions,
    arrayResize(akamai_siem_extract(ruleSelectorsStr), length(ruleTags), '') AS ruleSelectors,
    akamai_extract_key_pair(requestHeadersStr,'
', ':') AS requestHeaders,
    akamai_extract_key_pair(responseHeadersStr,'
', ':') AS responseHeaders,
    arrayExists(x -> multiSearchAny(x, ['AKAMAI/BOT/','BOT/','CUSTOM/BOT/','MBS_CL', 'AKAMAI/BOT/CUST_DEFINED_BOTS']), ruleTags) AS attack_bot,
    arrayExists(x -> multiSearchAny(x, ['ASE/','AKAMAI/POLICY/','OWASP_CRS/','AKAMAI/WAF','AKAMAI/WEB_ATTACK/']), ruleTags) AS attack_waf,
    arrayExists(x -> x = 'REPUTATION', ruleTags) AS attack_reputation,
    arrayExists(x -> startsWith(x, '6'), rules) AS attack_custom,
    arrayExists(x -> multiSearchAny(x, ['USER-RISK']), rules) AS attack_risk,
    arrayExists(x -> x = 'IPBLOCK', ruleTags) AS attack_firewall,
    arrayExists(x -> positionCaseInsensitive(x, 'BLOCK/') > 0, ruleTags) AS attack_dos,
    arrayFilter((x, y) -> y = 1, ['Bot','WAF', 'Reputation','Custom','DoS', 'User Risk', 'Network Firewall'], [attack_bot, attack_waf,attack_reputation,attack_custom,attack_dos, attack_risk, attack_firewall]) AS attackTypes,
    multiIf(
 arrayExists(x -> startsWith(x, 'Web Scrapers'), ruleMessages), 'Web Scrapers', 
 arrayExists(x -> startsWith(x, 'Scanning Tools'), ruleMessages), 'Scanning Tools', 
 arrayExists(x -> startsWith(x, 'Web Attackers'), ruleMessages), 'Web Attackers', 
 arrayExists(x -> startsWith(x, 'DOS Attacker'), ruleMessages), 'DOS Attacker', 
Null) AS ruleMessage,
    arrayDistinct(arrayFilter(x -> multiSearchAny(x, ['AKAMAI/BOT/','BOT/','CUSTOM/BOT/','MBS_CL',':']), ruleTags)) AS ruleTagsBot,
    arrayDistinct(arrayFilter(x -> multiSearchAny(x, ['ASE/','AKAMAI/POLICY/','OWASP_CRS/','AKAMAI/WAF','AKAMAI/WEB_ATTACK/',':']), ruleTags)) AS ruleTagsWAF,
    arrayDistinct(arrayFilter(x -> multiSearchAny(x, ['IPBLOCK',':']), ruleTags)) AS ruleTagsDOS,
    requestHeaders['Sec-CH-UA'] AS CH_UA,
    requestHeaders['User-Agent'] AS UA,
    notEmpty(CH_UA) AS has_CH_UA,
    datediff('s', timestamp, now64(3)) AS hdx_source_latency,
    regexpExtract(requestHeadersStr, 'Referer:\\s*(\\S+)', 1) AS referer,
    multiIf(
 arrayExists(x -> multiSearchAny(x, ['AKAMAI_CATEGORIZED']), ruleTags), 'Akamai',
 arrayExists(x -> multiSearchAny(x, ['CUST_DEFINED_BOTS']), ruleTags), 'Customer',
 'Unknown') AS botType,
botType as bot_type,
    multiIf(
 botData_responseSegment = 0, 'Human', 
 botData_responseSegment > 0, 'Bot', 
 'empty') AS responseSegment,
    multiIf(
 botData_responseSegment = 0, 'Human',
 botData_responseSegment = 1, 'Cautious response', botData_responseSegment = 2, 'Strict response', 
 botData_responseSegment = 3, 'Aggressive response', botData_responseSegment = 4, 'Safeguard',
 'empty') AS responseSegmentDetails,
    multiIf(
 clientData_telemetryType = 0, 'Web client (standard telemetry)',
 clientData_telemetryType = 1, 'Web client (inline telemetry)',
 clientData_telemetryType = 2, 'Native app (SDK)',
 'empty') AS telemetryType,
    multiIf( indexOf(ruleTags, 'AKAMAI/BOT/AKAMAI_CATEGORIZED') > 0, indexOf(ruleTags, 'AKAMAI/BOT/AKAMAI_CATEGORIZED'),
      indexOf(ruleTags, 'AKAMAI/BOT/CUST_DEFINED_BOTS') > 0, indexOf(ruleTags, 'AKAMAI/BOT/CUST_DEFINED_BOTS'),
      indexOf(ruleTags, 'AKAMAI/BOT/UNKNOWN_BOT') > 0, indexOf(ruleTags, 'AKAMAI/BOT/UNKNOWN_BOT'), 0
 ) AS indexOfValues,
    ruleData[indexOfValues] AS botnetId,
    botnetId AS botnet_id,
    ruleMessages[indexOfValues] AS botCategory,
    botCategory AS bot_category,
    *,
    multiIf(arrayExists(x -> positionCaseInsensitive(x, 'deny') > 0 OR positionCaseInsensitive(x, 'block') > 0, ruleActions), 'deny', arrayExists(x -> positionCaseInsensitive(x, 'tarpit') > 0 OR positionCaseInsensitive(x, 'challenge') > 0 OR positionCaseInsensitive(x, 'delay') > 0 OR positionCaseInsensitive(x, 'serve_alt') > 0, ruleActions), 'mitigate', arrayExists(x -> positionCaseInsensitive(x, 'monitor') > 0 OR positionCaseInsensitive(x, 'alert') > 0, ruleActions), 'monitor', arrayExists(x -> positionCaseInsensitive(x, 'allow') > 0, ruleActions), 'allow', '') AS actionClass,
    multiIf(arrayExists(x -> positionCaseInsensitive(x, 'Cookie authentication failed') > 0, ruleMessages), 'fail', '') AS authOutcome,
    lower(cutQueryString(coalesce(path, ''))) AS requestPathNorm,
    arrayStringConcat(arrayMap(segment -> multiIf(empty(segment), '', match(segment, '(?i)^[a-z0-9._-]+\\.(jpg|jpeg|png|gif|webp|avif|svg|css|js|mjs|map|woff|woff2|ttf|ico)([._-][a-z0-9]+)?$'), ':asset', match(segment, '^[0-9]+$'), ':num', match(segment, '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'), ':uuid', match(segment, '^[0-9a-f]{16,}$'), ':hex', match(segment, '^[a-z0-9][a-z0-9_-]{19,}$') AND match(segment, '[0-9]'), ':token', segment), splitByChar('/', requestPathNorm)), '/') AS requestPathPattern,
    dictGet('akamai_ua_cat_dict', 'ua_category', assumeNotNull(UA)) AS userAgentCategory,
    dictGet('akamai_ua_cat_dict', 'ai_category', assumeNotNull(UA)) AS aiCategory,
    dictGet('akamai_ua_cat_dict', 'is_bot', assumeNotNull(UA)) AS isBotTraffic,
    dictGet('akamai_ua_cat_dict', 'producer', assumeNotNull(UA)) AS botProducer,
    if(notEmpty(aiCategory), botProducer, '') AS aiSource,
    multiIf(positionCaseInsensitive(assumeNotNull(path), 'robots.txt') > 0, 'robots.txt', positionCaseInsensitive(assumeNotNull(path), 'sitemap.xml') > 0, 'sitemap.xml', positionCaseInsensitive(assumeNotNull(path), 'ads.txt') > 0, 'ads.txt', positionCaseInsensitive(assumeNotNull(path), 'llms.txt') > 0, 'llms.txt', match(assumeNotNull(path), '^/api/') OR match(assumeNotNull(path), '/api/'), 'api', match(assumeNotNull(path), '\\.(css|js|png|jpg|jpeg|gif|svg|ico|woff2?|ttf|eot)$'), 'static', match(assumeNotNull(path), '\\.(html?|php|asp|jsp)$') OR assumeNotNull(path) = '/' OR NOT match(assumeNotNull(path), '\\.'), 'page', 'other') AS resourceCategory
FROM
    {STREAM}
