{
 "title": "mPulse Core Web Vitals",
 "tags": [
  "core analysis",
  "v1.0",
  "add-on"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pageDomainName",
    "label": "Page Domain Name",
    "query": "SELECT pageDomainName FROM ${mpulse} WHERE $__timeFilter(timestamp) AND notEmpty(pageDomainName) GROUP BY pageDomainName ORDER BY count() DESC LIMIT 50"
   },
   {
    "name": "aggregation",
    "label": "Aggregation",
    "query": "P10 : quantile(0.10) , P25 : quantile(0.25) , Average : avg , Median : quantile(0.5) , P75 : quantile(0.75) , P90 : quantile(0.9) , P95 : quantile(0.95) , P99 : quantile(0.99)"
   },
   { "name": "mpulse", "query": "${VAR_MPULSE}" },
   { "name": "paramsU", "label": "URL" },
   { "name": "filter" },
   {
    "name": "groupBy",
    "label": "Group By",
    "query": "Page Group : pageGroupName , Device Type : deviceTypeName , Country : countryCode , URL : paramsU , Browser : userAgentName , Beacon Type : beaconTypeName ,  Hostname : pageDomainName , OS : operatingSystemName , Browser : userAgentName , Akamai Property Version : akamaiPropertyVersionName"
   },
   {
    "name": "beaconTypeName",
    "label": "Beacon Type",
    "query": "SELECT beaconTypeName FROM ${mpulse} WHERE $__timeFilter(timestamp) AND notEmpty(beaconTypeName) GROUP BY beaconTypeName ORDER BY count() DESC LIMIT 50"
   },
   { "name": "baseFilter", "query": "${VAR_BASEFILTER}" }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Understand how your pages perform based on Google's key usability metrics: LCP (Largest Contentful Paint), INP (Interaction to Next Paint), CLS (Cumulative layout Shift)."
   }
  },
  { "title": "Core Web Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "LCP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT ${aggregation}(largestContentfulPaint) as timer\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=LCP; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "% with LCP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT countIf(largestContentfulPaint>0)/count(*) as \"% LCP\"\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=% with LCP; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "INP",
   "type": "stat",
   "description": "Interaction to Next Paint. Good: <200ms , Poor: > 500ms",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT ${aggregation}(interactionToNextPaint) as timer\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=INP; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "% with INP",
   "type": "stat",
   "description": "Interaction to Next Paint. Good: <200ms , Poor: > 500ms",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT countIf(interactionToNextPaint>0)/count(*) as \"% with INP\"\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=% with INP; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "CLS",
   "type": "stat",
   "description": "Cumulative Layout Shift. Good: <.1 , Poor: > .25",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT ${aggregation}(cumulativeLayoutShift) as timer\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=CLS; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "% with CLS",
   "type": "stat",
   "description": "Cumulative Layout Shift. Good: <.1 , Poor: > .25",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT countIf(cumulativeLayoutShift>0)/count(*) as \"% with CLS\"\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=% with CLS; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "LCP",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT ${aggregation}(largestContentfulPaint) as timer,\n$__timeInterval(timestamp) as time\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\ngroup by time\norder by time asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=LCP by Time; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "INP",
   "type": "timeseries",
   "description": "Interaction to Next Paint. Good: <200ms , Poor: > 500ms",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT ${aggregation}(interactionToNextPaint) as timer,\n$__timeInterval(timestamp) as time\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\ngroup by time\norder by time asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=INP by Time; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "CLS",
   "type": "timeseries",
   "description": "Cumulative Layout Shift. Good: <.1 , Poor: > .25",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT ${aggregation}(cumulativeLayoutShift) as timer,\n$__timeInterval(timestamp) as time\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\ngroup by time\norder by time asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=CLS by Time; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "LCP Element",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT cwvLcpElement,\ncount(*) as count\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\ngroup by cwvLcpElement\norder by count desc\nLIMIT 1000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=LCP Element; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "INP Element",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT cwvInpElement,\ncount(*) as count\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\ngroup by cwvInpElement\norder by count desc\nLIMIT 1000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=INP Element; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "CLS Element",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT cwvClsElement,\ncount(*) as count\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\ngroup by cwvClsElement\norder by count desc\nLIMIT 1000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=CLS Element; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "CWV by ${groupBy}",
   "type": "table",
   "description": "Measured values for Core Web Vitals items, as well as what percent of beacons contained a non-zero value for that measurement.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \n  ${groupBy} as ${groupBy},\n  count(*) as count,\n  ${aggregation}(largestContentfulPaint) as LCP,\n  countIf(largestContentfulPaint>0)/count(*) as \"% LCP\",\n  ${aggregation}(interactionToNextPaint) as INP,\n  countIf(interactionToNextPaint>0)/count(*) as \"% INP\",\n  ${aggregation}(cumulativeLayoutShift) as CLS,\n  countIf(cumulativeLayoutShift>0)/count(*) as \"% CLS\",\n  ${aggregation}(pageLoadTime) as PageLoad\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\ngroup by ${groupBy}\norder by count desc\nLIMIT 1000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=CWV by ...; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "PageLoadTime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT ${aggregation}(pageLoadTime) as pageLoad,\ncount(*) as pageViews,\n$__timeInterval(timestamp) as time\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\ngroup by time\norder by time asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=PageLoadTime; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "OS",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT operatingSystemName,count(*) as count,${aggregation}(pageLoadTime) as pageLoad\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\ngroup by operatingSystemName\norder by count desc\nLIMIT 1000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=OS; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Page Views",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as pageViews,\n$__timeInterval(timestamp) as time\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\ngroup by time\norder by time asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Page Views; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT uniq(sessionId) as sessions\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\nLIMIT 1000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Sessions; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Session Length",
   "type": "stat",
   "description": "Avg # of pages viewed in a session.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with sessionTable as (\n  SELECT sessionId,max(sessionPages) as sessionPages\n  FROM ${mpulse}\n  where $__timeFilter(timestamp)\n  AND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\n  AND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n  ${filter}\n  ${baseFilter}\ngroup by sessionId\n  )\n\nselect avg(sessionPages) as avgSessionPages\nfrom sessionTable\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Session Length; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "Session Duration",
   "type": "stat",
   "description": "Avg (max(sessionLatest)-min(sessionStart))",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with sessionTable as (\n  SELECT sessionId,max(sessionLatest) - min(sessionStart) as sessionDuration\n  FROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n${baseFilter}\n\ngroup by sessionId\n  )\n\nselect avg(sessionDuration) as avgsessionDuration\nfrom sessionTable\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Session Duration; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "HELP and INFO",
     "type": "text",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
     "options": {
      "content": "To learn more about Core Web Vitals and mPulse see this blog: [Akamai Blog | Measuring and Improving Core Web Vitals](https://www.akamai.com/blog/performance/measuring-improving-core-web-vitals#:~:text=Akamai%20mPulse%20RUM,-mPulse%20RUM%20is&text=As%20of%20September%202020%2C%20mPulse,not%20match%20Google%20results%20exactly)  "
     }
    }
   ]
  }
 ]
}