{
 "title": "mPulse Page Weight by Group",
 "tags": [
  "core analysis",
  "v1.0",
  "add-on"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "mpulse", "query": "${VAR_MPULSE}" },
   {
    "name": "groupBy",
    "query": "Hostname : pageDomainName , Page Group : pageGroupName , URL : paramsU , Country : countryCode , Beacon Type : beaconTypeName"
   },
   { "name": "topN", "query": "${VAR_TOPN}" },
   {
    "name": "resourceType",
    "query": "Total : total , CSS : css , Font : font , HTML : html , Image : img , JavaScript : js , Other : other , Page : page , XHR : xhr"
   },
   {
    "name": "metric",
    "query": " Decoded Body Size : DecodedBodySize , Transfer Size : TransferSize"
   },
   {
    "name": "aggregation",
    "query": "Average : avg , Median : quantile(0.5) , P75 : quantile(0.75) , P90 : quantile(0.90) , P95 : quantile(0.95) , P99 : quantile(0.99)"
   },
   { "name": "maxTreemapCells", "query": "${VAR_MAXTREEMAPCELLS}" },
   {
    "name": "pageDomainName",
    "label": "Hostname",
    "query": "SELECT pageDomainName \nFROM ${mpulse} \nWHERE $__timeFilter(timestamp) AND notEmpty(pageDomainName) GROUP BY pageDomainName \nORDER BY count() DESC \nLIMIT 50"
   },
   {
    "name": "pageGroupName",
    "label": "Page Group Name",
    "query": "SELECT pageGroupName \nFROM ${mpulse} \nWHERE $__timeFilter(timestamp) AND notEmpty(pageGroupName) GROUP BY pageGroupName \nORDER BY count() DESC \nLIMIT 50"
   },
   {
    "name": "beaconTypeName",
    "label": "Beacon Type",
    "query": "SELECT beaconTypeName \nFROM ${mpulse} \nWHERE $__timeFilter(timestamp) AND notEmpty(beaconTypeName) GROUP BY beaconTypeName \nORDER BY count()\nDESC LIMIT 50"
   },
   {
    "name": "isp",
    "query": "SELECT isp \nFROM ${mpulse} \nWHERE $__timeFilter(timestamp) AND notEmpty(isp) \nGROUP BY isp \nORDER BY count() DESC \nLIMIT 50"
   },
   {
    "name": "countryCode",
    "label": "Country",
    "query": "SELECT countryCode \nFROM ${mpulse} \nWHERE $__timeFilter(timestamp) AND notEmpty(countryCode) \nGROUP BY countryCode \nORDER BY count() DESC \nLIMIT 50"
   },
   {
    "name": "regionCode",
    "label": "State",
    "query": "SELECT regionCode \nFROM ${mpulse} \nWHERE $__timeFilter(timestamp) AND notEmpty(regionCode) \nGROUP BY regionCode \nORDER BY count() DESC \nLIMIT 50"
   },
   {
    "name": "geoCity",
    "label": "City",
    "query": "SELECT geoCity \nFROM ${mpulse} \nWHERE $__timeFilter(timestamp) AND notEmpty(geoCity) \nGROUP BY geoCity \nORDER BY count() DESC \nLIMIT 50"
   },
   {
    "name": "deviceTypeName",
    "query": "SELECT deviceTypeName \nFROM ${mpulse} \nWHERE $__timeFilter(timestamp) AND notEmpty(deviceTypeName) GROUP BY deviceTypeName \nORDER BY count() DESC \nLIMIT 10"
   },
   { "name": "paramsULike", "label": "URL like" },
   { "name": "omniFilter", "label": "Omni Filter" },
   {
    "name": "paramsU",
    "label": "URL",
    "query": "SELECT paramsU \nFROM ${mpulse} \nWHERE $__timeFilter(timestamp) AND notEmpty(paramsU) \nGROUP BY paramsU \nORDER BY count() DESC \nLIMIT 50"
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Find 'overweight' pages by identifying the pages/URLs with highest Total weight or highest transfer size."
   }
  },
  {
   "title": "Timers Over Time (use 'GroupBy filter to pick grouping)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "Page Views per ${groupBy}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "WITH top10 AS (\n  SELECT ${groupBy}\n  FROM ${mpulse}\n  WHERE $__timeFilter(timestamp)\n  AND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n  ${omniFilter}\n  GROUP BY ${groupBy}\n  ORDER BY count(*) DESC\n  LIMIT ${topN}\n)\nSELECT ${groupBy} , \n  count(*) as \"-\", \n  $__timeInterval(timestamp) as time\nFROM ${mpulse}\nWHERE $__timeFilter(timestamp)\n  AND ${groupBy} IN (SELECT ${groupBy} FROM top10)\n  AND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n  ${omniFilter}\nGROUP BY 3, 1\nORDER BY 3\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Page Views per ${groupBy}; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Timer Treemaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "${metric} by Hostname( ${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT \n  coalesce(pageDomainName,'(None)') as item, \n  count(*) as count,\n  ${aggregation}(${resourceType}${metric}) as metric\nFROM ${mpulse}\nWHERE $__timeFilter(timestamp)\n  AND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n  ${omniFilter}\nGROUP BY 1\nORDER BY 2 DESC \nLIMIT ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=${metric} by Hostname( ${aggregation}) ; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "${metric} by Page Group( ${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT \n  coalesce(pageGroupName,'(None)') as item, \n  count(*) as count,\n  ${aggregation}(${resourceType}${metric}) as metric\nFROM ${mpulse}\nWHERE $__timeFilter(timestamp)\n  AND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n  ${omniFilter}\nGROUP BY 1\nORDER BY 2 DESC \nLIMIT ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=${metric} by Page Group( ${aggregation}) ; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "${metric} by URL (${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT \n  replaceOne(coalesce(paramsU,'(None)'),'undefined','undefine_d') as item, \n  count(*) as count,\n  ${aggregation}(${resourceType}${metric}) as metric\nFROM ${mpulse}\nWHERE $__timeFilter(timestamp)\n  AND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n  ${omniFilter}\nGROUP BY 1\nORDER BY 2 DESC \nLIMIT ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=${metric} by URL (${aggregation}) ; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "${metric} by Device Type (${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 34 },
     "targets": [
      {
       "rawSql": "SELECT \n  coalesce(deviceTypeName,'(None)') as item, \n  count(*) as count,\n  ${aggregation}(${resourceType}${metric}) as metric\nFROM ${mpulse}\nWHERE $__timeFilter(timestamp)\n  AND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n  ${omniFilter}\nGROUP BY 1\nORDER BY 2 DESC \nLIMIT ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=${metric} by Device Type (${aggregation}) ; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "${metric} by Beacon Type (${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 34 },
     "targets": [
      {
       "rawSql": "SELECT \n  coalesce(beaconTypeName,'(None)') as item, \n  count(*) as count,\n  ${aggregation}(${resourceType}${metric}) as metric\nFROM ${mpulse}\nWHERE $__timeFilter(timestamp)\n  AND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n  ${omniFilter}\nGROUP BY 1\nORDER BY 2 DESC \nLIMIT ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=${metric} by Beacon Type (${aggregation}) ; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "${metric} by ISP (${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 34 },
     "targets": [
      {
       "rawSql": "SELECT \n  coalesce(isp,'(None)') as item, \n  count(*) as count,\n  ${aggregation}(${resourceType}${metric}) as metric\nFROM ${mpulse}\nWHERE $__timeFilter(timestamp)\n  AND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n  ${omniFilter}\nGROUP BY 1\nORDER BY 2 DESC \nLIMIT ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=${metric} by ISP (${aggregation}) ; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "${metric} by Country (${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 45 },
     "targets": [
      {
       "rawSql": "SELECT \n  coalesce(countryCode,'(None)') as item, \n  count(*) as count,\n  ${aggregation}(${resourceType}${metric}) as metric\nFROM ${mpulse}\nWHERE $__timeFilter(timestamp)\n  AND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n  ${omniFilter}\nGROUP BY 1\nORDER BY 2 DESC \nLIMIT ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=${metric} by Country (${aggregation}) ; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "${metric} by State (${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 45 },
     "targets": [
      {
       "rawSql": "SELECT \n  coalesce(regionCode,'(None)') as item, \n  count(*) as count,\n  ${aggregation}(${resourceType}${metric}) as metric\nFROM ${mpulse}\nWHERE $__timeFilter(timestamp)\n  AND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n  ${omniFilter}\nGROUP BY 1\nORDER BY 2 DESC \nLIMIT ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=${metric} by State (${aggregation}) ; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "${metric} by City (${aggregation}) ",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 45 },
     "targets": [
      {
       "rawSql": "SELECT \n  coalesce(geoCity,'(None)') as item, \n  count(*) as count,\n  ${aggregation}(${resourceType}${metric}) as metric\nFROM ${mpulse}\nWHERE $__timeFilter(timestamp)\n  AND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n  ${omniFilter}\nGROUP BY 1\nORDER BY 2 DESC \nLIMIT ${maxTreemapCells}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=${metric} by City (${aggregation}) ; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Raw Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Logs",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT concat(toString(timestamp), ' - ', beaconTypeName,' - ', pageGroupName) , * \nFROM  ${mpulse}\nWHERE $__timeFilter(timestamp)\n  AND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}) , ${pageDomainName} )\n  AND $__conditionalAll(pageGroupName in (${pageGroupName:sqlstring}),${pageGroupName} )\n  AND $__conditionalAll(deviceTypeName in (${deviceTypeName:sqlstring}),${deviceTypeName} )\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName} )\n  AND $__conditionalAll(isp in (${isp:sqlstring}),${isp} )\n  AND $__conditionalAll(countryCode in (${countryCode:sqlstring}),${countryCode} )\n  AND $__conditionalAll(regionCode in (${regionCode:sqlstring}),${regionCode} )\n  AND $__conditionalAll(geoCity in (${geoCity:sqlstring}),${geoCity} )\n  AND $__conditionalAll(paramsU in (${paramsU:sqlstring}),${paramsU} )\n  and if (empty('${paramsULike}'),true, paramsU like '${paramsULike}')\n  ${omniFilter}\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Raw Logs; du=${__user.login}'"
      }
     ]
    }
   ]
  }
 ]
}