{
 "title": "mPulse DevOps",
 "tags": [
  "core analysis",
  "v1.0",
  "add-on"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pageDomainName",
    "label": "Page Domain Name",
    "query": "SELECT pageDomainName FROM ${mpulse} WHERE $__timeFilter(timestamp) AND notEmpty(pageDomainName) GROUP BY pageDomainName ORDER BY count() DESC LIMIT 50"
   },
   {
    "name": "aggregation",
    "label": "Aggregation",
    "query": "P10 : quantile(0.10) , P25 : quantile(0.25) , Average : avg , Median : quantile(0.5) , P75 : quantile(0.75) , P90 : quantile(0.9) , P95 : quantile(0.95) , P99 : quantile(0.99)"
   },
   { "name": "mpulse", "query": "${VAR_MPULSE}" },
   { "name": "paramsU", "label": "URL" },
   { "name": "filter" },
   {
    "name": "beaconTypeName",
    "query": "SELECT beaconTypeName FROM ${mpulse} WHERE $__timeFilter(timestamp) AND notEmpty(beaconTypeName) GROUP BY beaconTypeName ORDER BY count() DESC LIMIT 50"
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Provides an overview of site volume and performance and session metrics (session length, session duration, bounce rate)"
   }
  },
  {
   "title": "Back-End Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ${aggregation}(firstByteTimer) as timer,\n$__timeInterval(timestamp) as time\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\ngroup by time\norder by time asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Back-End Time; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Front-End Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT ${aggregation}(firstLastByteTimer) as timer,\n$__timeInterval(timestamp) as time\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\ngroup by time\norder by time asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Front-End Time; du=${__user.login}'\n\n"
    }
   ]
  },
  {
   "title": "Page Load Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT ${aggregation}(pageLoadTime) as timer,\n$__timeInterval(timestamp) as time\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\ngroup by time\norder by time asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Page Load Time; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "PageLoadTime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT ${aggregation}(pageLoadTime) as pageLoad,\ncount(*) as pageViews,\n$__timeInterval(timestamp) as time\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\ngroup by time\norder by time asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=PageLoadTime by Time; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "Page Views",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as pageViews,\n$__timeInterval(timestamp) as time\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\ngroup by time\norder by time asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Page Views; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct(sessionId)) as sessions\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\nLIMIT 1000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Sessions; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "DNS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT ${aggregation}(dnsTimer) as timer,\n$__timeInterval(timestamp) as time\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\ngroup by time\norder by time asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=DNS; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "TCP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT ${aggregation}(tcpTimer) as timer,\n$__timeInterval(timestamp) as time\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\ngroup by time \norder by time asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=TCP; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "TLS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT ${aggregation}(sslTimer) as timer,\n$__timeInterval(timestamp) as time\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\ngroup by time\norder by time asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=TLS; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Session Length",
   "type": "stat",
   "description": "Avg # of pages viewed in a session.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with sessionTable as (\n  SELECT sessionId,max(sessionPages) as sessionPages\n  FROM ${mpulse}\n  where $__timeFilter(timestamp)\n  AND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\n  AND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\n  AND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n  group by sessionId\n  )\n\nselect avg(sessionPages) as avgSessionPages\nfrom sessionTable\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Session Length; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "Session Duration",
   "type": "stat",
   "description": "Avg (max(sessionLatest)-min(sessionStart))",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with sessionTable as (\n  SELECT sessionId,max(sessionLatest) - min(sessionStart) as sessionDuration\n  FROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\n  group by sessionId\n  )\n\nselect avg(sessionDuration) as avgsessionDuration\nfrom sessionTable\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Session Duration; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Country",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT countryCode,count(*) as count,${aggregation}(pageLoadTime) as pageLoad\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\ngroup by countryCode\norder by count desc\nLIMIT 1000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Country; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "PageLoadTime",
   "type": "geomap",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT ${aggregation}(pageLoadTime) as pageLoad,\ncount(*) as count,\nregionCode\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\ngroup by regionCode\norder by count(*) desc\nLIMIT 60\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=PageLoadTime Map; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "OS",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT operatingSystemName,count(*) as count,${aggregation}(pageLoadTime) as pageLoad\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\ngroup by operatingSystemName\norder by count desc\nLIMIT 1000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=OS; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Page Groups",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT pageGroupName,count(*) as count,${aggregation}(pageLoadTime) as pageLoad\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\ngroup by pageGroupName\norder by count desc\nLIMIT 1000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Page Groups; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Device Type",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT deviceTypeName,count(*) as count,${aggregation}(pageLoadTime) as pageLoad\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\ngroup by deviceTypeName\norder by count desc\nLIMIT 1000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Device Type; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Browser",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT userAgentName,count(*) as count,${aggregation}(pageLoadTime) as pageLoad\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\ngroup by userAgentName\norder by count desc\nLIMIT 1000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Browser; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top URLs (paramsU)",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT paramsU as url ,count(*) as count,${aggregation}(pageLoadTime) as pageLoad\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\ngroup by url\norder by count desc\nLIMIT 1000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top URLs (paramsU); du=${__user.login}'"
    }
   ]
  },
  {
   "title": "AppID",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT appId ,count(*) as count,${aggregation}(pageLoadTime) as pageLoad\nFROM ${mpulse}\nwhere $__timeFilter(timestamp)\nAND if (empty ('${paramsU}'),true,paramsU like '${paramsU}')\nAND $__conditionalAll(beaconTypeName in (${beaconTypeName:sqlstring}),${beaconTypeName})\nAND $__conditionalAll(pageDomainName in (${pageDomainName:sqlstring}),${pageDomainName})\n${filter}\ngroup by appId\norder by count desc\nLIMIT 1000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=AppID; du=${__user.login}'"
    }
   ]
  }
 ]
}