folders:
  hdx-main-folder:
    name: TrafficPeak Certified Reference Dashboards
    children: {}
dashboards:
  hdx-usage:
    dashboard:
      __extend__: dashboards/usage.json
    folderUid: hdx-main-folder
  hdx-home:
    dashboard:
      __extend__: dashboards/home.json
    folderUid: hdx-main-folder
  hdx-raw:
    dashboard:
      __extend__: dashboards/raw.json
    folderUid: hdx-main-folder
    inputs:
      DS_HYDROLIX-HYDROLIX-DATASOURCE: hdx-hydrolix-datasource
      VAR_DS2: akamai.logs
      VAR_TIMESTAMP: reqTimeSec
  hdx-cache:
    dashboard:
      __extend__: dashboards/cache.json
    folderUid: hdx-main-folder
  hdx-error:
    dashboard:
      __extend__: dashboards/error.json
    folderUid: hdx-main-folder
  hdx-cdn:
    dashboard:
      __extend__: dashboards/cdn.json
    folderUid: hdx-main-folder
  hdx-explore:
    dashboard:
      __extend__: dashboards/explore.json
    folderUid: hdx-main-folder
