{
 "title": "Cascade - WAF",
 "time": { "from": "now-1h", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "table", "query": "aws.waf" },
   {
    "name": "host",
    "label": "Host",
    "query": "SELECT http_headers['host'] as host FROM ${table} WHERE $__timeFilter(${timefilter})\nGROUP BY host\nLIMIT 100"
   },
   {
    "name": "timefilter",
    "query": " SELECT primary_key FROM system.tables WHERE database = splitByChar('.', '${table}')[1]\nAND table = splitByChar('.', '${table}')[2]"
   },
   {
    "name": "request_method",
    "label": "Request Method",
    "query": "SELECT arrayJoin(topK(10)(request_method))\nFROM ${table} WHERE $__timeFilter(${timefilter})"
   },
   {
    "name": "waf_action",
    "label": "Waf Action",
    "query": "SELECT arrayJoin(topK(10)(waf_action))\nFROM ${table} WHERE $__timeFilter(${timefilter})"
   },
   {
    "name": "client_country_iso_code",
    "label": "Country",
    "query": "SELECT arrayJoin(topK(10)(client_country_iso_code))\nFROM ${table} WHERE $__timeFilter(${timefilter})"
   },
   { "name": "request_path" },
   { "name": "client_ip", "label": "client_ip" },
   { "name": "waf_requestId" },
   { "name": "x_amz_cf_id" },
   { "name": "user_agent" }
  ]
 },
 "panels": [
  {
   "title": "Request count WAF",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT count(), $__timeInterval(${timefilter}) as time\nFROM ${table}\nWHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(http_headers['host'] IN (${host:sqlstring}),$host)\nAND $__conditionalAll(request_method IN (${request_method:sqlstring}),$request_method)\nAND $__conditionalAll(waf_action IN (${waf_action:sqlstring}),$waf_action)\nAND $__conditionalAll(request_path IN (${request_path:sqlstring}),$request_path)\nAND $__conditionalAll(client_country_iso_code IN (${client_country_iso_code:sqlstring}),$client_country_iso_code)\nAND $__conditionalAll(client_ip IN (${client_ip:sqlstring}),$client_ip)\nAND $__conditionalAll(waf_requestId IN (${waf_requestId:sqlstring}),$waf_requestId)\nAND $__conditionalAll(http_headers['x-amz-cf-id'] IN (${x_amz_cf_id:sqlstring}),$x_amz_cf_id)\nAND $__conditionalAll(http_headers['user-agent'] IN (${user_agent:sqlstring}),$user_agent)\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Count By WAF Action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT count(), waf_action, $__timeInterval(${timefilter}) as time\nFROM ${table}\nWHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(http_headers['host'] IN (${host:sqlstring}),$host)\nAND $__conditionalAll(request_method IN (${request_method:sqlstring}),$request_method)\nAND $__conditionalAll(waf_action IN (${waf_action:sqlstring}),$waf_action)\nAND $__conditionalAll(request_path IN (${request_path:sqlstring}),$request_path)\nAND $__conditionalAll(client_country_iso_code IN (${client_country_iso_code:sqlstring}),$client_country_iso_code)\nAND $__conditionalAll(client_ip IN (${client_ip:sqlstring}),$client_ip)\nAND $__conditionalAll(waf_requestId IN (${waf_requestId:sqlstring}),$waf_requestId)\nAND $__conditionalAll(http_headers['x-amz-cf-id'] IN (${x_amz_cf_id:sqlstring}),$x_amz_cf_id)\nAND $__conditionalAll(http_headers['user-agent'] IN (${user_agent:sqlstring}),$user_agent)\nGROUP BY waf_action, time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Request count per country",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(), client_country_iso_code\nFROM ${table}\nWHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(http_headers['host'] IN (${host:sqlstring}),$host)\nAND $__conditionalAll(request_method IN (${request_method:sqlstring}),$request_method)\nAND $__conditionalAll(waf_action IN (${waf_action:sqlstring}),$waf_action)\nAND $__conditionalAll(request_path IN (${request_path:sqlstring}),$request_path)\nAND $__conditionalAll(client_country_iso_code IN (${client_country_iso_code:sqlstring}),$client_country_iso_code)\nAND $__conditionalAll(client_ip IN (${client_ip:sqlstring}),$client_ip)\nAND $__conditionalAll(waf_requestId IN (${waf_requestId:sqlstring}),$waf_requestId)\nAND $__conditionalAll(http_headers['x-amz-cf-id'] IN (${x_amz_cf_id:sqlstring}),$x_amz_cf_id)\nAND $__conditionalAll(http_headers['user-agent'] IN (${user_agent:sqlstring}),$user_agent)\nGROUP BY client_country_iso_code"
    }
   ]
  },
  {
   "title": "Count By WAF Action",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(), waf_action\nFROM ${table}\nWHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(http_headers['host'] IN (${host:sqlstring}),$host)\nAND $__conditionalAll(request_method IN (${request_method:sqlstring}),$request_method)\nAND $__conditionalAll(waf_action IN (${waf_action:sqlstring}),$waf_action)\nAND $__conditionalAll(request_path IN (${request_path:sqlstring}),$request_path)\nAND $__conditionalAll(client_country_iso_code IN (${client_country_iso_code:sqlstring}),$client_country_iso_code)\nAND $__conditionalAll(client_ip IN (${client_ip:sqlstring}),$client_ip)\nAND $__conditionalAll(waf_requestId IN (${waf_requestId:sqlstring}),$waf_requestId)\nAND $__conditionalAll(http_headers['x-amz-cf-id'] IN (${x_amz_cf_id:sqlstring}),$x_amz_cf_id)\nAND $__conditionalAll(http_headers['user-agent'] IN (${user_agent:sqlstring}),$user_agent)\nGROUP BY waf_action"
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM ${table}\nWHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(http_headers['host'] IN (${host:sqlstring}),$host)\nAND $__conditionalAll(request_method IN (${request_method:sqlstring}),$request_method)\nAND $__conditionalAll(waf_action IN (${waf_action:sqlstring}),$waf_action)\nAND $__conditionalAll(request_path IN (${request_path:sqlstring}),$request_path)\nAND $__conditionalAll(client_country_iso_code IN (${client_country_iso_code:sqlstring}),$client_country_iso_code)\nAND $__conditionalAll(client_ip IN (${client_ip:sqlstring}),$client_ip)\nAND $__conditionalAll(waf_requestId IN (${waf_requestId:sqlstring}),$waf_requestId)\nAND $__conditionalAll(http_headers['x-amz-cf-id'] IN (${x_amz_cf_id:sqlstring}),$x_amz_cf_id)\nAND $__conditionalAll(http_headers['user-agent'] IN (${user_agent:sqlstring}),$user_agent)\nORDER BY ${timefilter} DESC\nLIMIT 100"
    }
   ]
  }
 ]
}