{
 "title": "DS2 Web Security",
 "description": "This dashboard requires web security and breadcrumbs enabled for Datastream 2 and the appropriate transform configuration to handle the new data.\n\nsplitByChar('|',assumeNotNull(securityRules))[1] as policy,\nsplitByChar('|',assumeNotNull(securityRules))[3] as denyRule,\nif(empty(splitByChar('|',assumeNotNull(securityRules))[3]),0,1) as denied,\nmultiIf(denyRule like '%REP%','Reputation', \n\tdenyRule like '3%' or denyRule like 'BOT-%', 'BOT',\n\tdenyRule like 'IP%', 'DOS',\n\tdenyRule like 'XSS%' or denyRule like 'WAT-%' or denyRule like 'RFI-ANOMALY%' or denyRule like 'PLATFORM-ANOMALY' or  denyRule like 'SQL%' or denyRule like 'LFI%' or denyRule like 'CMD-INJECTION%' or denyRule like 'PROTOCOL-ANOMALY%'  or denyRule like 'ADAPTIVE_UA_IP_BLOCK%' or denyRule like '6%', 'WAF Rule',\n\t''\n\t) as denyGroup",
 "tags": [
  "Security",
  "DS2",
  "v0.9"
 ],
 "time": { "from": "now-30m", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "edge_response_time_percentile", "label": "Edge Response Time Percentile", "query": "0.5 , 0.75 , 0.90 , 0.95, 0.99" },
   {
    "name": "transferTimeMSec_percentile",
    "query": "$__conditionalAll(SELECT quantile(${edge_response_time_percentile})(transferTimeMSec) FROM ${table} WHERE $__timeFilter(reqTimeSec),$edge_response_time_percentile)"
   },
   {
    "name": "table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   },
   {
    "name": "catalog",
    "query": "SELECT concat(project,'.`',table,'#.catalog`')\nFROM (SELECT splitByChar('.','${table}')[1] as project, splitByChar('.','${table}')[2] as table)"
   },
   { "name": "filter" },
   {
    "name": "raw_table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   }
  ]
 },
 "panels": [
  {
   "title": "Akamai / Hydrolix internal - Please read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "<div style=\"background-color: #990000; color: #CCCCCC; padding: 15px; padding-bottom: 0; border-radius: 5px 5px 0 0;\">\n      <h1 style=\"color: #CCCCCC; margin-top: 0;\">Akamai / Hydrolix Internal - Please read:</h1>\n  <br><p style=\"color: #CCCCCC;\">IF you export this <b>TrafficPeak Certified Reference <i>Security</i></b> dashboard please double check that the Ad Hoc Filter variable has a datasource.</p>\n  <br>\n</div>\n\n"
     }
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Traffic and Security Overview",
   "type": "timeseries",
   "description": "Counts of different parts of traffic, summed up by minute",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n$__timeInterval(reqTimeSec) as time,\nsum(denied) AS Denied,\ncountIf(denied = 0 and arrayFirstOrNull(x -> if(length(x)>0,1,0), assumeNotNull(rulesTriggered)) IS NOT NULL) AS Monitored,\ncountIf(notEmpty(Origin_IP)) AS Origin,\ncountIf(cacheStatus = 1) AS Edge,\ncount() AS Total\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__adHocFilter()\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\ngroup by time order by time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Traffic and Security Overview; du=${__user.login}'"
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Overall Traffic vs Denied",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(reqTimeSec) as time, \r\n  count(reqTimeSec) as Overall,\r\n  countIf(denied = 1) as Denied\r\nFROM ${table}\r\nWHERE $__timeFilter(reqTimeSec)\r\n  AND $__adHocFilter()\r\n  AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\r\nGROUP BY time ORDER BY time\r\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - totalTraffic vs Denied - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Deny Rule BreakDown",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT toString(denyRule) as denyRule, $__timeInterval(reqTimeSec) as time, count(denyRule) as count\r\nFROM ${table}\r\nWHERE $__timeFilter(reqTimeSec)\r\n  AND $__adHocFilter()\r\n  AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\r\n  AND denied = 1\r\nGROUP BY denyRule, time ORDER BY time\r\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Deny Rule BreakDown; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "% Total  Denied Traffic",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT countIf(denied = 1) / count() as \"Denied Traffic\", \r\n  $__timeInterval(toStartOfMinute(reqTimeSec)) as time\r\nFROM ${table}\r\nWHERE $__timeFilter(reqTimeSec)\r\n  AND $__adHocFilter()\r\n  AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\r\nGROUP BY time, time ORDER BY time\r\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=% Total  Denied Traffic; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Denied Traffic By Response Content Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(),\n  rspContentType\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\n  AND $__adHocFilter()\n  AND rspContentType IS not NULL\n  AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\n  AND denied = 1\nGROUP BY rspContentType \nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Denied Traffic By Response Content Type; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 50 IP Denied",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  tupleElement(tuple, 1) AS cliIP,\r\n  tupleElement(tuple, 2) as Count\r\nFROM (\r\n  SELECT arrayJoin(approx_top_k(50)(cliIP)) as tuple\r\n  FROM ${table}\r\n  WHERE $__timeFilter(reqTimeSec)\r\n    AND $__adHocFilter()\r\n    AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\r\n    AND denied = 1\r\n)\r\nORDER BY Count DESC\r\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 50 IP Denied; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Denied Group Counts",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT  denyGroup,\r\n\tcount()\r\nFROM ${table}\r\nWHERE $__timeFilter(reqTimeSec)\r\nAND $__adHocFilter()\r\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\r\nAND denied = 1\r\nAND notEmpty(denyGroup)\r\nGROUP BY denyGroup\r\nORDER BY count() Desc\r\nLimit 50\r\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Denied Group; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 50 Traffic Denied Rules",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  tupleElement(tuple, 1) AS denyRule,\r\n  tupleElement(tuple, 2) as Count\r\nFROM (\r\n  SELECT arrayJoin(approx_top_k(50)(denyRule)) as tuple\r\n  FROM ${table}\r\n  WHERE $__timeFilter(reqTimeSec)\r\n    AND $__adHocFilter()\r\n    AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\r\n    AND denied = 1\r\n) \r\nORDER BY Count Desc\r\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 50 Traffic Denied Rules; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 50 Denied By URL",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  tupleElement(tuple, 1) AS reqPath,\r\n  tupleElement(tuple, 2) AS Count\r\nFROM (\r\n  SELECT \r\n    arrayJoin(approx_top_k(50)(reqPath)) as tuple\r\n  FROM ${table}\r\n  WHERE $__timeFilter(reqTimeSec)\r\n    AND $__adHocFilter()\r\n    AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\r\n    AND denied = 1\r\n)\r\nORDER BY Count Desc\r\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 50 Denied By URL; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "General CDN Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hits per status code",
     "type": "timeseries",
     "description": "Number of requests - grouped by HTTP Status Code",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT \n  toString(statusCode) as HTTP_Status_Code, \n  $__timeInterval(reqTimeSec) as time, \n  count(*) as http\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\n  AND $__adHocFilter()\n  AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\nGROUP BY HTTP_Status_Code, time \nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Hits per status code; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "timeseries",
     "description": "Sum of all requests with cacheStatus of 1, divided by total count of requests",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeInterval(reqTimeSec) as time,\n  (sumIf(cacheStatus,1)/count()) * 100 as cache_hit \nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\n  AND $__adHocFilter()\n  AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\nGROUP BY time \nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Cache Hit Ratio; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "description": "Sum of all bytes delivered divided by the sum of transfer time",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeInterval(reqTimeSec) as time,\n  sum(totalBytes) / sum(transferTimeMSec/1000) as Throughput\nFROM ${table}\nWHERE \n  $__timeFilter(reqTimeSec)\n  AND $__adHocFilter()\n  AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Throughput; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Bytes Delivered",
     "type": "timeseries",
     "description": "Sum of Total Bytes Delivered",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "SELECT \n  $__timeInterval(reqTimeSec) as time,\n  sum(totalBytes) as Bytes_Delivered\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\n  AND $__adHocFilter()\n  AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\nGROUP BY time \nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Bytes Delivered; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top 50 Path",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    count() as Count,\n    reqPath\nFROM ${table}\nWHERE \n    $__timeFilter(reqTimeSec)\n    AND $__adHocFilter()\n    AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\nGROUP BY reqPath\nORDER BY Count DESC\nLIMIT 50\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 50 Path; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top 50 User Agent",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    tupleElement(tuple, 1) AS UA,\n    REPLACE(tupleElement(tuple, 1), ',', '__gfc__') AS escaped_UA,\n    tupleElement(tuple, 2) AS Count\nFROM (\n    SELECT arrayJoin(approx_top_k(50)(UA)) as tuple\n    FROM ${table}\n    WHERE $__timeFilter(reqTimeSec)\n        AND $__adHocFilter() \n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\n)\nORDER BY Count DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 50 User Agent; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Request Per Content Type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\ncount(),\nrspContentType\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\n  AND $__adHocFilter()\n  AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\n  AND rspContentType IS not NULL\nGROUP BY rspContentType ORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Request Per Content Type; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top 50 IP",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    tupleElement(tuple, 1) AS cliIP,\n    tupleElement(tuple, 2) AS Count\nFROM (\n    SELECT arrayJoin(approx_top_k(50)(cliIP)) AS tuple\n    FROM ${table}\n    WHERE \n        $__timeFilter(reqTimeSec)\n        AND $__adHocFilter()\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\n)\nORDER BY Count DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 50 IP; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Edge TransferTime",
     "type": "timeseries",
     "description": "The time in milliseconds from when the edge server is ready to send the first byte of the response to when the last byte reaches the kernel.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "SELECT $__timeInterval(reqTimeSec) as time,\n  quantile(0.25)(transferTimeMSec) as 25th,\n  quantile(0.5)(transferTimeMSec) as 50th,\n  quantile(0.75)(transferTimeMSec) as 75th,\n  quantile(0.9)(transferTimeMSec) as 90th,\n  quantile(0.95)(transferTimeMSec) as 95th,\n  quantile(0.99)(transferTimeMSec) as 99th\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\n  AND $__adHocFilter()\n  AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Edge TransferTime; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Edge Turn Around Time",
     "type": "timeseries",
     "description": "The time in milliseconds from when the edge server receives the last byte of the request to when it sends the first bytes of the response.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "SELECT $__timeInterval(reqTimeSec) as time,\n  quantile(0.25)(turnAroundTimeMSec) as 25th,\n  quantile(0.5)(turnAroundTimeMSec) as 50th,\n  quantile(0.75)(turnAroundTimeMSec) as 75th,\n  quantile(0.9)(turnAroundTimeMSec) as 90th,\n  quantile(0.95)(turnAroundTimeMSec) as 95th,\n  quantile(0.99)(turnAroundTimeMSec) as 99th\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\n  AND $__adHocFilter()\n  AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, ${transferTimeMSec_percentile})\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Edge Turn Around Time; du=${__user.login}'"
      }
     ]
    }
   ]
  }
 ]
}