SELECT datediff('s', timestamp, now64(3)) AS hdx_source_latency_sec,
__SHARED_PROJECT___breadcrumbs(breadcrumbs, '(\[[^[]*c=o[^]]*\])', 'k=([^,\]]+)') as origin_time_to_last_byte_ms,
__SHARED_PROJECT___breadcrumbs(breadcrumbs, '(\[[^[]*c=g[^]]*\])', 'n=([^,\]]+)') as edge_pop,
__SHARED_PROJECT___breadcrumbs(breadcrumbs, '(\[[^[]*c=o[^]]*\])', 'a=([^,\]]+)') AS origin_ip,
__SHARED_PROJECT___breadcrumbs(breadcrumbs, '(\[[^[]*c=o[^]]*\])', 'l=([^,\]]+)') AS origin_time_to_first_byte_ms,
__SHARED_PROJECT___breadcrumbs(breadcrumbs, '(\[[^[]*c=g[^]]*\])', 'a=([^,\]]+)') as edge_ip,
multiIf(
cacheStatus=1,1,
breadcrumbs IS NULL OR empty(breadcrumbs),0,
origin_ip IS NULL OR empty(origin_ip) OR origin_ip = '127.0.0.1',1,0
) AS cache_was_cached,
origin_ip IS NOT NULL AND notEmpty(origin_ip) AND origin_ip != '127.0.0.1' AS is_origin_request,
decodeURLComponent(assumeNotNull(queryStr)) AS request_query_string,
concat('/', assumeNotNull(request_path)) as request_path,
decodeURLComponent(assumeNotNull(referer)) AS request_referer,
decodeURLComponent(assumeNotNull(UA)) as user_agent,
dictGet('__SHARED_PROJECT___ua_cat_dict', 'ua_category', assumeNotNull(user_agent)) AS user_agent_category,
nullIf(extract(extractURLParameter(decodeURLComponent(assumeNotNull(queryStr)), 'CMCD'), 'sid="([^"]+)"'), '') AS sid,
multiIf(cacheStatus = 1, 'HIT', cacheStatus = 0, 'MISS', cacheStatus = 2, 'REDIRECT', cacheStatus = 3, 'ERROR', NULL) AS cache_outcome_category,
splitByChar('|',assumeNotNull(securityRules))[1] as akamai_security_policy,
splitByChar('|',assumeNotNull(securityRules))[3] as akamai_security_deny_rule,
if(empty(splitByChar('|',assumeNotNull(securityRules))[3]),0,1) as akamai_security_denied,
multiIf(akamai_security_deny_rule like '%REP%','Reputation',akamai_security_deny_rule like '3%' or akamai_security_deny_rule like 'BOT-%','BOT',akamai_security_deny_rule like 'IP%','DOS',akamai_security_deny_rule like 'XSS%' or akamai_security_deny_rule like 'WAT-%' or akamai_security_deny_rule like 'RFI-ANOMALY%' or akamai_security_deny_rule like 'PLATFORM-ANOMALY' or akamai_security_deny_rule like 'SQL%' or akamai_security_deny_rule like 'LFI%' or akamai_security_deny_rule like 'CMD-INJECTION%' or akamai_security_deny_rule like 'PROTOCOL-ANOMALY%' or akamai_security_deny_rule like 'ADAPTIVE_UA_IP_BLOCK%' or akamai_security_deny_rule like '6%','WAF Rule','') as akamai_security_deny_group,
splitByChar(':',splitByChar('|',coalesce(assumeNotNull(securityRules),'||'))[2]) as akamai_security_rules_triggered,
splitByChar('|',assumeNotNull(earlyHints))[1] as akamai_early_hints_user_hints,
splitByChar('|',assumeNotNull(earlyHints))[2] as akamai_early_hints_user_hints_bytes,
splitByChar('|',assumeNotNull(earlyHints))[3] as akamai_early_hints_akamai_hints,
splitByChar('|',assumeNotNull(earlyHints))[4] as akamai_early_hints_akamai_hints_bytes,
position(assumeNotNull(contentProtectionInfo),'epd') >= 1 as akamai_epd_match,
splitByString('/',assumeNotNull(contentProtectionInfo))[5] as akamai_epd_code,
splitByString('/',assumeNotNull(contentProtectionInfo))[6] as akamai_epd_action_code,
multiIf(akamai_epd_code='av','Anonymous VPN',akamai_epd_code='pp','Public Proxy',akamai_epd_code='hp','Hosting Provider',akamai_epd_code='tr','TOR Exit Node',akamai_epd_code='dp','Smart DNS Proxy',akamai_epd_code='rp','Residential Proxy',akamai_epd_code='vc','VPN Data Centre','') as akamai_epd_category,
multiIf(akamai_epd_action_code='0','Request Denied',akamai_epd_action_code='1','Request Allowed(override)',akamai_epd_action_code='2','Request Redirected','') as akamai_epd_action_name,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[1] as akamai_ew_stage_information,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[2] as akamai_ew_id,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[3] as akamai_ew_process_time,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[4] as akamai_ew_total_time,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[5] as akamai_ew_total_stage_time,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[6] as akamai_ew_used_memory,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[7] as akamai_ew_edge_server_flow,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[8] as akamai_ew_error_code,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[9] as akamai_ew_http_status,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[10] as akamai_ew_cpu_flits,
akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[11] as akamai_ew_tier_id,
akamai_edge_worker(assumeNotNull(ewUsageInfo))[1] as akamai_ew_uid,
akamai_edge_worker(assumeNotNull(ewUsageInfo))[2] as akamai_ew_version,
akamai_edge_worker(assumeNotNull(ewUsageInfo))[3] as akamai_ew_event_handler,
akamai_edge_worker(assumeNotNull(ewUsageInfo))[4] as akamai_ew_off_reason,
akamai_edge_worker(assumeNotNull(ewUsageInfo))[5] as akamai_ew_logic_executed,
akamai_edge_worker(assumeNotNull(ewUsageInfo))[6] as akamai_ew_status,
akamai_edge_worker(assumeNotNull(ewUsageInfo))[7] as akamai_ew_revision_id,
 * 
FROM {STREAM}