{
 "title": "EAA Usage Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   },
   { "name": "table_deviceinventory", "query": "${VAR_TABLE_DEVICEINVENTORY}" },
   { "name": "user_det", "label": "user_det", "query": "${VAR_USER_DET}" },
   { "name": "origin_det", "label": "origin_det", "query": "${VAR_ORIGIN_DET}" },
   { "name": "apphost_det", "label": "apphost_det", "query": "${VAR_APPHOST_DET}" },
   { "name": "commonlibraries", "query": "${VAR_COMMONLIBRARIES}" },
   { "name": "filter" },
   { "name": "timestamp", "query": "datetime" },
   { "name": "generalescaping", "query": "${VAR_GENERALESCAPING}" },
   { "name": "querieslimit", "query": "${VAR_QUERIESLIMIT}" },
   {
    "name": "raw_table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   }
  ]
 },
 "panels": [
  {
   "title": "EAA Usage Statistics",
   "type": "canvas",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(datetime) AS d,\n  uniq(username) as \"Total_Username\",\n  uniq(origin) as \"Total_Origin\",\n  uniq(apphost) as \"Total_EAA_APPS\",\n  uniq(cloudZone) as \"Total_cloudZone\",\n  uniq(conUuid) as \"Total_Connectors\",  \n  SUM(bytesIn) \"Incoming\",\n  SUM(bytesOut) \"Outgoing\"\n  FROM ${table}\n  WHERE $__timeFilter(datetime)\n\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\n\nGROUP BY  d\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Users per APP; du=${__user.login}'"
    }
   ]
  },
  { "title": "LAST 30 MINS usage stats ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Real time active users",
   "type": "stat",
   "description": "Users connected doing active sessions",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    uniq(username) AS Total_Username,\n    d\nFROM (\n    SELECT\n        username,\n        CASE\n            WHEN datetime >= now() - INTERVAL 45 MINUTE\n             AND datetime <  now() - INTERVAL 15 MINUTE\n                THEN toStartOfMinute(now() - INTERVAL 15 MINUTE)\n            WHEN datetime >= now() - INTERVAL 75 MINUTE\n             AND datetime <  now() - INTERVAL 45 MINUTE\n                THEN toStartOfMinute(now() - INTERVAL 45 MINUTE)\n        END AS d\n    FROM ${table}\n    WHERE datetime >= now() - INTERVAL 75 MINUTE\n      AND username != '-'\n      AND ${generalescaping}\n      AND $__adHocFilter()\n) t\nWHERE d IS NOT NULL\nGROUP BY d\nORDER BY d ASC\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Real time active users; du=${__user.login}';\n"
    }
   ]
  },
  {
   "title": "Failed logins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  uniq(username) as Total_Username,\n  toStartOfInterval(datetime, INTERVAL 5 MINUTE) AS d\n  FROM ${table}\n  WHERE datetime >= now() - INTERVAL 30 minute\n\n\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  and username != '-'\n  AND idpinfo IN ('LOGIN|F', 'MFA|MF')\n\n\nGROUP BY  d\norder by d asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Failed logins; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "EAA_App in use",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  uniq(apphost) as Total_Apphost,\n  toStartOfInterval(datetime, INTERVAL 5 MINUTE) AS d\n  FROM ${table}\n  WHERE datetime >= now() - INTERVAL 30 minute\n\n\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  and username != '-'\n\nGROUP BY  d\norder by d asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=EAA_App in use; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Last ${querieslimit} logged in users",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT username, maxOrNull(datetime) AS Last_Access FROM ${table}\nWHERE datetime >= now() - INTERVAL 30 MINUTE\nAND ${generalescaping}\nAND $__adHocFilter() \n\nAND (\n  urlPath = '/saml/sp/response' \n  AND \n  idpinfo = 'UNSPEC|D'\n  AND\n  username != '-'\n)\n\nAND username != '-'\n\nGROUP BY username\nORDER BY Last_Access DESC\nLIMIT ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last ${querieslimit} logged in users; du=${__user.login}'\n"
    }
   ]
  },
  { "title": "EAA Maintenance Alerts", "type": "news", "gridPos": { "h": 22, "w": 6, "x": 18, "y": 2 } },
  {
   "title": "Bandwidth usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT sum(bytesIn)*8/60 as Incoming, sum(bytesOut)*8/60 AS Outgoing, \ntoStartOfInterval(datetime, INTERVAL 60 SECOND) AS d\nFROM ${table} \nWHERE datetime >= now() - INTERVAL 30 MINUTE\nAND ${generalescaping}\nAND $__adHocFilter()\nGROUP BY d\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Bandwidth Usage; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 25 most requested origins",
   "type": "bargauge",
   "description": "Top 25 Requested Origins in the LAST 30 MINS",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT uniq(username) as current_users, origin FROM ${table}\nWHERE datetime >= now() - INTERVAL 30 MINUTE\nAND ${generalescaping}\nAND $__adHocFilter() \nAND origin != '-'\ngroup by origin \norder by current_users desc\nlimit 25\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 25 most requested origins; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 25 most used clientless app",
   "type": "bargauge",
   "description": "Last Accesses for clientless apps.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT uniq(username) as current_users, apphost FROM ${table}\nWHERE datetime >= now() - INTERVAL 30 MINUTE\nAND ${generalescaping}\nAND $__adHocFilter() \nAND clientId ='-' \nAND username != '-'\ngroup by apphost \norder by current_users desc\nlimit 25\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 25 most used clientless app; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 25 most used tunnel apps",
   "type": "bargauge",
   "description": "Last Accesses for Tunnel Apps.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT uniq(username) as current_users, apphost FROM ${table}\n--WHERE datetime > (now() - interval 30 minute)\nWHERE datetime >= now() - INTERVAL 30 MINUTE\nAND ${generalescaping}\nAND $__adHocFilter() \nAND username != '-'\nand clientId != '-'\ngroup by apphost \norder by current_users desc\nlimit 25\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 25 most used tunnel apps; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "User Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "User locations",
     "type": "geomap",
     "description": "Connecting Locations",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT geoCountrycode, geoCountry, uniq(username) as Total_users\nFROM ${table}\nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND username != '-'\nGROUP BY geoCountrycode, geoCountry\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=User locations; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Unique username",
     "type": "timeseries",
     "description": "Login activities",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "panelId": 533 }
     ]
    },
    {
     "title": "Top 25 users",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT username, count() as Hits\nFROM ${table}\nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nand username != '-'\nGROUP BY username\nORDER BY Hits DESC\nlimit 25\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 25 users; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Failed logins",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeInterval(datetime) AS d,\n  count(*) as \"Total\"\n  FROM ${table}\n  WHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \n  AND idpinfo IN ('LOGIN|F', 'MFA|MF')\nGROUP BY  d, denyReason, statusCode\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Failed logins; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} failed login users list",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "rawSql": "SELECT\n  username, denyReason, clientip, datetime\n  FROM ${table}\n  WHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \n  AND idpinfo IN ('LOGIN|F', 'MFA|MF')\n  AND username != '-'\nGROUP BY  username, denyReason, clientip, datetime\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} failed login users list; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Last ${querieslimit} active users",
     "type": "table",
     "description": "Active users that have been accessing during the specified time range",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "rawSql": "SELECT username, maxOrNull(datetime) as Last_Access FROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \n\nAND username != '-'\n\ngroup by username \norder by Last_Access desc\nLIMIT ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last ${querieslimit} active users; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Last ${querieslimit} inactive users",
     "type": "table",
     "description": "Known users who did not make any requests during the selected timeframe. Known users are defined as identities that have made at least one access request.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "rawSql": "SELECT username, maxOrNull(datetime) as Last_Access FROM ${table} \nWHERE datetime >= toDateTime(${__from} / 1000) AND datetime <= toDateTime(${__to} / 1000)\nAND ${generalescaping}\nAND $__adHocFilter() \n\nAND username != '-'\n\n\ngroup by username\nHAVING maxOrNull(datetime) < toDateTime(${__from} / 1000)\n    OR maxOrNull(datetime) > toDateTime(${__to} / 1000)\norder by Last_Access desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last ${querieslimit} inactive users; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Destination Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total origins accessed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "panelId": 533 }
     ]
    },
    {
     "title": "Top ${querieslimit} active destinations",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT origin,\n       maxOrNull(datetime) AS Last_Access\nFROM ${table}\nWHERE $__timeFilter(datetime)\nAND ${generalescaping}\nAND $__adHocFilter() \nAND origin != '-'\nGROUP BY origin\nORDER BY Last_Access DESC\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} active destinations; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} inactive destinations",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT origin,\n       maxOrNull(datetime) AS Last_Access\nFROM ${table}\nWHERE datetime >= toDateTime(${__from} / 1000) AND datetime <= toDateTime(${__to} / 1000)\nAND ${generalescaping}\nAND $__adHocFilter() \n\nAND origin != '-'\n\nGROUP BY origin\nHAVING (\n        maxOrNull(datetime) < toDateTime(${__from} / 1000)\n    OR  maxOrNull(datetime) > toDateTime(${__to} / 1000) \n    )\nORDER BY Last_Access DESC\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} inactive destinations; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} active ports",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  arrayElement(splitByChar(':', ifNull(origin, '')), 2) AS port,\n  count(port) AS port_count,\n  maxOrNull(datetime) AS Last_Access\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND origin IS NOT NULL\n  AND origin != '-'\nGROUP BY port\nORDER BY port_count DESC\nLIMIT ${querieslimit}\nSETTINGS hdx_query_max_execution_time = 60,\n         hdx_query_admin_comment = 'db=${__dashboard}; dp=Top ${querieslimit} active ports; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top 25 Destinations",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 130 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT origin, count() as Hits\nFROM ${table}\nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nand origin != '-'\nGROUP BY origin\nORDER BY Hits DESC\nlimit 25\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 5 Origins; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "EAA Application Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total EAA_APPS accessed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "panelId": 533 }
     ]
    },
    {
     "title": "Top 25 EAA Apps",
     "type": "bargauge",
     "description": "Shows the most accessed EAA Apps, Clientless and Cliented",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT apphost, count() as Hits\nFROM ${table}\nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \n\nAND apphost != '-'\n\nGROUP BY apphost\nHAVING apphost IS NOT NULL\nORDER BY Hits DESC\nlimit 25\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 25 EAA Apps; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} active EAA apps",
     "type": "table",
     "description": "Lists all EAA Apps in use. Clientless and Tunnel Apps",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT apphost, maxOrNull(datetime) as Last_Access FROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND apphost !='-'\ngroup by apphost \norder by Last_Access desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} active EAA apps; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} inactive EAA apps",
     "type": "table",
     "description": "Inactive EAA Apps. Clientless and Tunnel Apps",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT apphost, maxOrNull(datetime) as Last_Access FROM ${table} \nWHERE datetime >= toDateTime(${__from} / 1000) AND datetime <= toDateTime(${__to} / 1000)\nAND ${generalescaping}\nAND $__adHocFilter()\nAND apphost != '-'\ngroup by apphost \nHAVING maxOrNull(datetime) < toDateTime(${__from} / 1000)\n    OR maxOrNull(datetime) > toDateTime(${__to} / 1000)\norder by Last_Access desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} inactive EAA apps; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Connectors Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total connectors accessed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "panelId": 533 }
     ]
    },
    {
     "title": "Top 25 connectors",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT conUuid, count() as Hits\nFROM ${table}\nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND conUuid != '-'\nAND conUuid IS NOT NULL\nGROUP BY conUuid\nORDER BY Hits DESC\nlimit 25\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 25 connectors; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} active connectors",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT conUuid, maxOrNull(datetime) as Last_Access FROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND conUuid != '-'\nAND conUuid IS NOT NULL\ngroup by conUuid \norder by Last_Access desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} active connectors; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} inactive connectors",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 120 },
     "targets": [
      {
       "rawSql": "SELECT conUuid, maxOrNull(datetime) as Last_Access FROM ${table} \nWHERE datetime >= toDateTime(${__from} / 1000) AND datetime <= toDateTime(${__to} / 1000)\nAND ${generalescaping}\nAND $__adHocFilter() \nAND conUuid != '-'\nAND conUuid IS NOT NULL\ngroup by conUuid \nHAVING (\n        maxOrNull(datetime) < toDateTime(${__from} / 1000)\n    OR maxOrNull(datetime) > toDateTime(${__to} / 1000)\n    )\norder by Last_Access desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last accessed apps; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Cloudzones usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total cloudzone accessed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "panelId": 533 }
     ]
    },
    {
     "title": "Top ${querieslimit} cloudzone deployment details",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT cloudZone, apphost as EAA_APP\nFROM ${table}\nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nGROUP BY cloudZone, apphost\nORDER BY cloudZone DESC\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} cloudzone deployment details; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top 25 Cloudzone by users",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT cloudZone, uniq(username) as users\nFROM ${table}\nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nGROUP BY cloudZone\nORDER BY users DESC\nlimit 25\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 25 Cloudzone by users; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top 25 Cloudzone by EAA_APP",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT cloudZone, uniq(apphost) as EAA_APP\nFROM ${table}\nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nGROUP BY cloudZone\nORDER BY EAA_APP DESC\nlimit 25\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 25 Cloudzone by EAA_APP; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total traffic seen",
     "type": "timeseries",
     "description": "Total Aggregate traffic that has been delivered by EAA over the time period selected.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "panelId": 533 }
     ]
    },
    {
     "title": "Top ${querieslimit} total traffic split by username",
     "type": "table",
     "description": "Total traffic delivered for the username.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 93 },
     "targets": [
      {
       "rawSql": "SELECT sum(bytesIn) Incoming, sum(bytesOut) Outgoing, toDate(datetime) as Date, \nusername FROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND username != '-'\nGROUP BY Date, username \norder by username asc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} total traffic split by username; du=${__user.login}'\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} total traffic split by EAA App",
     "type": "table",
     "description": "Traffic that is delivered by both Clientless and Tunnel Apps.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT sum(bytesIn) Incoming, sum(bytesOut) Outgoing, toDate(datetime) as Date, apphost FROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND apphost != '-'\nGROUP BY Date, apphost \norder by apphost asc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} total traffic split by EAA App; du=${__user.login}'\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} total traffic split by destination",
     "type": "table",
     "description": "Total traffic delivered for the internal destination.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT sum(bytesIn) Incoming, sum(bytesOut) Outgoing, toDate(datetime) as Date, \norigin FROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND origin != '-'\nGROUP BY Date, origin \norder by origin asc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} total traffic split by destination; du=${__user.login}'\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Client versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of client version",
     "type": "piechart",
     "gridPos": { "h": 16, "w": 11, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT clientVersion, count(distinct clientId)\nFROM ${table} \nWHERE clientVersion IS NOT NULL and clientVersion != '-' \nand username != '-'\nAND $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \ngroup by clientVersion\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Number of client version; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} client version details",
     "type": "table",
     "gridPos": { "h": 16, "w": 13, "x": 11, "y": 94 },
     "targets": [
      {
       "rawSql": "SELECT clientVersion, clientId, deviceType, username, maxOrNull(datetime) as Last_Access FROM ${table}\nWHERE clientVersion IS NOT NULL and clientVersion != '-'\nand username != '-'\nAND $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nGROUP BY clientVersion, clientId, deviceType, username\norder by Last_Access desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} client version details; du=${__user.login}'\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Device Posture versions (beta not filterable)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of full client version",
     "type": "piechart",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n    clientVersion,\n    count() AS device_count\nFROM (\n    SELECT\n        clientVersion,\n        deviceName \n    FROM ${table_deviceinventory} \n    WHERE $__timeFilter(signalTimestamp)\n      AND deviceName != '-'\n      AND deviceName != ''\n--      AND ${generalescaping}\n--      AND $__adHocFilter()     \n    ORDER BY signalTimestamp DESC\n    LIMIT 1 BY deviceName\n)\nGROUP BY clientVersion\nORDER BY clientVersion\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Number of full client version; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Number of major client version",
     "type": "piechart",
     "gridPos": { "h": 16, "w": 6, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    concat(extract(clientVersion, '(\\\\d+)'), '.*') AS major_version,\n    count() AS device_count\nFROM (\n    SELECT\n        clientVersion,\n        deviceName\n    FROM ${table_deviceinventory} \n    WHERE $__timeFilter(signalTimestamp)\n      AND deviceName != '-'\n      AND deviceName != ''\n--      AND ${generalescaping}\n--      AND $__adHocFilter()     \n    ORDER BY signalTimestamp DESC\n    LIMIT 1 BY deviceName\n)\nWHERE major_version != '.*'\nGROUP BY major_version\nORDER BY device_count desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Number of major client version; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Number of minor client version",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 6, "x": 18, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    extract(clientVersion, '(\\\\d+\\\\.\\\\d+)') AS major_minor_version,\n    count() AS device_count\nFROM (\n    SELECT\n        clientVersion,\n        deviceName\n    FROM ${table_deviceinventory} \n    WHERE $__timeFilter(signalTimestamp)\n      AND deviceName != '-'\n      AND deviceName != ''\n--      AND ${generalescaping}\n--      AND $__adHocFilter()  \n    ORDER BY signalTimestamp DESC\n    LIMIT 1 BY deviceName\n)\nWHERE major_minor_version != ''\nGROUP BY major_minor_version\nORDER BY device_count desc \nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Number of minor client version; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} client version details",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 111 },
     "targets": [
      {
       "rawSql": "SELECT\n    clientVersion,\n    deviceName,\n    idpUsername,\n    osName,\n    osVersion,\n    signalTimestamp as last_update\nFROM (\n    SELECT\n        clientVersion,\n        deviceName,\n        osName,\n        osVersion,\n        signalTimestamp,\n        idpUsername\n    FROM ${table_deviceinventory} \n    WHERE $__timeFilter(signalTimestamp)\n      AND deviceName != '-'\n      AND deviceName != ''\n--      AND ${generalescaping}\n--      AND $__adHocFilter()     \n    ORDER BY signalTimestamp DESC\n    LIMIT 1 BY deviceName\n)\nGROUP BY clientVersion, deviceName, idpUsername, osName, osVersion, last_update\nORDER BY last_update desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} client version details; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status codes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 14, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeInterval(datetime) AS time,\n    statusCode,\n    count(*) AS \"Total\"\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY time, statusCode\nORDER BY time ASC, statusCode\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Status codes; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Status codes",
     "type": "table",
     "gridPos": { "h": 11, "w": 10, "x": 14, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    toString(statusCode) AS statusCode,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  statusCode\nORDER BY Total desc\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Status codes; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Error codes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 14, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeInterval(datetime) AS time,\n    errorCode,\n    count(*) AS \"Total\"\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY time, errorCode\nORDER BY time ASC, errorCode\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Error codes; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Error codes",
     "type": "table",
     "gridPos": { "h": 11, "w": 10, "x": 14, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    toString(errorCode) AS errorCode,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  errorCode\nORDER BY Total desc\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Error codes; du=${__user.login}';\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Request specs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top ${querieslimit} device OS",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    deviceOs,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  deviceOs\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} device OS; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} device type",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    deviceType,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  deviceType\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} device type; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} user agent",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    userAgent,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  userAgent\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} user agent; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} client process",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    clientProcess,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  clientProcess\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} client process; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} client IP",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    clientip,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  clientip\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} client IP; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} session ID",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    sessionId,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\n  AND sessionId != '-'\nGROUP BY  sessionId\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} session ID; du=${__user.login}';\n"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP specs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP method",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 14, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeInterval(datetime) AS time,\n    httpMethod,\n    count(*) AS \"Total\"\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY time, httpMethod\nORDER BY time ASC, httpMethod\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=HTTP method; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "HTTP Method",
     "type": "table",
     "gridPos": { "h": 11, "w": 10, "x": 14, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    httpMethod,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  httpMethod\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=HTTP Method; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} URL Path",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    urlPath,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  urlPath\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} URL Path; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} referer",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    referer,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  referer\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} referer; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} content type",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    contentType,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  contentType\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} content type; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} HTTP version",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    httpVer,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  httpVer\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} HTTP version; du=${__user.login}';\n"
      }
     ]
    }
   ]
  }
 ]
}