{
 "title": "_EAA-common-libraries",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   },
   { "name": "filter" },
   { "name": "timestamp", "query": "datetime" },
   { "name": "generalescaping", "query": "${VAR_GENERALESCAPING}" },
   { "name": "eselect" },
   { "name": "querieslimit", "query": "${VAR_QUERIESLIMIT}" },
   { "name": "etitle" },
   { "name": "customquery" },
   { "name": "customtime" },
   {
    "name": "raw_table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   }
  ]
 },
 "panels": [
  {
   "title": "_EAA-common-libraries (Internal)",
   "type": "canvas",
   "description": "This is an internal library dashboard that enables the other dashboards. It should not be deleted.",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(datetime) AS d,\n  uniq(username) as \"Total_Username\",\n  uniq(origin) as \"Total_Origin\",\n  uniq(apphost) as \"Total_EAA_APPS\",\n  uniq(cloudZone) as \"Total_cloudZone\",\n  SUM(bytesIn) \"Incoming\",\n  SUM(bytesOut) \"Outgoing\",\n  uniq(conUuid) as \"Total_Connectors\"\n  FROM ${table}\n  WHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \n  AND origin != '-'\n  AND username != '-'\n  AND apphost != '-'\n  and conUuid != '-'\nGROUP BY  d\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Users per APP; du=${__user.login}'"
    }
   ]
  },
  { "title": "Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "${etitle}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeInterval(datetime) AS time,\n    ${eselect},\n    count(*) AS \"Total\"\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY time, ${eselect}\nORDER BY time ASC, ${eselect}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Users per APP; du=${__user.login}';\n"
    }
   ]
  },
  { "title": "full list plain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "${etitle} details",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT ${eselect}, maxOrNull(datetime) as Last_Access \nFROM ${table} \nWHERE $__timeFilter(datetime)  \nAND ${generalescaping}\nAND $__adHocFilter() \n\n-- ### PPP WARNING COPY (AND KEEP ALIGNED!) THIS BLOCK IN ALL CUSTOMLIBRARIES QUERIES!\nAND (\n    CASE\n        -- Apply one of the following filters if customquery has its value\n        WHEN '${customquery}' = 'CQnoapphostdash' THEN apphost != '-'\n        WHEN '${customquery}' = 'CQnoapphostconuuiddash' THEN apphost != '-' AND conUuid != '-'\n        WHEN '${customquery}' = 'CQnoapphostorigindash' THEN apphost != '-' AND origin != '-'\n        WHEN '${customquery}' = 'CQnoapphostoriginusernamedash' THEN apphost != '-' AND origin != '-' AND username != '-'\n        WHEN '${customquery}' = 'CQnoapphostusernamedash' THEN apphost != '-' AND username != '-'\n\n        WHEN '${customquery}' = 'CQnoconuuiddash' THEN conUuid != '-' AND conUuid IS NOT NULL\n        WHEN '${customquery}' = 'CQnoconuuidorigindash' THEN conUuid != '-' AND conUuid IS NOT NULL AND origin != '-'\n        WHEN '${customquery}' = 'CQnoconuuidusernamedash' THEN conUuid != '-' AND conUuid IS NOT NULL AND username != '-'\n\n        WHEN '${customquery}' = 'CQnoorigindash' THEN origin != '-' \n        WHEN '${customquery}' = 'CQnooriginusernamedash' THEN origin != '-' AND username != '-'\n        \n        WHEN '${customquery}' = 'CQnousernamedash' THEN username != '-'\n\n        WHEN '${customquery}' = 'CQlastuserlogin' THEN username != '-' AND ( urlPath = '/saml/sp/response' AND idpinfo = 'UNSPEC|D' AND username != '-')\n        WHEN '${customquery}' = 'CQuserfailedlogin' THEN username != '-' AND idpinfo IN ('LOGIN|F', 'MFA|MF')\n        WHEN '${customquery}' = 'CQclientversion' THEN clientVersion IS NOT NULL AND clientVersion != '-' AND username != '-'\n\n        -- don't filter by default\n        ELSE 1=1\n    END\n)\n\n-- PPP don't copy this block into the panel: full list external timerange (inactive things)\nAND (\n    CASE\n        -- if CTlast30 get only last 30minutes of results\n        WHEN '${customtime}' = 'CTlast30' THEN datetime >= now() - INTERVAL 30 MINUTE\n\n        ELSE 1=1\n\n    END\n)\n-- ### \n\ngroup by ${eselect}\n\norder by Last_Access desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last accessing users; du=${__user.login}'"
    }
   ]
  },
  { "title": "full list with count Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "${etitle} details",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT ${eselect}, count(*) as Total\nFROM ${table} \nWHERE $__timeFilter(datetime)  \nAND ${generalescaping}\nAND $__adHocFilter() \n\n-- ### PPP WARNING COPY (AND KEEP ALIGNED!) THIS BLOCK IN ALL CUSTOMLIBRARIES QUERIES!\nAND (\n    CASE\n        -- Apply one of the following filters if customquery has its value\n        WHEN '${customquery}' = 'CQnoapphostdash' THEN apphost != '-'\n        WHEN '${customquery}' = 'CQnoapphostconuuiddash' THEN apphost != '-' AND conUuid != '-'\n        WHEN '${customquery}' = 'CQnoapphostorigindash' THEN apphost != '-' AND origin != '-'\n        WHEN '${customquery}' = 'CQnoapphostoriginusernamedash' THEN apphost != '-' AND origin != '-' AND username != '-'\n        WHEN '${customquery}' = 'CQnoapphostusernamedash' THEN apphost != '-' AND username != '-'\n\n        WHEN '${customquery}' = 'CQnoconuuiddash' THEN conUuid != '-' AND conUuid IS NOT NULL\n        WHEN '${customquery}' = 'CQnoconuuidorigindash' THEN conUuid != '-' AND conUuid IS NOT NULL AND origin != '-'\n        WHEN '${customquery}' = 'CQnoconuuidusernamedash' THEN conUuid != '-' AND conUuid IS NOT NULL AND username != '-'\n\n        WHEN '${customquery}' = 'CQnoorigindash' THEN origin != '-' \n        WHEN '${customquery}' = 'CQnooriginusernamedash' THEN origin != '-' AND username != '-'\n        \n        WHEN '${customquery}' = 'CQnousernamedash' THEN username != '-'\n\n        WHEN '${customquery}' = 'CQlastuserlogin' THEN username != '-' AND ( urlPath = '/saml/sp/response' AND idpinfo = 'UNSPEC|D' AND username != '-')\n        WHEN '${customquery}' = 'CQuserfailedlogin' THEN username != '-' AND idpinfo IN ('LOGIN|F', 'MFA|MF')\n        WHEN '${customquery}' = 'CQclientversion' THEN clientVersion IS NOT NULL AND clientVersion != '-' AND username != '-'\n\n        -- don't filter by default\n        ELSE 1=1\n    END\n)\n\n-- PPP don't copy this block into the panel: full list external timerange (inactive things)\nAND (\n    CASE\n        -- if CTlast30 get only last 30minutes of results\n        WHEN '${customtime}' = 'CTlast30' THEN datetime >= now() - INTERVAL 30 MINUTE\n\n        ELSE 1=1\n\n    END\n)\n-- ### \n\ngroup by ${eselect}\n\norder by Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last accessing users; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "full list with no maxdate event",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "${etitle} details",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT ${eselect}, maxOrNull(datetime) as Last_Access \nFROM ${table} \n\nWHERE $__timeFilter(datetime)\nAND ${generalescaping}\nAND $__adHocFilter() \n\n-- ### PPP WARNING COPY (AND KEEP ALIGNED!) THIS BLOCK IN ALL CUSTOMLIBRARIES QUERIES!\nAND (\n    CASE\n        -- Apply one of the following filters if customquery has its value\n        WHEN '${customquery}' = 'CQnoapphostdash' THEN apphost != '-'\n        WHEN '${customquery}' = 'CQnoapphostconuuiddash' THEN apphost != '-' AND conUuid != '-'\n        WHEN '${customquery}' = 'CQnoapphostorigindash' THEN apphost != '-' AND origin != '-'\n        WHEN '${customquery}' = 'CQnoapphostoriginusernamedash' THEN apphost != '-' AND origin != '-' AND username != '-'\n        WHEN '${customquery}' = 'CQnoapphostusernamedash' THEN apphost != '-' AND username != '-'\n\n        WHEN '${customquery}' = 'CQnoconuuiddash' THEN conUuid != '-' AND conUuid IS NOT NULL\n        WHEN '${customquery}' = 'CQnoconuuidorigindash' THEN conUuid != '-' AND conUuid IS NOT NULL AND origin != '-'\n        WHEN '${customquery}' = 'CQnoconuuidusernamedash' THEN conUuid != '-' AND conUuid IS NOT NULL AND username != '-'\n\n        WHEN '${customquery}' = 'CQnoorigindash' THEN origin != '-'\n        WHEN '${customquery}' = 'CQnooriginusernamedash' THEN origin != '-' AND username != '-'\n\n        WHEN '${customquery}' = 'CQnousernamedash' THEN username != '-'\n\n        WHEN '${customquery}' = 'CQlastuserlogin' THEN username != '-' AND ( urlPath = '/saml/sp/response' AND idpinfo = 'UNSPEC|D' AND username != '-')\n        WHEN '${customquery}' = 'CQuserfailedlogin' THEN username != '-' AND idpinfo IN ('LOGIN|F', 'MFA|MF')\n        WHEN '${customquery}' = 'CQclientversion' THEN clientVersion IS NOT NULL AND clientVersion != '-' AND username != '-'\n\n        -- don't filter by default\n        ELSE 1=1\n    END\n)\n\n-- PPP don't copy this block into the panel: full list external timerange (inactive things)\nAND (\n    CASE\n        -- if CTlast30 get only last 30minutes of results\n        WHEN '${customtime}' = 'CTlast30' THEN datetime >= now() - INTERVAL 30 MINUTE\n\n        ELSE 1=1\n\n    END\n)\n-- ###\n\ngroup by ${eselect}\n\norder by Last_Access desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last accessing users; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "full list external timerange (inactive things)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "${etitle} details",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT ${eselect}, maxOrNull(datetime) as Last_Access \nFROM ${table} \nWHERE datetime >= toDateTime(${__from} / 1000) AND datetime <= toDateTime(${__to} / 1000)\nAND ${generalescaping}\nAND $__adHocFilter() \n\n-- ### PPP WARNING COPY (AND KEEP ALIGNED!) THIS BLOCK IN ALL CUSTOMLIBRARIES QUERIES!\nAND (\n    CASE\n        -- Apply one of the following filters if customquery has its value\n        WHEN '${customquery}' = 'CQnoapphostdash' THEN apphost != '-'\n        WHEN '${customquery}' = 'CQnoapphostconuuiddash' THEN apphost != '-' AND conUuid != '-'\n        WHEN '${customquery}' = 'CQnoapphostorigindash' THEN apphost != '-' AND origin != '-'\n        WHEN '${customquery}' = 'CQnoapphostoriginusernamedash' THEN apphost != '-' AND origin != '-' AND username != '-'\n        WHEN '${customquery}' = 'CQnoapphostusernamedash' THEN apphost != '-' AND username != '-'\n\n        WHEN '${customquery}' = 'CQnoconuuiddash' THEN conUuid != '-' AND conUuid IS NOT NULL\n        WHEN '${customquery}' = 'CQnoconuuidorigindash' THEN conUuid != '-' AND conUuid IS NOT NULL AND origin != '-'\n        WHEN '${customquery}' = 'CQnoconuuidusernamedash' THEN conUuid != '-' AND conUuid IS NOT NULL AND username != '-'\n\n        WHEN '${customquery}' = 'CQnoorigindash' THEN origin != '-' \n        WHEN '${customquery}' = 'CQnooriginusernamedash' THEN origin != '-' AND username != '-'\n        \n        WHEN '${customquery}' = 'CQnousernamedash' THEN username != '-'\n\n        WHEN '${customquery}' = 'CQlastuserlogin' THEN username != '-' AND ( urlPath = '/saml/sp/response' AND idpinfo = 'UNSPEC|D' AND username != '-')\n        WHEN '${customquery}' = 'CQuserfailedlogin' THEN username != '-' AND idpinfo IN ('LOGIN|F', 'MFA|MF')\n        WHEN '${customquery}' = 'CQclientversion' THEN clientVersion IS NOT NULL AND clientVersion != '-' AND username != '-'\n\n        -- don't filter by default\n        ELSE 1=1\n    END\n)\n-- ### \n\ngroup by ${eselect}\nHAVING maxOrNull(datetime) < toDateTime(${__from} / 1000) OR maxOrNull(datetime) > toDateTime(${__to} / 1000)\norder by Last_Access desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last accessing users; du=${__user.login}'"
    }
   ]
  },
  { "title": "traffic specific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "${etitle} details",
   "type": "canvas",
   "description": "Traffic that is delivered by both Clientless and Tunnel Apps.",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT sum(bytesIn) Incoming, sum(bytesOut) Outgoing, toDate(datetime) as Date, ${eselect}  \nFROM ${table} \nWHERE $__timeFilter(datetime)\nAND ${generalescaping}\nAND $__adHocFilter() \n\n-- ### PPP WARNING COPY (AND KEEP ALIGNED!) THIS BLOCK IN ALL CUSTOMLIBRARIES QUERIES!\nAND (\n    CASE\n        -- Apply one of the following filters if customquery has its value\n        WHEN '${customquery}' = 'CQnoapphostdash' THEN apphost != '-'\n        WHEN '${customquery}' = 'CQnoapphostconuuiddash' THEN apphost != '-' AND conUuid != '-'\n        WHEN '${customquery}' = 'CQnoapphostorigindash' THEN apphost != '-' AND origin != '-'\n        WHEN '${customquery}' = 'CQnoapphostoriginusernamedash' THEN apphost != '-' AND origin != '-' AND username != '-'\n        WHEN '${customquery}' = 'CQnoapphostusernamedash' THEN apphost != '-' AND username != '-'\n\n        WHEN '${customquery}' = 'CQnoconuuiddash' THEN conUuid != '-' AND conUuid IS NOT NULL\n        WHEN '${customquery}' = 'CQnoconuuidorigindash' THEN conUuid != '-' AND conUuid IS NOT NULL AND origin != '-'\n        WHEN '${customquery}' = 'CQnoconuuidusernamedash' THEN conUuid != '-' AND conUuid IS NOT NULL AND username != '-'\n\n        WHEN '${customquery}' = 'CQnoorigindash' THEN origin != '-'\n        WHEN '${customquery}' = 'CQnooriginusernamedash' THEN origin != '-' AND username != '-'\n\n        WHEN '${customquery}' = 'CQnousernamedash' THEN username != '-'\n\n        WHEN '${customquery}' = 'CQlastuserlogin' THEN username != '-' AND idpinfo = 'LOGIN|S'\n        WHEN '${customquery}' = 'CQuserfailedlogin' THEN username != '-' AND idpinfo IN ('LOGIN|F', 'MFA|MF')\n        WHEN '${customquery}' = 'CQclientversion' THEN clientVersion IS NOT NULL AND clientVersion != '-' AND username != '-'\n\n        -- don't filter by default\n        ELSE 1=1\n    END\n)\n\n-- PPP don't copy this block into the panel: full list external timerange (inactive things)\nAND (\n    CASE\n        -- if CTlast30 get only last 30minutes of results\n        WHEN '${customtime}' = 'CTlast30' THEN datetime >= now() - INTERVAL 30 MINUTE\n\n        ELSE 1=1\n\n    END\n)\n-- ###\n\nGROUP BY Date, ${eselect}  \norder by Date desc\nlimit ${querieslimit}\n"
    }
   ]
  },
  { "title": "test impossible travel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "impossible travel",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 55 },
   "targets": [
    {
     "rawSql": "SELECT\n  username,\n  min(datetime) AS window_start,\n  max(datetime) AS window_end,\n  count(DISTINCT geoCountry) AS distinct_countries,\n  groupArray(DISTINCT geoCountry) AS countries_seen\nFROM ${table}\nWHERE $__timeFilter(datetime)\nGROUP BY\n  username,\n  intDiv(toUnixTimestamp(datetime), 100000) -- to be sure we are totally inside window start window end\nHAVING distinct_countries > 1"
    }
   ]
  }
 ]
}