folders:
  hdx-main-folder:
    name: TrafficPeak Certified Reference Dashboards
    children:
      hdx-security-folder:
        name: Security
dashboards:
  hdx-bot-insights-siem:
    dashboard:
      __extend__: dashboards/bot_insights_siem.json
    folderUid: hdx-security-folder
    inputs:
      DS_HYDROLIX-HYDROLIX-DATASOURCE: hdx-hydrolix-datasource
      VAR_SIEM_RAW: akamai.siem
      VAR_SIEM_SUMMARY_HOUR: akamai.bot_siem_summary_hour
      VAR_SIEM_SUMMARY_DAY: akamai.bot_siem_summary_day
      VAR_SIEM_SUMMARY_MONTH: akamai.bot_siem_summary_month
