{
 "title": "Bot Insights (SIEM)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "SELECT  CASE\nWHEN ${duration} <= 24 THEN '${summary_min}'\nWHEN ${duration} > 24 THEN '${summary_hour}'\nEND"
   },
   {
    "name": "seconds",
    "query": "SELECT  CASE\nWHEN ${duration} <= 24 THEN 60\nWHEN ${duration} > 24 THEN 3600\nEND"
   },
   { "name": "summary_min", "query": "${VAR_SUMMARY_MIN}" },
   { "name": "summary_hour", "query": "${VAR_SUMMARY_HOUR}" },
   { "name": "filter", "label": "Filter" },
   {
    "name": "duration",
    "query": "SELECT datediff('h', $__fromTime, $__toTime)"
   },
   {
    "name": "siem_table",
    "query": "SELECT CASE\nWHEN ${duration} < 6 THEN '${siem_raw}'\nWHEN ${duration} >=6 AND ${duration} < 72 THEN '${siem_summary_hour}'\nELSE '${siem_summary_day}'\nEND"
   },
   { "name": "siem_raw", "query": "${VAR_SIEM_RAW}" },
   { "name": "siem_summary_hour", "query": "${VAR_SIEM_SUMMARY_HOUR}" },
   { "name": "siem_summary_day", "query": "${VAR_SIEM_SUMMARY_DAY}" },
   {
    "name": "attackTypes_var",
    "query": "SELECT  IF('${table}' = '${siem_raw}', 'attackTypes', $$arrayFilter((x, y) -> y = 1, ['Bot','WAF', 'Reputation','Custom','DoS', 'User Risk', 'Network Firewall', 'Custom'], [attack_bot, attack_waf,attack_reputation,attack_custom_bot,attack_dos, attack_risk, attack_firewall, attack_custom_rules]) $$ )"
   },
   {
    "name": "WAFConfig",
    "query": "with  cte as (\nSELECT 'WAF Security File' as WafConfig, '3366' as WafConfigId, 'CPC PoC' as PolicyName, '6h78_267295' as PolicyId UNION ALL \nSELECT 'WAF Security File' as WafConfig, '3366' as WafConfigId, 'NL_Placeholder' as PolicyName, 'nlph_40921' as PolicyId UNION ALL \nSELECT 'WAF Security File' as WafConfig, '3366' as WafConfigId, 'QA_ChoiceHotels' as PolicyName, 'QACH_58335' as PolicyId UNION ALL \nSELECT 'WAF Security File' as WafConfig, '3366' as WafConfigId, 'Alert Monitor only' as PolicyName, 'ps_224861' as PolicyId UNION ALL \nSELECT 'WAF Security File' as WafConfig, '3366' as WafConfigId, 'KRS_ChoiceHotels' as PolicyName, '2000_5001' as PolicyId UNION ALL \nSELECT 'WAF Security File' as WafConfig, '3366' as WafConfigId, 'Redirects' as PolicyName, 'redi_54784' as PolicyId UNION ALL \nSELECT 'Radisson Americas Security File' as WafConfig, '72649' as WafConfigId, 'Radisson Americas Security Policy' as PolicyName, 'RHBM_116227' as PolicyId UNION ALL \nSELECT 'International' as WafConfig, '21242' as WafConfigId, 'KRS_International_ChoiceHotels' as PolicyName, 'intd_49367' as PolicyId UNION ALL \nSELECT 'International' as WafConfig, '21242' as WafConfigId, 'NL_Placeholder' as PolicyName, 'nlph_49365' as PolicyId UNION ALL \nSELECT 'International' as WafConfig, '21242' as WafConfigId, 'Redirects' as PolicyName, 'redi_55714' as PolicyId UNION ALL \nSELECT 'Choice University Security File' as WafConfig, '100983' as WafConfigId, 'Choice University Security Policy' as PolicyName, 'CU_256240' as PolicyId UNION ALL \n\nSELECT 'Advantage' as WafConfig, '21371' as WafConfigId, 'NL_Placeholder' as PolicyName, 'nlph_49856' as PolicyId UNION ALL \nSELECT 'Advantage' as WafConfig, '21371' as WafConfigId, 'Skytouch KRS policy' as PolicyName, 'sky_291530' as PolicyId UNION ALL \nSELECT 'Advantage' as WafConfig, '21371' as WafConfigId, 'Alert Monitor only' as PolicyName, 'aml_243752' as PolicyId UNION ALL \nSELECT 'Advantage' as WafConfig, '21371' as WafConfigId, 'Choice Advantage KRS policy' as PolicyName, 'CU_qik2_4985556240' as PolicyId \n ), cte2 as (\nSELECT policyId\nFROM ${siem_table}\nWHERE $__timeFilter(timestamp)\ngroup by policyId\n)\n         select concatWithSeparator('|', toString(WafConfigId), concatWithSeparator(' : ', toString(WafConfigId), WafConfig)) as WAFConfig from cte\n         INNER JOIN cte2 on  cte.PolicyId = cte2.policyId\n                      GROUP BY WAFConfig\n"
   },
   {
    "name": "WAFPolicy",
    "query": "with  cte as (\nSELECT 'WAF Security File' as WafConfig, '3366' as WafConfigId, 'CPC PoC' as PolicyName, '6h78_267295' as PolicyId UNION ALL \nSELECT 'WAF Security File' as WafConfig, '3366' as WafConfigId, 'NL_Placeholder' as PolicyName, 'nlph_40921' as PolicyId UNION ALL \nSELECT 'WAF Security File' as WafConfig, '3366' as WafConfigId, 'QA_ChoiceHotels' as PolicyName, 'QACH_58335' as PolicyId UNION ALL \nSELECT 'WAF Security File' as WafConfig, '3366' as WafConfigId, 'Alert Monitor only' as PolicyName, 'ps_224861' as PolicyId UNION ALL \nSELECT 'WAF Security File' as WafConfig, '3366' as WafConfigId, 'KRS_ChoiceHotels' as PolicyName, '2000_5001' as PolicyId UNION ALL \nSELECT 'WAF Security File' as WafConfig, '3366' as WafConfigId, 'Redirects' as PolicyName, 'redi_54784' as PolicyId UNION ALL \nSELECT 'Radisson Americas Security File' as WafConfig, '72649' as WafConfigId, 'Radisson Americas Security Policy' as PolicyName, 'RHBM_116227' as PolicyId UNION ALL \nSELECT 'International' as WafConfig, '21242' as WafConfigId, 'KRS_International_ChoiceHotels' as PolicyName, 'intd_49367' as PolicyId UNION ALL \nSELECT 'International' as WafConfig, '21242' as WafConfigId, 'NL_Placeholder' as PolicyName, 'nlph_49365' as PolicyId UNION ALL \nSELECT 'International' as WafConfig, '21242' as WafConfigId, 'Redirects' as PolicyName, 'redi_55714' as PolicyId UNION ALL \nSELECT 'Choice University Security File' as WafConfig, '100983' as WafConfigId, 'Choice University Security Policy' as PolicyName, 'CU_256240' as PolicyId UNION ALL \n\nSELECT 'Advantage' as WafConfig, '21371' as WafConfigId, 'NL_Placeholder' as PolicyName, 'nlph_49856' as PolicyId UNION ALL \nSELECT 'Advantage' as WafConfig, '21371' as WafConfigId, 'Skytouch KRS policy' as PolicyName, 'sky_291530' as PolicyId UNION ALL \nSELECT 'Advantage' as WafConfig, '21371' as WafConfigId, 'Alert Monitor only' as PolicyName, 'aml_243752' as PolicyId UNION ALL \nSELECT 'Advantage' as WafConfig, '21371' as WafConfigId, 'Choice Advantage KRS policy' as PolicyName, 'CU_qik2_4985556240' as PolicyId \n ),\n cte2 as (SELECT policyId\nFROM ${siem_table}\nWHERE $__timeFilter(timestamp)\ngroup by policyId)\n\n\n\nselect  concatWithSeparator('|', toString(PolicyId), concatWithSeparator(' : ', toString(PolicyId), PolicyName)) from cte\n INNER JOIN cte2 on  cte.PolicyId = cte2.policyId\nwhere  $__conditionalAll(WafConfigId in (${WAFConfig}), ${WAFConfig})"
   },
   {
    "name": "bot_category_var",
    "query": "with cte as (SELECT  \nbot_type,\n${bot_category_array} as bot_category_array\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__conditionalAll(configId in (${WAFConfig:sqlstring}), ${WAFConfig})\nAND $__conditionalAll(policyId in (${WAFPolicy:sqlstring}),${WAFPolicy})\nand notEmpty(bot_type))\nSELECT bot_category FROM cte array join bot_category_array as bot_category GROUP BY bot_category"
   },
   {
    "name": "bot_category_array",
    "query": "SELECT IF('${table}' = '${siem_raw}', '[bot_category]', '[bot_category_Str]')"
   },
   {
    "name": "Bot_Id_var",
    "query": "WITH cte AS (SELECT \n  bot_type,\n  ${Bot_Id_array} AS Bot_Id_array,\n  bot_category\n  FROM ${table}\n  WHERE $__timeFilter(timestamp)\n    AND $__conditionalAll(configId in (${WAFConfig:sqlstring}), ${WAFConfig})\n    AND $__conditionalAll(policyId in (${WAFPolicy:sqlstring}),${WAFPolicy})\n \n AND $__conditionalAll(arrayExists(x -> x IN (${bot_category_var:sqlstring}), ${bot_category_array}), ${bot_category_var})\n    AND notEmpty(bot_type)\n )\n\nSELECT Bot_Id \nFROM cte\nARRAY JOIN Bot_Id_array AS Bot_Id\nGROUP BY Bot_Id "
   },
   {
    "name": "Bot_Id_array",
    "query": "SELECT IF('${table}' = '${siem_raw}', 'Bot_Id', '[Bot_Id_Str]')"
   },
   {
    "name": "interval",
    "query": " SELECT CASE \nWHEN ${duration} < 6 THEN 'INTERVAL 1 MINUTE'\nWHEN ${duration} >= 6 AND ${duration} < 72 THEN 'INTERVAL 1 HOUR' \nELSE 'INTERVAL 1 DAY'\nEND"
   },
   {
    "name": "BotCategoryAkamai_array",
    "query": "SELECT IF('${table}' = '${siem_raw}', 'BotCategoryAkamai', '[BotCategoryAkamaiStr]')"
   },
   {
    "name": "cnt_all_var",
    "query": "SELECT IF('${table}' = '${siem_raw}', 'count(*)', 'cnt_all')"
   }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "## Bot Visibility\n\n**Provides visibility into how bots are interacting with your websites.**\n\nUnderstand high-level trends in bot traffic and which AI bots are requesting resources from your site.\n\nNOTE: THIS DASHBOARD IS SET TO QUERY FOR MAX OF 30 DAYS."
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Request overview",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    count() as \"Total Requests\",\n    countIf(notEmpty(bot_type) = 1) AS \"Total Bot Requests\",\n    countIf(notEmpty(bot_type) = 1 AND bot_category = 'Artificial Intelligence (AI) Bots') AS \"AI Bot Requests\",\n    timestamp\nFROM \n    ${table}\nWHERE $__timeFilter(timestamp)\n    AND $__adHocFilter()\nGROUP BY\n    timestamp\n    \nSETTINGS hdx_query_max_execution_time=60, hdx_query_max_timerange_sec=2592000, hdx_query_admin_comment='db=${__dashboard}; dp=Traffic breakdown; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Bot traffic per category",
   "type": "piechart",
   "description": "bot traffic for each category",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    bot_category,\n    count()\nFROM \n    ${table}\nWHERE \n    $__timeFilter(timestamp)\n    AND $__adHocFilter()\n    AND notEmpty(bot_type) = 1\nGROUP BY bot_category\nSETTINGS hdx_query_max_execution_time=60, hdx_query_max_timerange_sec=2592000, hdx_query_admin_comment='db=${__dashboard}; Bot traffic percentage per category; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "All Bot Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n    toStartOfDay(timestamp) as time,\n    count() as \"All Bot Requests\",\n    bot_category    \nFROM \n    ${table}\nWHERE $__timeFilter(timestamp)\n    AND $__adHocFilter()\n    AND notEmpty(bot_type) = 1\nGROUP BY \n    time, bot_category\nORDER BY \n    count() DESC\n    \nSETTINGS hdx_query_max_execution_time=60, hdx_query_max_timerange_sec=2592000, hdx_query_admin_comment='db=${__dashboard}; dp=Bot traffic; du=${__user.login}'"
    }
   ]
  },
  { "title": "AI Bot Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "AI Bot Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n    toStartOfDay(timestamp) as time,\n    count(),\n    botnet_id\nFROM \n    ${table}\nWHERE $__timeFilter(timestamp)\n    AND $__adHocFilter()\n    AND notEmpty(bot_type) = 1\n    AND bot_category = 'Artificial Intelligence (AI) Bots'\nGROUP BY \n    time, botnet_id\nORDER BY \n    time, count() DESC\n    \nSETTINGS hdx_query_max_execution_time=60, hdx_query_max_timerange_sec=2592000, hdx_query_admin_comment='db=${__dashboard}; dp=AI traffic by bot; du=${__user.login}'"
    }
   ]
  },
  { "title": "AI Bots: Requested Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Summary of Crawl Policy File Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT \n    botnet_id,\n    path,\n    count() as count\nFROM \n    ${table}\nWHERE $__timeFilter(timestamp)\n    AND $__adHocFilter()\n    AND notEmpty(bot_type) = 1\n    AND bot_category = 'Artificial Intelligence (AI) Bots'\nGROUP BY \n    botnet_id, path\nORDER BY\n    count DESC\n    \nSETTINGS hdx_query_max_execution_time=60, hdx_query_max_timerange_sec=2592000, hdx_query_admin_comment='db=${__dashboard}; dp=Resource request by bot; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Crawl Policy File Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n    toStartOfDay(timestamp) as time,\n    botnet_id,\n    path,\n    count() as count\nFROM \n    ${table}\nWHERE $__timeFilter(timestamp)\n    AND $__adHocFilter()\n    AND notEmpty(bot_type) = 1\n    AND bot_category = 'Artificial Intelligence (AI) Bots'\nGROUP BY \n    time, botnet_id, path\nORDER BY\n    count() DESC\n    \nSETTINGS hdx_query_max_execution_time=60, hdx_query_max_timerange_sec=2592000, hdx_query_admin_comment='db=${__dashboard}; dp=Timeseries Resoruce request by bot ; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Additional Bot Insights from Web Security Analytics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 67 }
   ]
  },
  {
   "title": "Time Line: Attack Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH cte AS (\n  SELECT  \n    timestamp,\n    ${attackTypes_var} AS attackTypes\n  FROM ${table}\n  WHERE $__timeFilter(timestamp)\n    AND $__conditionalAll(configId IN (${WAFConfig:sqlstring}), ${WAFConfig})\n    AND $__conditionalAll(policyId IN (${WAFPolicy:sqlstring}),${WAFPolicy})\n    AND $__conditionalAll(arrayExists(x -> x IN (${bot_category_var:sqlstring}), ${bot_category_array}), ${bot_category_var})\n    AND $__conditionalAll(arrayExists(x -> x IN (${Bot_Id_var:sqlstring}), ${Bot_Id_array}), ${Bot_Id_var})\n    AND $__adHocFilter() \n)\nSELECT  \n  toStartOfInterval(toDateTime(timestamp), ${interval}) AS time,  \n  attackTypes, \n  count(*) as \"Request Count\"\nFROM cte\nARRAY JOIN attackTypes\nGROUP BY attackTypes, time  \nORDER BY count(*) desc"
    }
   ]
  },
  {
   "title": "Bot Category",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH cte AS (\n  SELECT  \n    timestamp,\n    bot_type,\n    ${bot_category_array} AS bot_category_array\n  FROM ${table}\n  WHERE $__timeFilter(timestamp)\n    AND $__conditionalAll(configId IN (${WAFConfig:sqlstring}), ${WAFConfig})\n    AND $__conditionalAll(policyId IN (${WAFPolicy:sqlstring}),${WAFPolicy})\n    AND $__conditionalAll(arrayExists(x -> x IN (${bot_category_var:sqlstring}), ${bot_category_array}), ${bot_category_var})\n    AND $__conditionalAll(arrayExists(x -> x IN (${Bot_Id_var:sqlstring}), ${Bot_Id_array}), ${Bot_Id_var})\n    --AND notEmpty(toString(botData_responseSegment))\n    AND notEmpty(bot_type)\n    AND $__adHocFilter() \n)\nSELECT \n  bot_category, \n  bot_type,  \n  toStartOfInterval(toDateTime(timestamp), ${interval}) AS time,  \n  count(*) \nFROM cte\nARRAY JOIN bot_category_array AS bot_category\nGROUP BY bot_category, bot_type, time ORDER by count() DESC"
    }
   ]
  },
  {
   "title": "Bot Type",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH cte AS (\n  SELECT  \n    timestamp,\n    bot_type\n  FROM ${table}\n  WHERE $__timeFilter(timestamp)\n    AND $__conditionalAll(configId IN (${WAFConfig:sqlstring}), ${WAFConfig})\n    AND $__conditionalAll(policyId IN (${WAFPolicy:sqlstring}),${WAFPolicy})\n    AND $__conditionalAll(arrayExists(x -> x IN (${bot_category_var:sqlstring}), ${bot_category_array}), ${bot_category_var})\n    AND $__conditionalAll(arrayExists(x -> x IN (${Bot_Id_var:sqlstring}), ${Bot_Id_array}), ${Bot_Id_var})\n    AND notEmpty(bot_type)\n    AND $__adHocFilter() \n)\nSELECT \n  bot_type, \n  toStartOfInterval(toDateTime(timestamp), ${interval}) as time, \n  count(*)  AS \"Count Requests Bot Type\" \nFROM cte \nGROUP BY bot_type, time"
    }
   ]
  },
  {
   "title": "Bot Score",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH cte AS (\n  SELECT  \n    timestamp,\n    multiIf(botScore = 0, '0',\n                botScore between 1 and 10, '1-10', \n                botScore between 11 and 20, '11-20', \n                botScore between 21 and 30, '21-30',\n                botScore between 31 and 40, '31-40',\n                botScore between 41 and 50, '41-50',\n                botScore between 51 and 60, '51-60',\n                botScore between 61 and 70, '61-70',\n                botScore between 71 and 80, '71-80',\n                botScore between 81 and 90, '81-90',\n                botScore between 91 and 100, '91-100', '') AS botScoreRange  \n  FROM ${table}\n  WHERE $__timeFilter(timestamp)\n    AND $__conditionalAll(configId IN (${WAFConfig:sqlstring}), ${WAFConfig})\n    AND $__conditionalAll(policyId IN (${WAFPolicy:sqlstring}),${WAFPolicy})\n    AND $__conditionalAll(arrayExists(x -> x IN (${bot_category_var:sqlstring}), ${bot_category_array}), ${bot_category_var})\n    AND $__conditionalAll(arrayExists(x -> x IN (${Bot_Id_var:sqlstring}), ${Bot_Id_array}), ${Bot_Id_var})\n    AND botScore IS NOT NULL\n    AND $__adHocFilter() \n)\nSELECT \n  botScoreRange,  \n  toStartOfInterval(toDateTime(timestamp), ${interval}) as time,  \n  count(*) \nFROM cte\nGROUP BY botScoreRange, time"
    }
   ]
  },
  {
   "title": "Bot Rule Id",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH cte AS (\n  SELECT  \n    timestamp,\n    [rules] AS BotCategoryAkamai_array,\n    ${bot_category_array} AS bot_category_array\n  FROM ${table}\n  WHERE $__timeFilter(timestamp)\n    AND $__conditionalAll(configId IN (${WAFConfig:sqlstring}), ${WAFConfig})\n    AND $__conditionalAll(policyId IN (${WAFPolicy:sqlstring}),${WAFPolicy})\n    --and notEmpty(bot_type)\n    AND bot_type IN ('Akamai', 'Unknown')\n    AND $__conditionalAll(arrayExists(x -> x IN (${bot_category_var:sqlstring}), ${bot_category_array}), ${bot_category_var})\n    AND $__conditionalAll(arrayExists(x -> x IN (${Bot_Id_var:sqlstring}), ${Bot_Id_array}), ${Bot_Id_var})\n    AND $__adHocFilter() \n)\nSELECT \n  BotCategoryAkamai, \n  bot_category,  \n  toStartOfInterval(toDateTime(timestamp), ${interval}) as time,  \n  count(*) \nFROM cte\nARRAY JOIN BotCategoryAkamai_array AS BotCategoryAkamai, bot_category_array AS bot_category\nGROUP BY BotCategoryAkamai, bot_category, time ORDER BY count() DESC\n"
    }
   ]
  }
 ]
}