{
 "title": "CDN Observability",
 "tags": [
  "Required tables: summary_hour/summary_sampled_day",
  "v1.1.1"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "duration",
    "query": "SELECT datediff('h', $__fromTime, $__toTime)"
   },
   {
    "name": "table",
    "query": "SELECT CASE\nWHEN ${duration} < 6 THEN '${ds2}'\nWHEN ${duration} >= 6 AND ${duration} < 72 THEN '${summary_hour}'\nWHEN ${duration} >= 72 THEN '${summary_day}'\nEND"
   },
   { "name": "timestamp", "query": "reqTimeSec" },
   {
    "name": "summary_hour",
    "query": "__PROJECT_NAME__.__SUMMARY_TABLE_NAME_1__"
   },
   { "name": "summary_day", "query": "${VAR_SUMMARY_DAY}" },
   { "name": "ds2", "query": "${VAR_DS2}" },
   { "name": "filter" },
   {
    "name": "uniq_cliIP_var",
    "query": "SELECT  \nIF('${table}' = '${ds2}', 'uniq (cliIP)', 'uniq_client_ip')"
   },
   {
    "name": "uniq_session_var",
    "query": "SELECT  \nIF('${table}' = '${ds2}', 'uniq (cliIP, UA)', 'uniq_session')"
   },
   {
    "name": "cnt_all_var",
    "query": "SELECT IF('${table}' = '${ds2}', 'count(*)', 'cnt_all')"
   },
   {
    "name": "cnt_originHits_var",
    "query": "SELECT IF('${table}' = '${ds2}', 'countIf (cacheStatus = 0)', 'cnt_originHits')\n"
   },
   {
    "name": "cnt_edgeHits_var",
    "query": "SELECT IF('${table}' = '${ds2}', 'countIf (cacheStatus = 1)', 'cnt_edgeHits')"
   },
   {
    "name": "cnt_errorHits_var",
    "query": "SELECT IF('${table}' = '${ds2}', 'countIf (statusCode > 400)', 'cnt_errorHits')"
   },
   {
    "name": "pct_errorRate_var",
    "query": "SELECT IF('${table}' = '${ds2}', '${cnt_errorHits_var} / count() * 100', 'pct_errorRate') "
   },
   {
    "name": "pct_offLoadBytes_var",
    "query": "SELECT IF('${table}' = '${ds2}', '${sum_BytesEdge_var} / ${sum_totalBytes_var} * 100', 'pct_offLoadBytes')\n"
   },
   {
    "name": "pct_offLoadHit_var",
    "query": "SELECT IF('${table}' = '${ds2}', '${cnt_edgeHits_var} / count() * 100 ', 'pct_offLoadHit')"
   },
   {
    "name": "sum_BytesOrigin_var",
    "query": "SELECT IF('${table}' = '${ds2}', 'sumIf (totalBytes, cacheStatus = 0)', 'sum_BytesOrigin')"
   },
   {
    "name": "sum_BytesEdge_var",
    "query": "SELECT IF('${table}' = '${ds2}', 'sumIf (totalBytes, cacheStatus = 1)', 'sum_BytesEdge')"
   },
   {
    "name": "sum_totalBytes_var",
    "query": "SELECT IF('${table}' = '${ds2}', 'sum(totalBytes)', 'sum_totalBytes')"
   },
   {
    "name": "quantiles_turnAroundTimeMSec_var",
    "query": "SELECT IF('${table}' = '${ds2}', 'quantiles (0.25, 0.5, 0.75, 0.9, 0.95, 0.99) (turnAroundTimeMSec)', 'quantiles_turnAroundTimeMSec')"
   },
   {
    "name": "quantiles_transferTimeMSec_var",
    "query": "SELECT IF('${table}' = '${ds2}', 'quantiles (0.25, 0.5, 0.75, 0.9, 0.95, 0.99) (transferTimeMSec)', 'quantiles_transferTimeMSec')"
   },
   {
    "name": "quantiles_downloadTimeMSec_var",
    "query": "SELECT IF('${table}' = '${ds2}', 'quantiles (0.25, 0.5, 0.75, 0.9, 0.95, 0.99) (downloadTime)', 'quantiles_downloadTimeMSec')"
   },
   {
    "name": "quantiles_timeToFirstByteMSec_var",
    "query": "SELECT IF('${table}' = '${ds2}', 'quantiles (0.25, 0.5, 0.75, 0.9, 0.95, 0.99) (timeToFirstByte)', 'quantiles_timeToFirstByteMSec')"
   },
   {
    "name": "sampledFields_banner",
    "query": "SELECT IF('${table}' = '${summary_day}', 'Please note: \nDue to the current time range selection (>= 3 days), the fields asn, cliIP, referer, reqPath and UA have been sampled.', 'CDN Observability\nReports on a standard set of CDN observability metrics, including offload, CHR and region analysis.')"
   },
   {
    "name": "cnt_1xx_status_code",
    "query": "SELECT \n  IF('${table}' = '${ds2}', \n     'countIf(statusCode >= 100 AND statusCode < 200)', \n     'countMergeIf(`count()`, statusCode >= 100 AND statusCode < 200)')"
   },
   {
    "name": "cnt_2xx_status_code",
    "query": "SELECT \n  IF('${table}' = '${ds2}', \n     'countIf(statusCode >= 200 AND statusCode < 300)', \n     'countMergeIf(`count()`, statusCode >= 200 AND statusCode < 300)')"
   },
   {
    "name": "cnt_3xx_status_code",
    "query": "SELECT\n  IF('${table}' = '${ds2}',\n     'countIf(statusCode >= 300 AND statusCode < 400)',\n     'countMergeIf(`count()`, statusCode >= 300 AND statusCode < 400)')"
   },
   {
    "name": "cnt_4xx_status_code",
    "query": "SELECT\n  IF('${table}' = '${ds2}',\n     'countIf(statusCode >= 400 AND statusCode < 500)',\n     'countMergeIf(`count()`, statusCode >= 400 AND statusCode < 500)')"
   },
   {
    "name": "cnt_5xx_status_code",
    "query": "SELECT\n  IF('${table}' = '${ds2}',\n     'countIf(statusCode >= 500 AND statusCode < 600)',\n     'countMergeIf(`count()`, statusCode >= 500 AND statusCode < 600)')"
   },
   {
    "name": "raw_table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "#### ${sampledFields_banner}" } },
  {
   "title": "Hits per Status Code",
   "type": "timeseries",
   "description": "Number of requests grouped by HTTP Status Code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT toString(statusCode) as HTTP_Status_Code, $__timeInterval($timestamp) as time, ${cnt_all_var} as http\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nGROUP BY HTTP_Status_Code, time \nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Hits per status code; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Distribution of Status Codes",
   "type": "piechart",
   "description": "Percentage share of each HTTP status code",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT ${cnt_all_var} as count, toString(statusCode) as HTTP_Status_Code\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nGROUP BY HTTP_Status_Code \nORDER BY count DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=HTTP Status Code Distribution; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Hits per Status Code Class",
   "type": "timeseries",
   "description": "Number of requests grouped by HTTP Status Code Class",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n${cnt_1xx_status_code} AS \"1xx Status Codes\", \n${cnt_2xx_status_code} AS \"2xx Status Codes\", \n${cnt_3xx_status_code} AS \"3xx Status Codes\", \n${cnt_4xx_status_code} AS \"4xx Status Codes\", \n${cnt_5xx_status_code} AS \"5xx Status Codes\", \n$__timeInterval($timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nGROUP BY time \nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Hits per Status Code Class; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "HTTP Error Rate",
   "type": "timeseries",
   "description": "Count of all requests with HTTP Status Code > 400 divided by total count of requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT ${pct_errorRate_var} as errorRate, $__timeInterval(${timestamp}) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nGROUP BY time \nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=HTTP Error Rate; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Bytes Delivered",
   "type": "timeseries",
   "description": "Sum of Total Bytes Delivered",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT ${sum_BytesEdge_var} as \"Edge\", ${sum_BytesOrigin_var} as \"Origin\", $__timeInterval($timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nGROUP BY time \nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Bytes Delivered; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Offload Bytes",
   "type": "timeseries",
   "description": "Cache Hit Ratio :\nSum of all request bytes with cacheStatus: 1 / divided by total bytes of request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT ${pct_offLoadBytes_var} as offloadBytes, $__timeInterval($timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nGROUP BY time \nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Offload Bytes; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "timeseries",
   "description": "Edge Hits vs Origin Hits",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT ${cnt_edgeHits_var} as \"Edge\", ${cnt_originHits_var} as \"Origin\", $__timeInterval($timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Hits; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "description": "Cache Hit Ratio :\nSum of all requests with cacheStatus: 1 / divided by total count of requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT ${pct_offLoadHit_var} as offloadHit, $__timeInterval($timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nGROUP BY time \nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Cache Hit Ratio; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Unique ClientIP and Session",
   "type": "timeseries",
   "description": "Count Unique Client IP and session is a hash value between Client IP and UA",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT ${uniq_cliIP_var} AS unique_cliIP, ${uniq_session_var} AS unique_session, $__timeInterval($timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nGROUP BY time\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Uniq ClientIP and Session; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Summary Table per Country",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT country, ${uniq_session_var}, ${cnt_all_var} as \"Edge Hit\", ${pct_offLoadHit_var} as \"Offload Hit\", ${sum_totalBytes_var} as \"Total Bytes\", ${pct_offLoadBytes_var} as \"Offload Bytes\", ${pct_errorRate_var} as \"Error Rate\"\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nGROUP BY country \nORDER BY \"Edge Hit\" DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Summary Table per Country; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Summary Table per Country",
   "type": "geomap",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "SELECT ${cnt_all_var} as \"Edge Hit\", ${pct_offLoadHit_var} as \"Offload Hit\", ${sum_totalBytes_var} as \"Total Bytes\", ${pct_offLoadBytes_var} as \"Offload Bytes\", ${pct_errorRate_var} as \"Error Rate\", ${uniq_session_var}, country\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nGROUP BY country \nORDER BY \"Edge Hit\" DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Summary Table per Country; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Summary Table per CPCode",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "rawSql": "SELECT cp as \"CP Code\", ${uniq_session_var}, ${cnt_all_var} as \"Edge Hit\", ${pct_offLoadHit_var} as \"Offload Hit\", ${sum_totalBytes_var} as \"Total Bytes\", ${pct_offLoadBytes_var} as \"Offload Bytes\", ${pct_errorRate_var} as \"Error Rate\"\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nGROUP BY cp \nORDER BY \"Edge Hit\" DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Summary Table per CPCode; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Request Per Content Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT rspContentType as item, ${cnt_all_var} as count\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nGROUP BY item \nORDER BY count DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Request Per Content Type; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 50 User Agent",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT ${cnt_all_var} as count, UA, REPLACE(UA, ',', '__gfc__') AS escaped_UA\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nAND UA NOT IN '~~~SAMPLED_OUT~~~'\nGROUP BY UA\nORDER BY count DESC\nLIMIT 50\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 50 User Agent; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 50 Request Path",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "rawSql": "SELECT ${cnt_all_var} as count, reqPath as RequestPath\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nAND RequestPath NOT IN '~~~SAMPLED_OUT~~~'\nGROUP BY RequestPath\nORDER BY count DESC\nLIMIT 50\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 50 Request Path; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 50 Client IP",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "rawSql": "SELECT ${cnt_all_var} as count, cliIP as ClientIP\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n AND $__adHocFilter() \n AND ClientIP NOT IN '~~~SAMPLED_OUT~~~'\nGROUP BY ClientIP\nORDER BY count DESC\nLIMIT 50\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 50 Client IP; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Edge TransferTime",
   "type": "timeseries",
   "description": "The time in milliseconds from when the edge server is ready to send the first byte of the response to when the last byte reaches the kernel.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT ${quantiles_transferTimeMSec_var}[1] as \"25th\", ${quantiles_transferTimeMSec_var}[2] as \"50th\", ${quantiles_transferTimeMSec_var}[3] as \"75th\", ${quantiles_transferTimeMSec_var}[4] as \"90th\", ${quantiles_transferTimeMSec_var}[5] as \"95th\", ${quantiles_transferTimeMSec_var}[6] as \"99th\", $__timeInterval($timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nGROUP BY time \nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Edge TransferTime; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Edge Turn Around Time",
   "type": "timeseries",
   "description": "The time in milliseconds from when the edge server receives the last byte of the request to when it sends the first bytes of the response.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT ${quantiles_turnAroundTimeMSec_var}[1] as \"25th\", ${quantiles_turnAroundTimeMSec_var}[2] as \"50th\", ${quantiles_turnAroundTimeMSec_var}[3] as \"75th\", ${quantiles_turnAroundTimeMSec_var}[4] as \"90th\", ${quantiles_turnAroundTimeMSec_var}[5] as \"95th\", ${quantiles_turnAroundTimeMSec_var}[6] as \"99th\", $__timeInterval($timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nGROUP BY time \nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Edge Turn Around Time; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Download Time",
   "type": "timeseries",
   "description": "The time taken to download the object in milliseconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT ${quantiles_downloadTimeMSec_var}[1] as \"25th\", ${quantiles_downloadTimeMSec_var}[2] as \"50th\", ${quantiles_downloadTimeMSec_var}[3] as \"75th\", ${quantiles_downloadTimeMSec_var}[4] as \"90th\", ${quantiles_downloadTimeMSec_var}[5] as \"95th\", ${quantiles_downloadTimeMSec_var}[6] as \"99th\", $__timeInterval($timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nGROUP BY time \nORDER BY time ASC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Download Time; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Time To First Byte",
   "type": "timeseries",
   "description": "The time taken to download the first byte of the received content in milliseconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT ${quantiles_timeToFirstByteMSec_var}[1] as \"25th\", ${quantiles_timeToFirstByteMSec_var}[2] as \"50th\", ${quantiles_timeToFirstByteMSec_var}[3] as \"75th\", ${quantiles_timeToFirstByteMSec_var}[4] as \"90th\", ${quantiles_timeToFirstByteMSec_var}[5] as \"95th\", ${quantiles_timeToFirstByteMSec_var}[6] as \"99th\", $__timeInterval($timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nGROUP BY time \nORDER BY time ASC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Time To First Byte; du=${__user.login}'"
    }
   ]
  }
 ]
}