{
 "title": "TrafficPeak Usage Report",
 "description": "Report on Ingest data",
 "tags": [ "v1.1.1" ],
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "SELECT concat(project,'.',name) as table FROM (SELECT DISTINCT database as project, splitByChar('#',table)[1] as name FROM system.tables WHERE engine = 'TurbineStorage' AND (project != 'sample_project'  AND project != 'hdx' AND project != 'hydro' AND primary_key not ilike '%toStartOf%'))"
   },
   {
    "name": "catalog_union",
    "query": "SELECT arrayStringConcat(\n    groupArray(\n        concat('SELECT index_size, manifest_size, data_size, raw_size, rows, min_timestamp FROM ', splitByChar('.', t)[1], '.`', splitByChar('.', t)[2], '#.catalog` WHERE $__timeFilter(min_timestamp)')\n    ),\n    ' UNION ALL '\n)\nFROM (\n    SELECT arrayJoin(splitByChar(',', '${table:csv}')) AS t\n)\n"
   },
   {
    "name": "raw_table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "#### TrafficPeak Usage Report\nProvides statistics on log data ingested into TrafficPeak."
   }
  },
  {
   "title": "Total Number of logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    sum(rows) as logs\n    FROM (\n    ${catalog_union}\n    )\n    WHERE $__timeFilter(min_timestamp)\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Total Number of logs; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Bytes per Log line",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    sum(raw_size)/sum(rows) as incoming_data\n    FROM (\n     ${catalog_union}\n    )\n    WHERE $__timeFilter(min_timestamp)\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Bytes per Log line; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Raw Data Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    sum(raw_size) as incoming_data\n    FROM (\n        ${catalog_union}\n        )\n    WHERE $__timeFilter(min_timestamp)\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Raw Data Size; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Data Footprint in Trafficpeak",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    sum(index_size + manifest_size + data_size) as trafficpeak_size\n    FROM (\n        ${catalog_union}\n    )\n    WHERE $__timeFilter(min_timestamp)\n    SETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Data Footprint in Trafficpeak; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Compression Ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    sum(raw_size)/sum(index_size + manifest_size + data_size) as compression_ratio  \n    FROM (\n        ${catalog_union}\n    )\n    WHERE $__timeFilter(min_timestamp)\n    SETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Compression Ratio in Trafficpeak; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Compression Savings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    1-(sum(index_size + manifest_size + data_size)/sum(raw_size)) as compression_savings\n    FROM (\n        ${catalog_union}\n    )\n    WHERE $__timeFilter(min_timestamp)\n    SETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Compression Ratio in Trafficpeak; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Total Number of partitions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(rows) AS partitions\nFROM (\n  ${catalog_union}\n)\nWHERE $__timeFilter(min_timestamp)\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Total Number of partitions; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Number of logs per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfDay(min_timestamp) as time,\n    sum(rows) as logs\n    FROM (\n         ${catalog_union}\n    )\n    WHERE $__timeFilter(min_timestamp)\n    GROUP BY time\n    ORDER BY time DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Number of logs per day; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Data Size per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfDay(min_timestamp) as time,\n    sum(index_size + manifest_size + data_size) as trafficpeak_size,\n    sum(raw_size) as raw_data\n    FROM (\n         ${catalog_union}\n    )\n    WHERE $__timeFilter(min_timestamp)\n    GROUP BY time\n    ORDER BY time DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Data Size per day; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Usage Report",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfDay(min_timestamp) as day,\n    sum(rows) as logs,\n    sum(index_size + manifest_size + data_size) as trafficpeak_size,\n    sum(raw_size) as raw_data\n    FROM (\n         ${catalog_union}\n    )\n    WHERE $__timeFilter(min_timestamp)\n    GROUP BY day\n    ORDER BY day DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Usage Report; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Number of Partitions per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfDay(min_timestamp) as day,\n    sum(rows) as logs,\n    sum(index_size + manifest_size + data_size) as trafficpeak_size,\n    sum(raw_size) as raw_data\n    FROM (\n         ${catalog_union}\n    )\n    WHERE $__timeFilter(min_timestamp)\n    GROUP BY day\n    ORDER BY day DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Usage Report; du=${__user.login}'"
    }
   ]
  }
 ]
}