{
 "title": "EAA Connector Health",
 "description": "testing",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   },
   { "name": "filter" },
   { "name": "timestamp", "query": "datetime" },
   { "name": "generalescaping", "query": "${VAR_GENERALESCAPING}" },
   { "name": "querieslimit", "query": "${VAR_QUERIESLIMIT}" },
   { "name": "commonlibraries", "query": "${VAR_COMMONLIBRARIES}" },
   { "name": "connhealth_det", "label": "connhealth_det", "query": "${VAR_CONNHEALTH_DET}" },
   {
    "name": "raw_table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   }
  ]
 },
 "panels": [
  {
   "title": "EAA Connector Health",
   "type": "canvas",
   "description": "Health metrics (CPU, memory, disk, and dialout activity)",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(datetime) AS d\n  FROM ${table}\n  WHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \n\nGROUP BY  d\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Users per APP; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Connectors",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    t.1 AS name,\n    t.2 AS version,\n    t.3 AS osVersion,\n    t.4 AS privateip,\n    t.5 AS publicip,\n    t.6 AS reachable,\n    t.7 AS last_update\nFROM (\n    SELECT argMax(tuple(name, version, osVersion, privateip, publicip, reachable, lastUpdate), lastUpdate) AS t\n    FROM ${table}\n    WHERE $__timeFilter(datetime)\n      AND ${generalescaping}\n      AND $__adHocFilter()\n    GROUP BY name\n) sub\nORDER BY name ASC\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Connectors; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "Tops for connectors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 25 connectors by CPU",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT       \n        anyLast(cpu) AS last_cpu,\n        name,\n        concat('', ' (avg:', toString(round(avg(cpu), 2)), ')') AS avg\n     FROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \nGROUP BY name\nORDER BY last_cpu DESC\nLIMIT 25\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 25 connectors by CPU; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top 25 connectors by memory",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT       \n        anyLast(mem) AS last_mem,\n        name,\n        concat('', ' (avg:', toString(round(avg(cpu), 2)), ')') AS avg\n     FROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \nGROUP BY name\nORDER BY last_mem DESC\nLIMIT 25\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 25 connectors by memory; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top 25 connectors by disk",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT       \n        anyLast(disk) AS last_disk,\n        name,\n        concat('', ' (avg:', toString(round(avg(cpu), 2)), ')') AS avg\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \nGROUP BY name\nORDER BY last_disk DESC\nLIMIT 25\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 25 connectors by disk; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top 25 connectors by active dialouts",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT       \n        anyLast(dialoutActive) AS last_dialouts,\n        name,\n        concat('', ' (avg:', toString(round(avg(dialoutActive), 0)), ')') AS avg\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \nGROUP BY name\nORDER BY last_dialouts DESC\nLIMIT 25\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 25 connectors by active dialouts; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Bottom for connectors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bottom 25 connectors by CPU",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT       \n        anyLast(cpu) AS last_cpu,\n        name,\n        concat('', ' (avg:', toString(round(avg(cpu), 2)), ')') AS avg\n     FROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \nGROUP BY name\nORDER BY last_cpu ASC\nLIMIT 25\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Bottom 25 connectors by CPU; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Bottom 25 connectors by memory",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT       \n        anyLast(mem) AS last_mem,\n        name,\n        concat('', ' (avg:', toString(round(avg(cpu), 2)), ')') AS avg\n     FROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \nGROUP BY name\nORDER BY last_mem ASC\nLIMIT 25\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Bottom 25 connectors by memory; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Bottom 25 connectors by disk",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT       \n        anyLast(disk) AS last_disk,\n        name,\n        concat('', ' (avg:', toString(round(avg(cpu), 2)), ')') AS avg\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \nGROUP BY name\nORDER BY last_disk ASC\nLIMIT 25\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Bottom 25 connectors by disk; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Bottom 25 connectors by active dialouts",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT       \n        anyLast(dialoutActive) AS last_dialouts,\n        name,\n        concat('', ' (avg:', toString(round(avg(dialoutActive), 0)), ')') AS avg\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \nGROUP BY name\nHAVING last_dialouts IS NOT NULL\nORDER BY last_dialouts ASC\nLIMIT 25\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Bottom 25 connectors by active dialouts; du=${__user.login}'"
      }
     ]
    }
   ]
  }
 ]
}