{
 "title": "EAA Origins Observability",
 "description": "testing",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   },
   { "name": "device_table", "query": "${VAR_DEVICE_TABLE}" },
   { "name": "filter" },
   { "name": "timestamp", "query": "datetime" },
   { "name": "generalescaping", "query": "${VAR_GENERALESCAPING}" },
   { "name": "querieslimit", "query": "${VAR_QUERIESLIMIT}" },
   { "name": "commonlibraries", "query": "${VAR_COMMONLIBRARIES}" },
   {
    "name": "raw_table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   }
  ]
 },
 "panels": [
  {
   "title": "Origins Observability",
   "type": "canvas",
   "description": "To run this dashboard, start from Usage Stats, selecting the desired EAA_APP.",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(datetime) AS d,\n  uniq(username) as \"Total_Username\",\n  uniq(origin) as \"Total_Origin\",\n  uniq(apphost) as \"Total_EAA_APPS\",\n  uniq(cloudZone) as \"Total_cloudZone\",\n  SUM(bytesIn) \"Incoming\",\n  SUM(bytesOut) \"Outgoing\",\n  uniq(conUuid) as \"Total_Connectors\"\n  FROM ${table}\n  WHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \n  AND origin != '-'\n  AND username != '-'\n  AND apphost != '-'\n  and conUuid != '-'  \nGROUP BY  d\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Users per APP; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "LAST 30 MINS Analysis for EAA Destinations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Connected users",
   "type": "stat",
   "description": "This indicator shows the current logged in users for the last 30 Minutes, and the trend over the 30 minutes before. \n\nUp Arrow: Positive Trend\nDown Arrow: Negative Trend",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    uniq(username) AS Total_Username,\n    d\nFROM (\n    SELECT\n        username,\n        CASE\n            WHEN datetime >= now() - INTERVAL 45 MINUTE\n             AND datetime <  now() - INTERVAL 15 MINUTE\n                THEN toStartOfMinute(now() - INTERVAL 15 MINUTE)\n            WHEN datetime >= now() - INTERVAL 75 MINUTE\n             AND datetime <  now() - INTERVAL 45 MINUTE\n                THEN toStartOfMinute(now() - INTERVAL 45 MINUTE)\n        END AS d\n    FROM ${table}\n    WHERE datetime >= now() - INTERVAL 75 MINUTE\n      AND username != '-'\n      AND origin != '-'\n      AND ${generalescaping}\n      AND $__adHocFilter()\n) t\nWHERE d IS NOT NULL\nGROUP BY d\nORDER BY d ASC\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Connected users; du=${__user.login}';"
    }
   ]
  },
  {
   "title": "EAA_Apphost",
   "type": "stat",
   "description": "This indicator shows the current logged in users for the last 30 Minutes, and the trend over the 30 minutes before. \n\nUp Arrow: Positive Trend\nDown Arrow: Negative Trend",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    uniq(apphost) AS Total_Apphost,\n    d\nFROM (\n    SELECT\n        apphost,\n        CASE\n            WHEN datetime >= now() - INTERVAL 45 MINUTE\n             AND datetime <  now() - INTERVAL 15 MINUTE\n                THEN toStartOfMinute(now() - INTERVAL 15 MINUTE)\n            WHEN datetime >= now() - INTERVAL 75 MINUTE\n             AND datetime <  now() - INTERVAL 45 MINUTE\n                THEN toStartOfMinute(now() - INTERVAL 45 MINUTE)\n        END AS d\n    FROM ${table}\n    WHERE datetime >= now() - INTERVAL 75 MINUTE\n      AND username != '-'\n      AND origin != '-'\n      AND ${generalescaping}\n      AND $__adHocFilter()\n) t\nWHERE d IS NOT NULL\nGROUP BY d\nORDER BY d ASC\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=EAA_Apphost; du=${__user.login}';\n"
    }
   ]
  },
  {
   "title": "Last ${querieslimit} connected users",
   "type": "table",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT origin, username, maxOrNull(datetime) AS Last_Access FROM ${table}\nWHERE datetime > NOW() - INTERVAL 30 MINUTE\nAND ${generalescaping}\nAND $__adHocFilter() \nAND origin != '-'\nAND username != '-'\nGROUP BY origin, username\nORDER BY Last_Access DESC\nLIMIT ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last ${querieslimit} connected users; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "Bandwidth usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT sum(bytesIn)*8/60 as Incoming, sum(bytesOut)*8/60 AS Outgoing, \ntoStartOfInterval(datetime, INTERVAL 60 SECOND) AS d\nFROM ${table} \nWHERE datetime >= now() - INTERVAL 30 MINUTE\nAND ${generalescaping}\nAND $__adHocFilter()\nAND origin != '-'\nAND username != '-'\nGROUP BY d\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Bandwidth Usage; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Tops for destination",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 username by hits",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  username, count() as Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \n  AND origin != '-'\nGROUP BY username\nORDER BY Total DESC\nLIMIT 5\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 5 username by hits; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top 5 cloudzone by hits",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  cloudZone, count() as Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \n  AND origin != '-'\nGROUP BY cloudZone\nORDER BY Total DESC\nLIMIT 5\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 5 cloudzone by hits; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top 5 connectors by hits",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  conUuid, count() as Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \n  AND origin != '-'\nGROUP BY conUuid\nORDER BY Total DESC\nLIMIT 5\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 5 connectors by hits; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Response time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "\nSELECT\n  $__timeInterval(datetime) AS d,\n  avg(originRespTime) as \"Origin_Response_Time\",\n  avg(connectorRespTime) as \"Connector_Response_Time\",\n  avg(totalRespTime) as \"Total_Response_Time\"\n  FROM ${table}\n  WHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND origin != '-'\n  AND username != '-'\n  AND apphost != '-'\n  and conUuid != '-' \n  and totalRespTime is not null\n  and connectorRespTime is not null\n  and originRespTime is not null\nGROUP BY  d --, connectorRespTime, originRespTime, totalRespTime\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Response time; du=${__user.login}'\n \n \n "
      }
     ]
    }
   ]
  },
  {
   "title": "Users to Destination Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Recent User locations",
     "type": "geomap",
     "gridPos": { "h": 19, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT geoCountrycode, geoCountry, uniq(username) as Total_users\nFROM ${table}\nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND origin != '-'\nAND username != '-'\nGROUP BY geoCountrycode, geoCountry\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Recent User locations; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Recent ${querieslimit} users",
     "type": "table",
     "description": "Number of users accessing the selected Destination.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT origin, username, maxOrNull(datetime) as Last_Access FROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND origin != '-'\nAND username != '-'\ngroup by origin, username \n\norder by Last_Access desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Recent ${querieslimit} users; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "User Access Load Trend",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "targets": [
      { "panelId": 906 }
     ]
    }
   ]
  },
  {
   "title": "EAA Application serving the Destination",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "EAA Apps per Destination",
     "type": "timeseries",
     "description": "Number of EAA Application that contains the selected Destination",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 295 },
     "targets": [
      { "panelId": 906 }
     ]
    },
    {
     "title": "Top ${querieslimit}  EAA App per Destination",
     "type": "table",
     "description": "Top EAA Application serving the selected destination",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 295 },
     "targets": [
      {
       "rawSql": "SELECT origin, apphost,\n       maxOrNull(datetime) AS Last_Access\nFROM ${table}\nWHERE $__timeFilter(datetime)\nAND ${generalescaping}\nAND $__adHocFilter() \nAND origin != '-'\nAND apphost !='-'\nGROUP BY origin, apphost\nORDER BY Last_Access DESC\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit}  EAA App per Destination; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Connectors serving the Destination",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connectors to Destination",
     "type": "timeseries",
     "description": "Number of EAA Application that contains the selected Destination",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
     "targets": [
      { "panelId": 906 }
     ]
    },
    {
     "title": "Top ${querieslimit} connectors to destination",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
     "targets": [
      {
       "rawSql": "SELECT origin, conUuid, maxOrNull(datetime) as Last_Access FROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND origin != '-'\nAND conUuid != '-'\ngroup by origin, conUuid \norder by Last_Access desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} connectors to destination; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Cloudzone & GEOs accessing the Destination",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cloudzones per Destination",
     "type": "timeseries",
     "description": "Shows the cloudzones that are serving the selected Destination",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 297 },
     "targets": [
      { "panelId": 906 }
     ]
    },
    {
     "title": "Top ${querieslimit} cloudzones per Destination",
     "type": "table",
     "description": "This table shows the cloudzones configured for the selected app.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 307 },
     "targets": [
      {
       "rawSql": "SELECT origin, cloudZone, maxOrNull(datetime) as Last_Access\nFROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND origin != '-'\nGROUP BY origin, cloudZone\nORDER BY Last_Access DESC\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} cloudzones per Destination; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} user Geographies",
     "type": "table",
     "description": "This table shows the top Geographies when the application has been accessed",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 307 },
     "targets": [
      {
       "rawSql": "SELECT origin, geoCity, geoCountry, maxOrNull(datetime) as Last_Access\nFROM ${table} \nWHERE $__timeFilter(datetime)\nAND ${generalescaping}\nAND $__adHocFilter() \nAND origin != '-'\ngroup by origin, geoCity, geoCountry\norder by Last_Access desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} user Geographies; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic metrics for the Destination",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic load per Destination",
     "type": "timeseries",
     "description": "This table shows the amount of Data exchanged by the selected destination.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 129 },
     "targets": [
      { "panelId": 906 }
     ]
    },
    {
     "title": "Top ${querieslimit} active users",
     "type": "table",
     "description": "This table shows the most active users on this Destination",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 196 },
     "targets": [
      {
       "rawSql": "SELECT sum(bytesIn) Incoming, sum(bytesOut) Outgoing, toDate(datetime) as Date, \norigin, username FROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND username != '-'\nAND origin != '-'\nGROUP BY Date, origin, username \norder by Date DESC\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} active users; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} traffic per Destination",
     "type": "table",
     "description": "This table shows the traffic split for each Destination configured in the selected app.\n",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 196 },
     "targets": [
      {
       "rawSql": "SELECT sum(bytesIn) Incoming, sum(bytesOut) Outgoing, toDate(datetime) as Date, \norigin, apphost FROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND apphost != '-'\nAND origin != '-'\nGROUP BY Date, origin, apphost \norder by Date desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} traffic per Destination; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status codes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 14, "x": 0, "y": 130 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeInterval(datetime) AS time,\n    statusCode,\n    count(*) AS \"Total\"\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY time, statusCode\nORDER BY time ASC, statusCode\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Status codes; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Status codes",
     "type": "table",
     "gridPos": { "h": 11, "w": 10, "x": 14, "y": 130 },
     "targets": [
      {
       "rawSql": "SELECT\n    toString(statusCode) AS statusCode,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  statusCode\nORDER BY Total desc\nlimit 100\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Status codes; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Error codes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 14, "x": 0, "y": 174 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeInterval(datetime) AS time,\n    errorCode,\n    count(*) AS \"Total\"\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY time, errorCode\nORDER BY time ASC, errorCode\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Error codes; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Error codes",
     "type": "table",
     "gridPos": { "h": 11, "w": 10, "x": 14, "y": 174 },
     "targets": [
      {
       "rawSql": "SELECT\n    toString(errorCode) AS errorCode,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  errorCode\nORDER BY Total desc\nlimit 100\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Error codes; du=${__user.login}';\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Request specs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top ${querieslimit} device OS",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 300 },
     "targets": [
      {
       "rawSql": "SELECT\n    deviceOs,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  deviceOs\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} device OS; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} device type",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 300 },
     "targets": [
      {
       "rawSql": "SELECT\n    deviceType,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  deviceType\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} device type; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} user agent",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 311 },
     "targets": [
      {
       "rawSql": "SELECT\n    userAgent,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  userAgent\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} user agent; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} client process",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 311 },
     "targets": [
      {
       "rawSql": "SELECT\n    clientProcess,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  clientProcess\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} client process; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} client IP",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 322 },
     "targets": [
      {
       "rawSql": "SELECT\n    clientip,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  clientip\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} client IP; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} session ID",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 322 },
     "targets": [
      {
       "rawSql": "SELECT\n    sessionId,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\n  AND sessionId != '-'\nGROUP BY  sessionId\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} session ID; du=${__user.login}';\n"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP specs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP method",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 14, "x": 0, "y": 132 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeInterval(datetime) AS time,\n    httpMethod,\n    count(*) AS \"Total\"\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY time, httpMethod\nORDER BY time ASC, httpMethod\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=HTTP method; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "HTTP Method",
     "type": "table",
     "gridPos": { "h": 11, "w": 10, "x": 14, "y": 132 },
     "targets": [
      {
       "rawSql": "SELECT\n    httpMethod,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  httpMethod\nORDER BY Total desc\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=HTTP method; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} URL Path",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 143 },
     "targets": [
      {
       "rawSql": "SELECT\n    urlPath,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  urlPath\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} URL Path; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} referer",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 143 },
     "targets": [
      {
       "rawSql": "SELECT\n    referer,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  referer\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} referer; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} content type",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 154 },
     "targets": [
      {
       "rawSql": "SELECT\n    contentType,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  contentType\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} content type; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} HTTP version",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 154 },
     "targets": [
      {
       "rawSql": "SELECT\n    httpVer,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  httpVer\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} HTTP version; du=${__user.login}';\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Destination Access details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last ${querieslimit} access logs ",
     "type": "table",
     "description": "This table shows the access log for the selected Destination",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 262 },
     "targets": [
      {
       "rawSql": "SELECT datetime, \n       origin,\n       apphost,\n       username, \n       clientip, \n       cloudZone, \n       geoCountry, \n       geoCity, \n       originRespTime, \n       totalRespTime, \n       errorCode,\n       httpMethod,\n       httpVerb2,\n       idpinfo,\n       referer,\n       sessionId,\n       sessionInfo,\n       statusCode,\n       urlPath,\n       userAgent,\n\n       IF(clientId != '-', 'tunnel', 'application') AS application_type, \n       clientId\nFROM ${table}\nWHERE $__timeFilter(datetime)\nAND ${generalescaping}\nAND $__adHocFilter() \n\nAND apphost != '-'\nAND origin != '-'\nAND username != '-'\n\nORDER BY datetime DESC\nLIMIT ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last ${querieslimit} access logs ; du=${__user.login}'\n"
      }
     ]
    }
   ]
  }
 ]
}