folders:
  hdx-main-folder:
    name: TrafficPeak Certified Reference Dashboards
    children:
      hdx-security-folder:
        name: Security
dashboards:
  hdx-network-monitoring-dashboard-synthetics:
    dashboard:
      __extend__: dashboards/network_monitoring_dashboard_synthetics.json
    folderUid: hdx-security-folder
    inputs:
      DS_HYDROLIX-HYDROLIX-DATASOURCE: hdx-hydrolix-datasource
      VAR_TIMESTAMP: startTime
      VAR_APICONTEXT_SAMPLED_DAY: __PROJECT_NAME__.__APICONTEXT_SAMPLED_DAY__
      VAR_LOGS: akamai.apicontext
      VAR_SIEM: __PROJECT_NAME__.__SIEM_TABLE_NAME__
  hdx-api-observability:
    dashboard:
      __extend__: dashboards/api_observability.json
    folderUid: hdx-security-folder
    inputs:
      DS_HYDROLIX-HYDROLIX-DATASOURCE: hdx-hydrolix-datasource
      VAR_TIMESTAMP: startTime
      VAR_APICONTEXT_SAMPLED_DAY: __PROJECT_NAME__.__APICONTEXT_SAMPLED_DAY__
      VAR_LOGS: akamai.apicontext
      VAR_SIEM: __PROJECT_NAME__.__SIEM_TABLE_NAME__
