SELECT toStartOfMinute(reqTimeSec) as timestamp_min,
statusCode,
reqHost,
asn,
city,
state,
country,
cacheable,
errorCode,
reqMethod,
rspContentType,
proto,
cp,
count() as cnt_all,
countIf(cacheStatus = 0) as cnt_originHits,
countIf(cacheStatus = 1) as cnt_edgeHits,
cnt_edgeHits / count() * 100 as pct_offLoadHit,
sum(totalBytes) as sum_totalBytes,
sumIf(totalBytes, cacheStatus = 0) as sum_BytesOrigin,
sumIf(totalBytes, cacheStatus = 1) as sum_BytesEdge,
sum_BytesEdge / sum_totalBytes * 100 as pct_offLoadBytes,
countIf(statusCode > 400) as cnt_errorHits,
cnt_errorHits / count() * 100 as pct_errorRate,
uniq (cliIP) as uniq_cliIP,
uniq (cliIP, UA) as uniq_session,
quantiles (0.25, 0.5, 0.75, 0.9, 0.95, 0.99) (turnAroundTimeMSec) as quantiles_turnAroundTimeMSec,
quantiles (0.25, 0.5, 0.75, 0.9, 0.95, 0.99) (transferTimeMSec) as quantiles_transferTimeMSec,
topK (50) (cliIP) as top_50_cliIP,
topK (50) (UA) as top_50_UA,
topK (50) (reqPath) as top_50_reqPath
FROM __PROJECT_NAME__.__TABLE_NAME__
GROUP BY
timestamp_min,
statusCode,
reqHost,
asn,
city,
state,
country,
cacheable,
errorCode,
reqMethod,
rspContentType,
proto,
cp
SETTINGS hdx_primary_key = 'timestamp_min'
