SELECT
    datediff('s', reqTimeSec, now64(3)) AS hdx_source_latency,
    decodeURLComponent(assumeNotNull(UA)) AS UA,
    decodeURLComponent(assumeNotNull(referer)) AS referer,
    decodeURLComponent(assumeNotNull(queryStr)) AS queryStr,
    extract(decodeURLComponent(assumeNotNull(breadcrumbs)), '\/\/BC\/(\S*)') AS breadcrumbs,
    akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=g[^]]*\])', 'a=([^,\]]+)') AS Edge_IP,
    akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=g[^]]*\])', 'b=([^,\]]+)') AS Edge_RequestID,
    akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=g[^]]*\])', 'k=([^,\]]+)') AS Edge_RequestEndTime,
    akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=g[^]]*\])', 'l=([^,\]]+)') AS Edge_TurnAroundTime,
    akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=g[^]]*\])', 'm=([^,\]]+)') AS Edge_DNSLookupTime,
    akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=g[^]]*\])', 'n=([^,\]]+)') AS Edge_GeoInfo,
    akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=g[^]]*\])', 'o=([^,\]]+)') AS Edge_ASN,
    akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=o[^]]*\])', 'a=([^,\]]+)') AS Origin_IP,
    akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=o[^]]*\])', 'b=([^,\]]+)') AS Origin_RequestID,
    akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=o[^]]*\])', 'k=([^,\]]+)') AS Origin_RequestEndTime,
    akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=o[^]]*\])', 'l=([^,\]]+)') AS Origin_TurnAroundTime,
    akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=o[^]]*\])', 'm=([^,\]]+)') AS Origin_DNSLookupTime,
    akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=o[^]]*\])', 'n=([^,\]]+)') AS Origin_GeoInfo,
    akamai_breadcrumbs(breadcrumbs, '(\[[^[]*c=o[^]]*\])', 'o=([^,\]]+)') AS Origin_ASN,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=p[^]]*\])', 'a=([^,\]]+)') AS Peer_IP,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=p[^]]*\])', 'b=([^,\]]+)') AS Peer_RequestID,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=p[^]]*\])', 'k=([^,\]]+)') AS Peer_RequestEndTime,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=p[^]]*\])', 'l=([^,\]]+)') AS Peer_TurnAroundTime,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=p[^]]*\])', 'm=([^,\]]+)') AS Peer_DNSLookupTime,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=p[^]]*\])', 'n=([^,\]]+)') AS Peer_GeoInfo,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=p[^]]*\])', 'o=([^,\]]+)') AS Peer_ASN,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=c[^]]*\])', 'a=([^,\]]+)') AS Parent_IP,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=c[^]]*\])', 'b=([^,\]]+)') AS Parent_RequestID,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=c[^]]*\])', 'k=([^,\]]+)') AS Parent_RequestEndTime,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=c[^]]*\])', 'l=([^,\]]+)') AS Parent_TurnAroundTime,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=c[^]]*\])', 'm=([^,\]]+)') AS Parent_DNSLookupTime,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=c[^]]*\])', 'n=([^,\]]+)') AS Parent_GeoInfo,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=c[^]]*\])', 'o=([^,\]]+)') AS Parent_ASN,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=w[^]]*\])', 'a=([^,\]]+)') AS CloudWrapper_IP,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=w[^]]*\])', 'b=([^,\]]+)') AS CloudWrapper_RequestID,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=w[^]]*\])', 'k=([^,\]]+)') AS CloudWrapper_RequestEndTime,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=w[^]]*\])', 'l=([^,\]]+)') AS CloudWrapper_TurnAroundTime,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=w[^]]*\])', 'm=([^,\]]+)') AS CloudWrapper_DNSLookupTime,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=w[^]]*\])', 'n=([^,\]]+)') AS CloudWrapper_GeoInfo,
    akamai_breadcrumbs(breadcrumbs, '(,\[[^[]*c=w[^]]*\])', 'o=([^,\]]+)') AS CloudWrapper_ASN,
    assumeNotNull(decodeURLComponent(cmcd)) AS url_cmcd,
    concat('/', assumeNotNull(reqPath)) AS reqPath,
    if(startsWith(url_cmcd, '//x.x@U/'), substring(url_cmcd, 9), url_cmcd) AS url,
    flatten(extractAllGroupsVertical(assumeNotNull(url), '([^=,"]+)="?([^,="]+)"? ?')) AS groups,
    akamai_cmcd_query_param('bl', groups) AS cmcd_buffer_length,
    akamai_cmcd_query_param('br', groups) AS cmcd_encoded_bitrate,
    url LIKE '%,bs,%' ? 1 : 0 AS cmcd_buffer_starvation,
    akamai_cmcd_query_param('cid', groups) AS cmcd_content_id,
    akamai_cmcd_query_param('d', groups) AS cmcd_object_duration,
    akamai_cmcd_query_param('dl', groups) AS cmcd_deadline,
    akamai_cmcd_query_param('mtp', groups) AS cmcd_measured_throughput,
    akamai_cmcd_query_param('nor', groups) AS cmcd_next_object_requests,
    akamai_cmcd_query_param('nrr', groups) AS cmcd_next_range_request,
    akamai_cmcd_object_type(akamai_cmcd_query_param('ot', groups)) AS cmcd_object_type,
    akamai_cmcd_query_param('pr', groups) AS cmcd_playback_rate,
    akamai_cmcd_query_param('rtp', groups) AS cmcd_requested_max_throughput,
    akamai_cmcd_streaming_format(akamai_cmcd_query_param('sf', groups)) AS cmcd_streaming_format,
    akamai_cmcd_query_param('sid', groups) AS cmcd_session_id,
    akamai_cmcd_stream_type(akamai_cmcd_query_param('st', groups)) AS cmcd_stream_type,
    url LIKE '%,su,%' ? 1 : 0 AS cmcd_startup,
    akamai_cmcd_query_param('tb', groups) AS cmcd_top_bitrate,
    akamai_cmcd_query_param('v', groups) AS cmcd_version,
    akamai_cmcd_query_param('d', groups) AS cmcd_playback_duration,
    splitByChar(':', lower(assumeNotNull(reqHost)))[1] AS reqHost,
    position(assumeNotNull(contentProtectionInfo), 'epd') >= 1 AS epd_Match,
    splitByString('/', assumeNotNull(contentProtectionInfo))[5] AS epd_Code,
    splitByString('/', assumeNotNull(contentProtectionInfo))[6] AS epd_ActionCode,
    multiIf(epd_Code='av', 'Anonymous VPN',
    epd_Code='pp','Public Proxy',
    epd_Code='hp','Hosting Provder',
    epd_Code='tr','TOR Exit Node',
    epd_Code='dp','Smart DNS Proxy',
    epd_Code='rp','Residential Proxy',
    epd_Code='vc','VPN Data Centre','') AS epd_Category,
    multiIf(epd_ActionCode='0', 'Request Denied',
    epd_ActionCode='1', 'Request Allowed(override)',
    epd_ActionCode='2', 'Request Redirected', '') AS epd_ActionName,
    splitByChar('|',assumeNotNull(securityRules))[1] AS policy,
    splitByChar('|',assumeNotNull(securityRules))[3] AS denyRule,
    if(empty(splitByChar('|',assumeNotNull(securityRules))[3]),0,1) AS denied,
    multiIf(denyRule like '%REP%','Reputation', 
	denyRule like '3%' or denyRule like 'BOT-%', 'BOT',
	denyRule like 'IP%', 'DOS',
	denyRule like 'XSS%' or denyRule like 'WAT-%' or denyRule like 'RFI-ANOMALY%' or denyRule like 'PLATFORM-ANOMALY' or  denyRule like 'SQL%' or denyRule like 'LFI%' or denyRule like 'CMD-INJECTION%' or denyRule like 'PROTOCOL-ANOMALY%'  or denyRule like 'ADAPTIVE_UA_IP_BLOCK%' or denyRule like '6%', 'WAF Rule',
	''
	) AS denyGroup,
    splitByChar('|',assumeNotNull(earlyHints))[1] AS userHints,
    splitByChar('|',assumeNotNull(earlyHints))[2] AS userHintsBytes,
    splitByChar('|',assumeNotNull(earlyHints))[3] AS akamaiHints,
    splitByChar('|',assumeNotNull(earlyHints))[4] AS akamaiHintsBytes,
    akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[1] AS ew_stageInformation,
    akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[2] AS ew_ID,
    akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[3] AS ew_processTime,
    akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[4] AS ew_totalTime,
    akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[5] AS ew_totalStageTime,
    akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[6] AS ew_usedMemory,
    akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[7] AS ew_edgeServerFlow,
    akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[8] AS ew_errorCode,
    akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[9] AS ew_httpStatus,
    akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[10] AS ew_cpuFlits,
    akamai_edge_worker_execution(assumeNotNull(ewExecutionInfo))[11] AS ew_tierID,
    akamai_edge_worker(assumeNotNull(ewUsageInfo))[1] AS ew_uID,
    akamai_edge_worker(assumeNotNull(ewUsageInfo))[2] AS ew_version,
    akamai_edge_worker(assumeNotNull(ewUsageInfo))[3] AS ew_eventHandler,
    akamai_edge_worker(assumeNotNull(ewUsageInfo))[4] AS ew_offReason,
    akamai_edge_worker(assumeNotNull(ewUsageInfo))[5] AS ew_logicExecuted,
    akamai_edge_worker(assumeNotNull(ewUsageInfo))[6] AS ew_status,
    akamai_edge_worker(assumeNotNull(ewUsageInfo))[7] AS ew_revisionID,
    akamai_edge_worker(assumeNotNull(ewUsageInfo))[8] AS ew_metrics,
    splitByChar(':',splitByChar('|',coalesce(assumeNotNull(securityRules),'||'))[2]) AS rulesTriggered,
    concat(reqHost, reqPath) AS URL,
    multiIf(
cacheStatus=1,1,
breadcrumbs IS NULL OR empty(breadcrumbs),0,
Origin_IP IS NULL OR empty(Origin_IP) OR Origin_IP = '127.0.0.1',1,0
) AS cacheStatus,
    *,
    'Akamai' AS hdx_cdn,
    dictGet('akamai_ua_cat_dict', 'ua_category', assumeNotNull(UA)) AS userAgentCategory,
    dictGet('akamai_ua_cat_dict', 'ua_category_key', assumeNotNull(UA)) AS userAgentCategoryKey,
    dictGet('akamai_ua_cat_dict', 'ai_category', assumeNotNull(UA)) AS aiCategory,
    dictGet('akamai_ua_cat_dict', 'is_bot', assumeNotNull(UA)) AS isBotTraffic,
    dictGet('akamai_ua_cat_dict', 'bot_class', assumeNotNull(UA)) AS botClass,
    dictGet('akamai_ua_cat_dict', 'bot_intent', assumeNotNull(UA)) AS botIntent,
    dictGet('akamai_ua_cat_dict', 'producer', assumeNotNull(UA)) AS botProducer,
    multiIf(positionCaseInsensitive(assumeNotNull(reqPath), 'robots.txt') > 0, 'robots.txt', positionCaseInsensitive(assumeNotNull(reqPath), 'sitemap.xml') > 0, 'sitemap.xml', positionCaseInsensitive(assumeNotNull(reqPath), 'ads.txt') > 0, 'ads.txt', positionCaseInsensitive(assumeNotNull(reqPath), 'llms.txt') > 0, 'llms.txt', match(assumeNotNull(reqPath), '^/api/') OR match(assumeNotNull(reqPath), '/api/'), 'api', match(assumeNotNull(reqPath), '\\.(css|js|png|jpg|jpeg|gif|svg|ico|woff2?|ttf|eot)$'), 'static', match(assumeNotNull(reqPath), '\\.(html?|php|asp|jsp)$') OR assumeNotNull(reqPath) = '/' OR NOT match(assumeNotNull(reqPath), '\\.'), 'page', 'other') AS resourceCategory,
    dictGetOrDefault('akamai_asn_type_dict', 'asn_type', toUInt32OrZero(toString(asn)), 'unknown') AS asnType,
    dictGetOrDefault('akamai_bot_ip_dict', 'bot_owner', toIPv4OrDefault(assumeNotNull(cliIP)), '') AS verifiedBotOwner,
    multiIf(isBotTraffic = 1 AND verifiedBotOwner != '', 'verified', isBotTraffic = 1 AND asnType = 'isp', 'declared_unverified', isBotTraffic = 1, 'unverified', 'not_bot') AS botVerificationTier,
    multiIf(isBotTraffic = 1 AND verifiedBotOwner != '', 'verified', isBotTraffic = 1 AND asnType = 'isp', 'suspicious', isBotTraffic = 1 AND asnType IN ('hosting', 'business'), 'plausible', isBotTraffic = 1, 'unverified', 'not_bot') AS botConfidence,
    --splitByString('/', coalesce(reqPath, '')) AS req_path_array,
    lower(cutQueryString(coalesce(reqPath, ''))) AS requestPathNorm,
    --if(empty(arrayFilter(segment -> notEmpty(segment), splitByChar('/', requestPathNorm))), '/', concat('/', arrayElement(arrayFilter(segment -> notEmpty(segment), splitByChar('/', requestPathNorm)), 1))) AS requestPathRoot,
if(arrayStringConcat(arrayMap(seg -> multiIf(seg IN (':num', ':version', ':hex', ':asset', ':token'), seg, has(['api', 'graphql', 'checkout', 'login', 'auth', 'oauth', 'sso', 'account', 'accounts', 'user', 'users', 'profile', 'customer', 'customers', 'search', 'cart', 'product', 'products', 'pd', 'category', 'categories', 'content', 'static', 'assets', 'asset', 'images', 'image', 'img', 'media', 'dist', 'js', 'css', 'json', 'fonts', 'font', 'store', 'stores', 'shop', 'catalog', 'collections', 'collection', 'loyalty', 'rates', 'rooms', 'blogs', 'wp-admin', 'admin', '_sec', '_bm', 'akam', 'm', 'mobile', 'web', 'app', 'client-api', 'internal', 'live', 'vod', 'hls', 'cmaf', 'feeds', 'feed', 'logos', 'logo', 'scoreboard', 'channels', 'channel', 'event', 'events', 'card', 'cards', 'leagues', 'league', 'teams', 'team', 'public', 'latest', 'client', 'tabs', 'subscriber', 'manage', 'include', 'redirect_flags', 'traffic', 'exchange', 'chunks', 'chunk', 'whitelist', 'livedata', 'odds'], seg), seg, match(seg, '^[a-z]{2}(-[a-z]{2})?$'), ':locale', ':slug'), arrayMap(seg -> multiIf(seg = '', '', match(seg, '^[0-9]+$'), ':num', match(seg, '^v?[0-9]+(\\.[0-9]+)+$'), ':version', match(seg, '^[0-9a-f]{8,}$'), ':hex', match(seg, '\\.(css|js|png|jpe?g|gif|svg|ico|woff2?|ttf|eot|map|json|xml|webp|avif|mp4|m3u8|ts|pdf)$'), ':asset', length(seg) >= 6 AND match(seg, '[0-9]') AND match(seg, '[a-z]') AND match(seg, '^[a-z0-9_-]+$'), ':token', seg), splitByChar('/', trim(BOTH '/' FROM lower(ifNull(requestPathNorm, '')))))), '/') = '', '/', concat('/', arrayStringConcat(arrayMap(seg -> multiIf(seg IN (':num', ':version', ':hex', ':asset', ':token'), seg, has(['api', 'graphql', 'checkout', 'login', 'auth', 'oauth', 'sso', 'account', 'accounts', 'user', 'users', 'profile', 'customer', 'customers', 'search', 'cart', 'product', 'products', 'pd', 'category', 'categories', 'content', 'static', 'assets', 'asset', 'images', 'image', 'img', 'media', 'dist', 'js', 'css', 'json', 'fonts', 'font', 'store', 'stores', 'shop', 'catalog', 'collections', 'collection', 'loyalty', 'rates', 'rooms', 'blogs', 'wp-admin', 'admin', '_sec', '_bm', 'akam', 'm', 'mobile', 'web', 'app', 'client-api', 'internal', 'live', 'vod', 'hls', 'cmaf', 'feeds', 'feed', 'logos', 'logo', 'scoreboard', 'channels', 'channel', 'event', 'events', 'card', 'cards', 'leagues', 'league', 'teams', 'team', 'public', 'latest', 'client', 'tabs', 'subscriber', 'manage', 'include', 'redirect_flags', 'traffic', 'exchange', 'chunks', 'chunk', 'whitelist', 'livedata', 'odds'], seg), seg, match(seg, '^[a-z]{2}(-[a-z]{2})?$'), ':locale', ':slug'), arrayMap(seg -> multiIf(seg = '', '', match(seg, '^[0-9]+$'), ':num', match(seg, '^v?[0-9]+(\\.[0-9]+)+$'), ':version', match(seg, '^[0-9a-f]{8,}$'), ':hex', match(seg, '\\.(css|js|png|jpe?g|gif|svg|ico|woff2?|ttf|eot|map|json|xml|webp|avif|mp4|m3u8|ts|pdf)$'), ':asset', length(seg) >= 6 AND match(seg, '[0-9]') AND match(seg, '[a-z]') AND match(seg, '^[a-z0-9_-]+$'), ':token', seg), splitByChar('/', trim(BOTH '/' FROM lower(ifNull(requestPathNorm, '')))))), '/'))) AS requestPathPattern,
   -- multiIf(match(requestPathNorm, '^/shop/product/[^/]+'), '/shop/product/:item', match(requestPathNorm, '^/product/[^/]+'), '/product/:item', match(requestPathNorm, '^/products/[^/]+'), '/products/:item', match(requestPathNorm, '^/p/[^/]+'), '/p/:item', match(requestPathNorm, '^/shop/[^/]+/[^/]+'), replaceRegexpOne(requestPathNorm, '^(/shop/[^/]+)/.*', '\\1/:path'), match(requestPathNorm, '^/category/[^/]+/[^/]+'), replaceRegexpOne(requestPathNorm, '^(/category/[^/]+)/.*', '\\1/:path'), match(requestPathNorm, '^/c/[^/]+/[^/]+'), replaceRegexpOne(requestPathNorm, '^(/c/[^/]+)/.*', '\\1/:path'), match(requestPathNorm, '^/api/[^/]+/[^/]+/[^/]+/[^/]+'), replaceRegexpOne(requestPathNorm, '^(/api/[^/]+/[^/]+/[^/]+)/.*', '\\1/:path'), match(requestPathNorm, '^/xapi/[^/]+/[^/]+/[^/]+/[^/]+'), replaceRegexpOne(requestPathNorm, '^(/xapi/[^/]+/[^/]+/[^/]+)/.*', '\\1/:path'), requestPathPattern) AS requestPathPatternCoarse,
    if(notEmpty(aiCategory), botProducer, '') AS aiSource,
    multiIf(isBotTraffic = 0, 'Human', notEmpty(aiCategory), 'AI', 'Bot') AS trafficCohort
FROM
    {STREAM}