folders:
  hdx-main-folder:
    name: TrafficPeak Certified Reference Dashboards
    children: {}
dashboards:
  hdx-ds2-web-security:
    dashboard:
      __extend__: dashboards/DS2 Web Security.json
    folderUid: hdx-main-folder
  hdx-ds2-security-analysis:
    dashboard:
      __extend__: dashboards/DS2 Security Analysis.json
    folderUid: hdx-main-folder
