folders:
  hdx-main-folder:
    name: TrafficPeak Certified Reference Dashboards
    children: {}
dashboards:
  hdx-siem-raw-logs:
    dashboard:
      __extend__: dashboards/siem_raw_logs.json
    folderUid: hdx-main-folder
    inputs:
      DS_HDX-DEMO: hdx-hydrolix-datasource
      VAR_TABLE: akamai.siem
      VAR_TIMESTAMP: timestamp
  hdx-security-analysis:
    dashboard:
      __extend__: dashboards/security_analysis.json
    folderUid: hdx-main-folder
    inputs:
      DS_HDX-DEMO: hdx-hydrolix-datasource
      VAR_TABLE: akamai.siem
      VAR_TIMESTAMP: timestamp
  hdx-akamai-siem:
    dashboard:
      __extend__: dashboards/akamai_siem.json
    folderUid: hdx-main-folder
    inputs:
      DS_HDX-DEMO: hdx-hydrolix-datasource
      VAR_TABLE: akamai.siem
      VAR_LOGS: akamai.logs
