{
 "title": "Akamai SIEM",
 "description": "Akamai SIEM powered by Hydrolix dashboard for security analytics\r\n",
 "tags": [
  "v0.9",
  "Security",
  "SIEM"
 ],
 "time": { "from": "2026-01-29T19:36:48.850Z", "to": "2026-01-30T19:36:48.850Z" },
 "templating": {
  "list": [
   {
    "name": "siem",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   },
   { "name": "siem_summary_hour", "query": "__SUMMARY_TABLE_NAME_1__" },
   { "name": "siem_summary_day", "query": "__SUMMARY_TABLE_NAME_2__" },
   {
    "name": "duration",
    "query": "SELECT datediff('h', $__fromTime, $__toTime)"
   },
   {
    "name": "table",
    "label": "Table used",
    "query": "SELECT  CASE\nWHEN ${duration} < 6 THEN '${siem}'\nWHEN ${duration} >= 6 AND ${duration} < 72 THEN '${siem_summary_hour}'\nWHEN ${duration} >= 72 THEN '${siem_summary_day}'\nEND"
   },
   { "name": "filter" },
   {
    "name": "attackTypes",
    "label": "Attack Types",
    "query": "SELECT arrayJoin(attackTypes) as type\nFROM ${table}\nWHERE timestamp >= $__fromTime\nAND timestamp < $__toTime\nGROUP BY type\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=attackTypes; du=${__user.login}'"
   },
   {
    "name": "ruleActions",
    "label": "Rule Action",
    "query": "SELECT arrayJoin(ruleActions) as ruleActions\nFROM ${table}\nWHERE timestamp >= $__fromTime\nAND timestamp < $__toTime\nGROUP BY ruleActions\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=ruleActions; du=${__user.login}'"
   },
   {
    "name": "ruleData",
    "label": "Rule Data",
    "query": "SELECT arrayJoin(ruleData) as ruleData\nFROM ${table}\nWHERE timestamp >= $__fromTime\nAND timestamp < $__toTime\nGROUP BY ruleData\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=ruleData; du=${__user.login}'"
   },
   {
    "name": "ruleTags",
    "label": "Rule Tags",
    "query": "SELECT arrayJoin(ruleTags) as ruleTags\nFROM ${table}\nWHERE timestamp >= $__fromTime\nAND timestamp < $__toTime\nGROUP BY ruleTags\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=ruleTags; du=${__user.login}'"
   },
   {
    "name": "ruleMessages",
    "label": "Rule Messages",
    "query": "SELECT arrayJoin(ruleMessages) as ruleMessages\nFROM ${table}\nWHERE timestamp >= $__fromTime\nAND timestamp < $__toTime\nGROUP BY ruleMessages\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=ruleMessages; du=${__user.login}'"
   },
   {
    "name": "rulesID",
    "label": "Rule ID",
    "query": "SELECT arrayJoin(rules) as rules\nFROM ${table}\nWHERE timestamp >= $__fromTime\nAND timestamp < $__toTime\nGROUP BY rules\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=rulesID; du=${__user.login}'"
   },
   {
    "name": "ruleSelectors",
    "label": "Rule Selectors",
    "query": "SELECT arrayJoin(ruleSelectors) as ruleSelectors\nFROM ${table}\nWHERE timestamp >= $__fromTime\nAND timestamp < $__toTime\nGROUP BY ruleSelectors\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=ruleSelectors; du=${__user.login}'"
   },
   { "name": "path", "label": "Path" },
   {
    "name": "sampledFields_banner",
    "query": "SELECT IF('${table}' = '${siem_summary_hour}' OR '${table}' = '${siem_summary_day}', \n    'Please note: \nDue to the current time range selection (>= 6 hours), the fields clientIP, host and path have been sampled.', \n    'Akamai SIEM:\nReal-time security event monitoring for Akamai infrastructure, including DDoS mitigation, bot detection, and firewall rule analysis.'\n)"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "#### ${sampledFields_banner}" } },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "SIEM Logs Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT arrayJoin(ruleActions) as ruleAction,\ncount(),\n$__timeInterval(timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(path ILIKE '%${path}%', $path)\nGROUP BY time, ruleAction\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=SIEM Logs Count; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "SIEM Logs per Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT toString(status) as status_code, count(),\n$__timeInterval(timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(path ILIKE '%${path}%', $path)\nGROUP BY time, status_code\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=SIEM Logs per Status Code; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 100 Message",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT count(),\narrayJoin(ruleMessages) AS message\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(path ILIKE '%${path}%', $path)\nGROUP BY message\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 100 Message; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 100 Tags",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT count(),\narrayJoin(ruleTags) AS tags\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(path ILIKE '%${path}%', $path)\nGROUP BY tags\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 100 Tags; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 100 Path",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT count(),\npath\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND path != '~~~SAMPLED_OUT~~~'\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(path ILIKE '%${path}%', $path)\nGROUP BY path\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 100 Path; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 100 Client IP",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT count(),\nclientIP\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND clientIP != '~~~SAMPLED_OUT~~~'\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(path ILIKE '%${path}%', $path)\nGROUP BY clientIP\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 100 Client IP; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 100 Host",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT count(),\nhost\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND host != '~~~SAMPLED_OUT~~~'\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(path ILIKE '%${path}%', $path)\nGROUP BY host\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 100 Host; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Geo Map",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Geo Map",
     "type": "geomap",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT country, count()\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(path ILIKE '%${path}%', $path)\nGROUP BY country\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Geo Map; du=${__user.login}'"
      }
     ]
    }
   ]
  }
 ]
}