{
 "title": "Security Analysis",
 "description": "Web Security Analytics on TrafficPeak",
 "tags": [
  "Security",
  "SIEM",
  "v0.9"
 ],
 "time": { "from": "2026-01-29T19:35:21.590Z", "to": "2026-01-30T19:34:21.590Z" },
 "templating": {
  "list": [
   {
    "name": "siem",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   },
   {
    "name": "siem_summary_hour",
    "query": "__PROJECT_NAME__.__SUMMARY_TABLE_NAME_1__"
   },
   {
    "name": "siem_summary_day",
    "query": "__PROJECT_NAME__.__SUMMARY_TABLE_NAME_2__"
   },
   {
    "name": "duration",
    "query": "SELECT datediff('h', $__fromTime, $__toTime)"
   },
   {
    "name": "table",
    "label": "Table used",
    "query": "SELECT  CASE\nWHEN ${duration} < 6 THEN '${siem}'\nWHEN ${duration} >= 6 AND ${duration} < 72 THEN '${siem_summary_hour}'\nWHEN ${duration} >= 72 THEN '${siem_summary_day}'\nEND"
   },
   { "name": "timestamp", "query": "${VAR_TIMESTAMP}" },
   { "name": "filter" },
   {
    "name": "attackTypes",
    "label": "Attack Types",
    "query": "SELECT arrayJoin(attackTypes) as type\nFROM ${table}\nWHERE timestamp >= $__fromTime\nAND timestamp < $__toTime\nGROUP BY type\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=attackTypes; du=${__user.login}'"
   },
   {
    "name": "ruleActions",
    "label": "Rule Action",
    "query": "SELECT arrayJoin(ruleActions) as ruleActions\nFROM ${table}\nWHERE timestamp >= $__fromTime\nAND timestamp < $__toTime\nGROUP BY ruleActions\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=ruleActions; du=${__user.login}'"
   },
   {
    "name": "ruleData",
    "label": "Rule Data",
    "query": "SELECT arrayJoin(ruleData) as ruleData\nFROM ${table}\nWHERE timestamp >= $__fromTime\nAND timestamp < $__toTime\nGROUP BY ruleData\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=ruleData; du=${__user.login}'"
   },
   {
    "name": "ruleTags",
    "label": "Rule Tags",
    "query": "SELECT arrayJoin(ruleTags) as ruleTags\nFROM ${table}\nWHERE timestamp >= $__fromTime\nAND timestamp < $__toTime\nGROUP BY ruleTags\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=ruleTags; du=${__user.login}'"
   },
   {
    "name": "ruleMessages",
    "label": "Rule Messages",
    "query": "SELECT arrayJoin(ruleMessages) as ruleMessages\nFROM ${table}\nWHERE timestamp >= $__fromTime\nAND timestamp < $__toTime\nGROUP BY ruleMessages\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=ruleMessages; du=${__user.login}'"
   },
   {
    "name": "ruleID",
    "label": "Rule ID",
    "query": "SELECT arrayJoin(rules) as rules\nFROM ${table}\nWHERE timestamp >= $__fromTime\nAND timestamp < $__toTime\nGROUP BY rules\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=ruleID; du=${__user.login}'"
   },
   {
    "name": "ruleSelectors",
    "label": "Rule Selectors",
    "query": "SELECT arrayJoin(ruleSelectors) as ruleSelectors\nFROM ${table}\nWHERE timestamp >= $__fromTime\nAND timestamp < $__toTime\nGROUP BY ruleSelectors\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=ruleSelectors; du=${__user.login}'"
   },
   { "name": "path", "label": "Path" },
   {
    "name": "sampledFields_banner",
    "query": "SELECT IF('${table}' = '${siem_summary_hour}' OR '${table}' = '${siem_summary_day}', \n    'Please note: \nDue to the current time range selection (>= 6 hours), the fields clientIP, host and path have been sampled.', \n    'Security Analysis:\nSIEM (Security Information and Event Management) is a comprehensive security solution that aggregates, analyzes, and correlates security data from across an organization IT infrastructure in real-time'\n)"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "options": { "content": "#### ${sampledFields_banner}" } },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Attack by Hostname",
   "type": "timeseries",
   "description": "Attack by Hostname by time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n\thost,\n\t$__timeInterval(timestamp) as time,\n\tcount()\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND host != '~~~SAMPLED_OUT~~~'\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(path ILIKE '%${path}%', $path)\nGROUP BY time, host\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Attack by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Rule Action Count",
   "type": "timeseries",
   "description": "Rule Action Count by time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT arrayJoin(ruleActions) as ruleAction,\n$__timeInterval(timestamp) as time,\ncount()\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(path ILIKE '%${path}%', $path)\nGROUP BY time, ruleAction\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Rule Action Count; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Attack Groups (Excluding Bot)",
   "type": "timeseries",
   "description": "High-level categories that organize multiple related attack types based on their nature and threat vector",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT arrayJoin(arrayFilter(x -> x != 'Bot', attackTypes)) as attack,\ncount(),\n$__timeInterval(timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(path ILIKE '%${path}%', $path)\nGROUP BY time, attack\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Attack Groups (Excluding Bot); du=${__user.login}'"
    }
   ]
  },
  {
   "title": "WAF",
   "type": "timeseries",
   "description": "Attacks targeting web applications - SQL injection, XSS, path traversal by time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT arrayJoin(arrayMap( x -> if(position(x,':') !=0, 'Record Header', x), ruleTagsWAF)) as tag,\ncount(),\n$__timeInterval(timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(path ILIKE '%${path}%', $path)\nAND attack_waf = 1\nGROUP BY time, tag\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=WAF; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "DoS",
   "type": "timeseries",
   "description": "Attacks attempting to overwhelm systems/networks with traffic to make services unavailable.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT arrayJoin(arrayMap( x -> if(position(x,':') !=0, 'Record Header', x), ruleTagsDOS)) as tag,\ncount(),\n$__timeInterval(timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(path ILIKE '%${path}%', $path)\nAND attack_dos = 1\nGROUP BY time, tag\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=DoS; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Reputation",
   "type": "timeseries",
   "description": "Threats identified based on known malicious IP addresses, domains, or file hashes from threat intelligence feeds  by time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT ruleMessage,\ncount(),\n$__timeInterval(timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(path ILIKE '%${path}%', $path)\nAND isNotNull(ruleMessage)\nAND attack_reputation\nGROUP BY time, ruleMessage\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Reputation; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Bot",
   "type": "timeseries",
   "description": "Automated malicious activity - credential stuffing, scraping, spam bots, malicious crawlers",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT arrayJoin(arrayMap( x -> if(position(x,':') !=0, 'Record Header', x), ruleTagsBot)) as tag,\ncount(),\n$__timeInterval(timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(path ILIKE '%${path}%', $path)\nAND attack_bot\nGROUP BY time, tag\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Bot; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 100 Rankings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host",
     "type": "table",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT count() as count,\nhost\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND host != '~~~SAMPLED_OUT~~~'\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY host\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Host; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Path",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 4, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT count() as count,\npath\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND path != '~~~SAMPLED_OUT~~~'\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY path\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Path; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Country",
     "type": "table",
     "gridPos": { "h": 9, "w": 3, "x": 10, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT count() as count,\ncountry\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY country\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Country; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "AS Number",
     "type": "table",
     "gridPos": { "h": 9, "w": 3, "x": 13, "y": 151 },
     "targets": [
      {
       "rawSql": "SELECT count() as count,\nasn\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY asn\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=AS Number; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Client IP",
     "type": "table",
     "gridPos": { "h": 9, "w": 4, "x": 16, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT count() as count,\nclientIP\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND clientIP != '~~~SAMPLED_OUT~~~'\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY clientIP\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Client IP; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Rule ID",
     "type": "table",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 151 },
     "targets": [
      {
       "rawSql": "SELECT\n  count() as count, rule\nFROM ${table}\nARRAY JOIN arrayDistinct( rules ) AS rule\nWHERE $__timeFilter(${timestamp})\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(rule IN (${ruleID:sqlstring}), $ruleID)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY rule\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Rule ID; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Rule Tag",
     "type": "table",
     "gridPos": { "h": 11, "w": 5, "x": 0, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  count() as count, \n  arrayJoin(arrayDistinct(arrayMap( x ->  if (position(x , ':') !=0, 'Record Header', x), ruleTags))) AS tag\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(tag IN (${ruleTags:sqlstring}), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY tag\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Rule Tag; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Rule Message",
     "type": "table",
     "gridPos": { "h": 11, "w": 6, "x": 5, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT count() as count,\narrayJoin(ruleMessages) AS message\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(message IN (${ruleMessages:sqlstring}), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY message\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Rule Message; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "User-Agent",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 11, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT count() as count, UA, REPLACE(UA, ',', '__gfc__') AS escaped_UA\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY UA\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=User-Agent; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Sec-CH-UA",
     "type": "table",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT count() as count,\nCH_UA,\nREPLACE(CH_UA, ',', '__gfc__') AS escaped_CH_UA\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND has_CH_UA\nGROUP BY CH_UA\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Sec-CH-UA; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Samples - request-level view",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Samples",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 696 },
     "targets": [
      {
       "rawSql": "SELECT requestId, formatDateTime(timestamp, '%F %T') AS Time, clientIP, asn, country, method, protocol, host, path, status, ruleActions, ruleTags\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND clientIP != '~~~SAMPLED_OUT~~~'\nAND host != '~~~SAMPLED_OUT~~~'\nAND path != '~~~SAMPLED_OUT~~~'\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(path ILIKE '%${path}%', $path)\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Samples; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Count by Geo Map",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hits per Country",
     "type": "geomap",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 697 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT country, count()\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${attackTypes:sqlstring}], attackTypes), $attackTypes)\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleID:sqlstring}], rules), $ruleID)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(path ILIKE '%${path}%', $path)\nGROUP BY country\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Geo Map; du=${__user.login}'"
      }
     ]
    }
   ]
  }
 ]
}