{
 "title": "EAA View Global Stats",
 "description": "testing",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   },
   { "name": "device_table", "query": "${VAR_DEVICE_TABLE}" },
   { "name": "generalescaping", "query": "${VAR_GENERALESCAPING}" },
   {
    "name": "raw_table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   }
  ]
 },
 "panels": [
  {
   "title": "EAA View Global Stats",
   "type": "canvas",
   "description": "Provides overall statistics on the total number of users, logins, applications visited, etc.",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(datetime) AS d,\n  uniq(username) as \"Total_Username\",\n  uniq(origin) as \"Total_Origin\",\n  uniq(apphost) as \"Total_EAA_APPS\",\n  uniq(cloudZone) as \"Total_cloudZone\",\n  SUM(bytesIn) \"Incoming\",\n  SUM(bytesOut) \"Outgoing\",\n  uniq(conUuid) as \"Total_Connectors\"\n  FROM ${table}\n  WHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \n  AND origin != '-'\n  AND username != '-'\n  AND apphost != '-'\n  and conUuid != '-'\nGROUP BY  d\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Users per APP; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Last 5m stats",
   "type": "canvas",
   "gridPos": { "h": 1, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  uniq(username) as Total_Username,\n  uniq(origin) as Total_Origin,\n  uniq(apphost) as Total_EAA_APPS,\n  uniq(cloudZone) as Total_cloudZone,\n  SUM(bytesIn) \"Incoming\",\n  SUM(bytesOut) \"Outgoing\",\n  toDate(datetime) as d\n  FROM ${table}\n  WHERE datetime >= now() - INTERVAL 30 day\n\n  AND ${generalescaping}\n  \nGROUP BY  d\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Users per APP; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Total EAA_App",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT uniq(apphost) as Count_EAA_App,\ntoStartOfInterval(datetime, INTERVAL 5 MINUTE) AS d \nFROM ${table}\nWHERE datetime >= now() - INTERVAL 24 hour\nAND ${generalescaping}\n\nGROUP BY  d\norder by d asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last 500 logged in users; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "Total CloudZone",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT uniq(cloudZone) as Count_CloudZone,\ntoStartOfInterval(datetime, INTERVAL 5 MINUTE) AS d \nFROM ${table}\nWHERE datetime >= now() - INTERVAL 24 hour\nAND ${generalescaping}\n\nGROUP BY  d\norder by d asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Total CloudZone; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT sum(bytesIn) Incoming,\ntoStartOfInterval(datetime, INTERVAL 5 MINUTE) AS d \nFROM ${table}\nWHERE datetime >= now() - INTERVAL 24 hour\nAND ${generalescaping}\n\nGROUP BY  d\norder by d asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Incoming; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "Outgoing",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT sum(bytesOut) Outgoing,\ntoStartOfInterval(datetime, INTERVAL 5 MINUTE) AS d \nFROM ${table}\nWHERE datetime >= now() - INTERVAL 24 hour\nAND ${generalescaping}\n\nGROUP BY  d\norder by d asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Outgoing; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "Total users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT uniq(username) as Count_Users,\ntoStartOfInterval(datetime, INTERVAL 5 MINUTE) AS d \nFROM ${table}\nWHERE datetime >= now() - INTERVAL 24 hour\nAND ${generalescaping}\nAND username != '-'\nGROUP BY  d\norder by d asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Total users; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "Total logins",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT uniq(username) as Count_Users,\ntoStartOfInterval(datetime, INTERVAL 5 MINUTE) AS d \nFROM ${table}\nWHERE datetime >= now() - INTERVAL 24 hour\nAND ${generalescaping}\nAND username != '-'\n\nAND (\n  urlPath = '/saml/sp/response' \n  AND \n  idpinfo = 'UNSPEC|D'\n  AND\n  username != '-'\n)\n\nGROUP BY  d\norder by d asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Total logins; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "Total failed logins",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT uniq(username) as Count_Users,\ntoStartOfInterval(datetime, INTERVAL 5 MINUTE) AS d \nFROM ${table}\nWHERE datetime >= now() - INTERVAL 24 hour\nAND ${generalescaping}\nAND username != '-'\nAND idpinfo IN ('LOGIN|F', 'MFA|MF')\n\nGROUP BY  d\norder by d asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Total failed logins; du=${__user.login}'\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 15, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT now() AS Last_Run\n" }
   ]
  },
  {
   "title": "Total origin",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT uniq(origin) as Count_Origin,\ntoStartOfInterval(datetime, INTERVAL 5 MINUTE) AS d \nFROM ${table}\nWHERE datetime >= now() - INTERVAL 24 hour\nAND ${generalescaping}\n\nGROUP BY  d\norder by d asc\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Total origin; du=${__user.login}'\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "options": { "content": "---------------" } },
  {
   "title": "Daily users",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 916 }
   ]
  },
  {
   "title": "Daily login errors",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\ntoDate(datetime) as d,\n  uniq(username) as \"Total_Login_Errors\"\n  FROM ${table}\n  WHERE datetime >= now() - INTERVAL 30 day\n  AND idpinfo IN ('LOGIN|F', 'MFA|MF')\n\n  AND ${generalescaping}\n  \nGROUP BY  d\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Daily login errors; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Daily data consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "panelId": 916 }
   ]
  },
  {
   "title": "Daily logins",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\ntoDate(datetime) as d,\n  uniq(username) as \"Total_Logins\"\n\n  FROM ${table}\n  WHERE datetime >= now() - INTERVAL 30 day\n\nAND (\n  urlPath = '/saml/sp/response' \n  AND \n  idpinfo = 'UNSPEC|D'\n  AND\n  username != '-'\n)\n\nand username != '-'\n\nAND ${generalescaping}\n  \nGROUP BY  d\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Daily logins; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Daily origins",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 916 }
   ]
  },
  {
   "title": "Daily EAA_App",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 916 }
   ]
  },
  {
   "title": "Daily CloudZone",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 916 }
   ]
  }
 ]
}