{
 "title": "EAA Username Observability",
 "description": "testing",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   },
   { "name": "table_deviceinventory", "query": "${VAR_TABLE_DEVICEINVENTORY}" },
   { "name": "device_table", "query": "${VAR_DEVICE_TABLE}" },
   { "name": "filter" },
   { "name": "timestamp", "query": "datetime" },
   { "name": "generalescaping", "query": "${VAR_GENERALESCAPING}" },
   { "name": "querieslimit", "query": "${VAR_QUERIESLIMIT}" },
   { "name": "commonlibraries", "query": "${VAR_COMMONLIBRARIES}" },
   {
    "name": "raw_table",
    "query": "__PROJECT_NAME__.__TABLE_NAME__"
   }
  ]
 },
 "panels": [
  {
   "title": "Username Observability",
   "type": "canvas",
   "description": "To run this dashboard, start from Usage Stats, selecting the desired user.",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(datetime) AS d,\n  uniq(username) as \"Total_Username\",\n  uniq(origin) as \"Total_Origin\",\n  uniq(apphost) as \"Total_EAA_APPS\",\n  uniq(cloudZone) as \"Total_cloudZone\",\n  uniq(geoCity) as \"Total_geoCity\",\n  uniq(geoCountry) as \"Total_geoCountry\",\n  SUM(bytesIn) \"Incoming\",\n  SUM(bytesOut) \"Outgoing\",\n  uniq(conUuid) as \"Total_Connectors\"\n  FROM ${table}\n  WHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \n  AND origin != '-'\n  AND username != '-'\n  AND apphost != '-'\n  and conUuid != '-'  \nGROUP BY  d\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Users per APP; du=${__user.login}'"
    }
   ]
  },
  { "title": "LAST 30 MINS for User", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  if(count() > 0, 'Connected', 'Not Connected') AS qres,\n  99 AS v\nFROM ${table}\nWHERE datetime > NOW() - INTERVAL 30 MINUTE\n  AND ${generalescaping}\n  AND $__adHocFilter() \nSETTINGS \n  hdx_query_max_execution_time=60, \n  hdx_query_admin_comment='db=${__dashboard}; dp=Status; du=${__user.login}'"
    },
    {
     "rawSql": "SELECT count(DISTINCT username) AS querycontroller, 99 as v\nFROM ${table}\nWHERE datetime > NOW() - INTERVAL 30 MINUTE\n  AND ${generalescaping}\n  AND $__adHocFilter()\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=ActiveUserCount; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Last login time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT datetime,  99 as v FROM ${table} \n  WHERE $__timeFilter(datetime)\nAND ${generalescaping}\n  AND $__adHocFilter() \n\nAND (\n  urlPath = '/saml/sp/response'\n  AND\n  idpinfo = 'UNSPEC|D'\n  AND\n  username != '-'\n)\n\n  order by datetime desc\n  limit 1\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last login time; du=${__user.login}'"
    },
    {
     "rawSql": "SELECT count(DISTINCT username) AS querycontroller, 99 as v\nFROM ${table}\nWHERE $__timeFilter(datetime)\nAND datetime > NOW() - INTERVAL 30 MINUTE\n  AND ${generalescaping}\n  AND $__adHocFilter()\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=ActiveUserCount; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Last Client IP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT clientip, 99 as v FROM ${table}\nWHERE $__timeFilter(datetime)\nAND ${generalescaping}\nAND $__adHocFilter() \norder by datetime desc\nlimit 1\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Current Client IP; du=${__user.login}'\n"
    },
    {
     "rawSql": "SELECT count(DISTINCT username) AS querycontroller, 99 as v\nFROM ${table}\nWHERE $__timeFilter(datetime)\nAND datetime > NOW() - INTERVAL 30 MINUTE\n  AND ${generalescaping}\n  AND $__adHocFilter()\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=ActiveUserCount; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Last connecting Geo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT geoCity as City, geoCountry as Country, 99 as v FROM ${table}\nWHERE $__timeFilter(datetime)\nAND ${generalescaping}\nAND $__adHocFilter() \norder by datetime desc\nlimit 1\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Current connecting Geo; du=${__user.login}'"
    },
    {
     "rawSql": "SELECT count(DISTINCT username) AS querycontroller, 99 as v\nFROM ${table}\nWHERE $__timeFilter(datetime)\nAND datetime > NOW() - INTERVAL 30 MINUTE\n  AND ${generalescaping}\n  AND $__adHocFilter()\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=ActiveUserCount; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "User Location",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT geoCountrycode, geoCountry, uniq(username) as Total_users\nFROM ${table}\nWHERE datetime > NOW() - INTERVAL 30 MINUTE\nAND ${generalescaping}\nAND $__adHocFilter() \nGROUP BY geoCountrycode, geoCountry\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 5 Origins; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "User Groups ",
   "type": "table",
   "description": "Groups associated with the user",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n  DISTINCT arrayJoin(splitByChar(',', assumeNotNull(groups))) AS Name, 99 as v\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND groups != '-'\n\nORDER BY datetime DESC\nLIMIT 500\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=User Groups ; du=${__user.login}'\n"
    },
    {
     "rawSql": "SELECT count(DISTINCT username) AS querycontroller, 99 as v\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND datetime > NOW() - INTERVAL 30 MINUTE\n  AND ${generalescaping}\n  AND $__adHocFilter()\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=ActiveUserCount; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Near realtime bandwidth usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT sum(bytesIn)*8/60 as Incoming, sum(bytesOut)*8/60 as Outgoing, \ntoStartOfInterval(datetime, INTERVAL 60 SECOND) AS d\n--datetime as d\nFROM ${table} \nWHERE datetime > (now() - interval 30 minute)\nAND ${generalescaping}\nAND $__adHocFilter() \nAND username != '-'\nGROUP BY d\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Near realtime bandwidth usage; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Tops for user",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Destinations by hits",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 284 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  origin, count() as Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \n  AND origin != '-'\nGROUP BY origin\nORDER BY Total DESC\nLIMIT 5\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 5 Destinations by hits; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top 5 EAA_APP by hits",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 284 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT apphost, count(*) as Total FROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND apphost != '-'\n\ngroup by apphost\norder by Total desc\nlimit 5\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 5 EAA_APP by hits; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Login errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed logins",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 285 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeInterval(datetime) AS d,\n  count(*) as \"Total\"\n  FROM ${table}\n  WHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \n  AND idpinfo IN ('LOGIN|F', 'MFA|MF')\nGROUP BY  d, denyReason, statusCode\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Failed logins; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} failed login users list",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 285 },
     "targets": [
      {
       "rawSql": "SELECT\n  username, denyReason, clientip, datetime\n  FROM ${table}\n  WHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter() \n  AND idpinfo IN ('LOGIN|F', 'MFA|MF')\n  AND username != '-'\nGROUP BY  username, denyReason, clientip, datetime\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} failed login users list; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Origins analysis for user",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total origins accessed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 286 },
     "targets": [
      { "panelId": 882 }
     ]
    },
    {
     "title": "Last ${querieslimit} origin details",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 483 },
     "targets": [
      {
       "rawSql": "SELECT username, origin, maxOrNull(datetime) as Last_Access FROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND username != '-'\nAND origin != '-'\ngroup by username, origin \norder by Last_Access desc\nlimit ${querieslimit} \nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last ${querieslimit} origin details; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} active ports",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 483 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  arrayElement(splitByChar(':', ifNull(origin, '')), 2) AS port,\n  count(port) AS port_count,\n  maxOrNull(datetime) AS Last_Access\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND origin IS NOT NULL\n  AND origin != '-'\nGROUP BY port\nORDER BY port_count DESC\nLIMIT ${querieslimit}\nSETTINGS hdx_query_max_execution_time = 60,\n         hdx_query_admin_comment = 'db=${__dashboard}; dp=Top ${querieslimit} active ports; du=${__user.login}';\n"
      }
     ]
    }
   ]
  },
  {
   "title": "EAA_APP for User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "EAA_APP per User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 287 },
     "targets": [
      { "panelId": 882 }
     ]
    },
    {
     "title": "Last ${querieslimit} EAA_APP to username",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 287 },
     "targets": [
      {
       "rawSql": "SELECT username, apphost, maxOrNull(datetime) as Last_Access FROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND username != '-'\nAND apphost != '-'\ngroup by username, apphost \norder by Last_Access desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last ${querieslimit} EAA_APP to username; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Connectors for User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connectors per User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 288 },
     "targets": [
      { "panelId": 882 }
     ]
    },
    {
     "title": "Last ${querieslimit} connectors to User",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 288 },
     "targets": [
      {
       "rawSql": "SELECT username, conUuid, maxOrNull(datetime) as Last_Access FROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND username != '-'\nAND conUuid != '-'\ngroup by username, conUuid \norder by Last_Access desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last ${querieslimit} connectors to User; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Cloudzones & GEOs for User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cloudzones per User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 289 },
     "targets": [
      { "panelId": 882 }
     ]
    },
    {
     "title": "Last ${querieslimit} CloudZone per User",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 289 },
     "targets": [
      {
       "rawSql": "SELECT username, cloudZone, maxOrNull(datetime) as Last_Access FROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter()\nAND username != '-' \ngroup by username, cloudZone \norder by Last_Access desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last ${querieslimit} CloudZone per User; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "GEO per User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 415 },
     "targets": [
      { "panelId": 882 }
     ]
    },
    {
     "title": "Top ${querieslimit} GEO per User",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 415 },
     "targets": [
      {
       "rawSql": "SELECT username, geoCity, geoCountry, maxOrNull(datetime) as Last_Access\nFROM ${table} \nWHERE $__timeFilter(datetime)\nAND ${generalescaping}\nAND $__adHocFilter() \nAND username != '-'\ngroup by username, geoCity, geoCountry\norder by Last_Access desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} GEO per User; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic metrics for User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic for user",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "panelId": 882 }
     ]
    },
    {
     "title": "Last ${querieslimit} total traffic split by EAA_APP",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 362 },
     "targets": [
      {
       "rawSql": "SELECT sum(bytesIn) bytesin, sum(bytesOut) bytesout, toDate(datetime) as Date, username, apphost FROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter()\nAND username != '-'\nAND apphost != '-'  \nGROUP BY Date, username, apphost \norder by Date desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last ${querieslimit} total traffic split by EAA_APP; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Last ${querieslimit} total traffic split by destination",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 362 },
     "targets": [
      {
       "rawSql": "SELECT sum(bytesIn) bytesin, sum(bytesOut) bytesout, toDate(datetime) as Date, username, origin FROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter()  \nAND username != '-'\nAND origin != '-'\nGROUP BY Date, username, origin \norder by  Date desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last ${querieslimit} total traffic split by destination; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Client versions for User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client list ",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 291 },
     "targets": [
      {
       "rawSql": "SELECT clientVersion, clientId, deviceType, username, maxOrNull(datetime) as Last_Access FROM ${table}\nWHERE clientVersion IS NOT NULL and clientVersion != '-'\nand username != '-'\nAND $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nGROUP BY clientVersion, clientId, deviceType, username\norder by Last_Access desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Client list ; du=${__user.login}'\n"
      }
     ]
    },
    {
     "title": "Device DP",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 291 },
     "targets": [
      {
       "rawSql": "WITH f AS (\n    SELECT\n        clientVersion, clientId, username, maxOrNull(datetime) AS Last_Access\n    FROM ${table}\n    WHERE\n        clientVersion IS NOT NULL AND clientVersion != '-'\n        AND $__timeFilter(datetime)\n        AND ${generalescaping}\n        AND $__adHocFilter()\n    GROUP BY clientVersion, clientId, username\n),\nd AS (\n    SELECT antiMalwareRunning, firewallStatus, deviceName, deviceId, joinedDomains, mobileDevice, osAutoUpdate, osName, riskPostureTagsName, riskPostureTagsPassed, riskPostureTagsRemediations, riskPostureTiersName, riskPostureTiersPassed, riskPostureTiersRemediations\n    FROM ${device_table}\n    WHERE $__timeFilter(signalTimestamp) \n)\nSELECT\n    f.clientVersion, f.clientId, f.username, f.Last_Access,\n    d.antiMalwareRunning, d.firewallStatus, d.deviceName, d.joinedDomains, d.mobileDevice, d.osAutoUpdate, d.osName,\n    d.riskPostureTagsName, d.riskPostureTagsPassed, d.riskPostureTagsRemediations, d.riskPostureTiersName, d.riskPostureTiersPassed, d.riskPostureTiersRemediations\nFROM f\nANY INNER JOIN d ON f.clientId = d.deviceId\n\nSETTINGS \n    hdx_query_max_execution_time = 60, \n    hdx_query_admin_comment = 'db=${__dashboard}; dp=Device DP; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status codes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 14, "x": 0, "y": 292 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeInterval(datetime) AS time,\n    statusCode,\n    count(*) AS \"Total\"\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY time, statusCode\nORDER BY time ASC, statusCode\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Status codes; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Status codes",
     "type": "table",
     "gridPos": { "h": 11, "w": 10, "x": 14, "y": 292 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    toString(statusCode) AS statusCode,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  statusCode\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Status codes; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Error codes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 14, "x": 0, "y": 336 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeInterval(datetime) AS time,\n    errorCode,\n    count(*) AS \"Total\"\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY time, errorCode\nORDER BY time ASC, errorCode\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Error codes; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Error codes",
     "type": "table",
     "gridPos": { "h": 11, "w": 10, "x": 14, "y": 336 },
     "targets": [
      {
       "rawSql": "SELECT\n    toString(errorCode) AS errorCode,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  errorCode\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Error codes; du=${__user.login}';\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Request specs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top ${querieslimit} device OS",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 293 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    deviceOs,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  deviceOs\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} device OS; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} device type",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 293 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    deviceType,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  deviceType\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} device type; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} user agent",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 304 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    userAgent,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  userAgent\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} user agent; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} client process",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 304 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    clientProcess,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  clientProcess\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} client process; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} client IP",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 315 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    clientip,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  clientip\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} client IP; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} session ID",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 315 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    sessionId,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\n  AND sessionId != '-'\nGROUP BY  sessionId\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} session ID; du=${__user.login}';\n"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP specs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP method",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 14, "x": 0, "y": 643 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeInterval(datetime) AS time,\n    httpMethod,\n    count(*) AS \"Total\"\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY time, httpMethod\nORDER BY time ASC, httpMethod\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=HTTP method; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "HTTP Method",
     "type": "table",
     "gridPos": { "h": 11, "w": 10, "x": 14, "y": 643 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    httpMethod,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  httpMethod\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=HTTP Method; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} URL Path",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 654 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    urlPath,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  urlPath\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} URL Path; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} referer",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 654 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    referer,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  referer\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} referer; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} content type",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 665 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    contentType,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  contentType\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} content type; du=${__user.login}';\n"
      }
     ]
    },
    {
     "title": "Top ${querieslimit} HTTP version",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 665 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n    httpVer,\n    count(*) AS Total\nFROM ${table}\nWHERE $__timeFilter(datetime)\n  AND ${generalescaping}\n  AND $__adHocFilter()\n  AND username != '-'\nGROUP BY  httpVer\nORDER BY Total desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60,\n         hdx_query_admin_comment='db=${__dashboard}; dp=Top ${querieslimit} HTTP version; du=${__user.login}';\n"
      }
     ]
    }
   ]
  },
  {
   "title": "User tracking for User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last ${querieslimit} login list",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 295 },
     "targets": [
      {
       "rawSql": "SELECT datetime, username, apphost, clientip, cloudZone, geoCountry, geoCity, userAgent\nFROM ${table} \nWHERE $__timeFilter(datetime)\nAND ${generalescaping}\nAND $__adHocFilter() \n\nAND (\n  urlPath = '/saml/sp/response'\n  AND\n  idpinfo = 'UNSPEC|D'\n  AND\n  username != '-'\n)\n\nAND username != '-'\norder by datetime desc\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last ${querieslimit} login list; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Failed logins",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 310 },
     "targets": [
      {
       "rawSql": "SELECT  datetime, username, apphost, denyReason, statusCode, clientip, cloudZone, geoCountry, geoCity, userAgent\nFROM ${table} \nWHERE $__timeFilter(datetime) \nAND ${generalescaping}\nAND $__adHocFilter() \nAND ( denyReason IS NOT NULL ) \nAND idpinfo IN ('LOGIN|F', 'MFA|MF')\norder by datetime desc\n--limit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Failed Logins list; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Last ${querieslimit} access logs ",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 325 },
     "targets": [
      {
       "rawSql": "SELECT datetime, \n      username,\n       origin,\n       apphost,\n       clientip, \n       cloudZone, \n       geoCountry, \n       geoCity, \n       originRespTime, \n       totalRespTime, \n       errorCode,\n       httpMethod,\n       httpVerb2,\n       idpinfo,\n       referer,\n       sessionId,\n       sessionInfo,\n       statusCode,\n       urlPath,\n       userAgent,\n       IF(clientId != '-', 'tunnel', 'application') AS application_type\n       FROM ${table}\nWHERE $__timeFilter(datetime)\nAND ${generalescaping}\nAND $__adHocFilter() \nAND username != '-'\n--AND origin != '-'\n--AND apphost != '-'\nORDER BY datetime DESC\nlimit ${querieslimit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Last ${querieslimit} access logs ; du=${__user.login}'\n"
      }
     ]
    }
   ]
  }
 ]
}