{
 "title": "HDX Cloudflare Recreation",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "table", "query": "${VAR_TABLE}" },
   { "name": "timestamp", "query": "${VAR_TIMESTAMP}" },
   {
    "name": "time_agg",
    "query": "SELECT\n    CASE\n        WHEN ${duration} <= 1 THEN 'toStartOfMinute(${timestamp})'\n        WHEN ${duration} <= 6 THEN 'toStartOfFiveMinutes(${timestamp})'\n        WHEN ${duration} <= 24 THEN 'toStartOfFifteenMinutes(${timestamp})'\n        ELSE 'toStartOfHour(${timestamp})'\n    END"
   },
   {
    "name": "duration",
    "query": "SELECT datediff('h', $__fromTime, $__toTime)"
   },
   {
    "name": "main_panel_select",
    "label": "Focus",
    "query": "Requests : ${requests_select}\\, ${time_agg} as min,Data Transfer : ${data_transfer_select}\\, ${time_agg} as min,Page Views : ${page_views_select}\\, ${time_agg} as min,Visits : ${visits_select}\\, ${time_agg} as min,API Requests : ${api_requests_select}\\, ${time_agg} as min"
   },
   {
    "name": "main_panel_filters",
    "label": "Detailed Breakdown",
    "query": "SELECT CASE\n  WHEN '${main_panel_select:text}' = 'Page Views' THEN ${page_views_filter:sqlstring}\n  WHEN '${main_panel_select:text}' = 'Visits' THEN ${visits_filter:sqlstring}\n  WHEN '${main_panel_select:text}' = 'API Requests' THEN ${api_requests_filter:sqlstring}\n  ELSE '1=1'\nEND"
   },
   {
    "name": "group_by",
    "label": "Group By",
    "query": "Referer host : request_referer, Host : request_host, Country : client_country_iso_code, Path : request_full_path, Edge status code : response_status_code, Source IP : client_ip, HTTP version : request_protocol, Cache status : clf_cache_cache_status, Source ASN : client_asn"
   },
   { "name": "requests_select", "query": "${VAR_REQUESTS_SELECT}" },
   { "name": "page_views_select", "query": "${VAR_PAGE_VIEWS_SELECT}" },
   { "name": "page_views_filter", "query": "${VAR_PAGE_VIEWS_FILTER}" },
   { "name": "visits_select", "query": "${VAR_VISITS_SELECT}" },
   { "name": "visits_filter", "query": "${VAR_VISITS_FILTER}" },
   { "name": "api_requests_select", "query": "${VAR_API_REQUESTS_SELECT}" },
   { "name": "api_requests_filter", "query": "${VAR_API_REQUESTS_FILTER}" },
   { "name": "data_transfer_select", "query": "${VAR_DATA_TRANSFER_SELECT}" },
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "Main Panel: ${main_panel_select:text}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT toString(${group_by}) as grouping,\n  ${main_panel_select}\nFROM ${table}\nWHERE $__timeFilter(timestamp)\n  AND $__adHocFilter() \n  AND ${main_panel_filters}\nGROUP BY min, grouping\nORDER BY grouping, min ASC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Main Panel; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT toString(${group_by}) as grouping, count() AS \"Total Requests\", ${time_agg} as min\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter() \nGROUP BY min, grouping\nORDER BY grouping, min ASC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Requests; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Page Views",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT toString(${group_by}) as grouping, count() as \"Total Views\", ${time_agg} as min\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter() \n  AND ${page_views_filter}\nGROUP BY min, grouping\nORDER BY grouping, min ASC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Page Views; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "Visits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT toString(${group_by}) as grouping, count() as \"Total Visits\", ${time_agg} as min\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter() \n  AND ${visits_filter}\nGROUP BY min, grouping\nORDER BY grouping, min ASC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Visits; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT toString(${group_by}) as grouping, count() as \"Total API Requests\", ${time_agg} as min\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter() \n  AND ${api_requests_filter}\nGROUP BY min, grouping\nORDER BY grouping, min ASC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=API Requests; du=${__user.login}'\n"
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT toString(${group_by}) as grouping, sum(request_total_bytes) as \"Total data transfer\", ${time_agg} as min\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter() \nGROUP BY min, grouping\nORDER BY grouping, min ASC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Data Transfer; du=${__user.login}'\n"
    }
   ]
  },
  { "title": "Detailed Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Country Map",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT client_country_iso_code AS Country, count() AS Count \nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter()\n  AND ${main_panel_filters} \nGROUP BY client_country_iso_code\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Requests volume by client_country_iso_code; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Referer",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT request_referer AS Referer, count() AS Count\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter()\n  AND ${main_panel_filters} \nGROUP BY request_referer\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Referers; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Path",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT request_full_path AS Path, count() AS Count\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter()\n  AND ${main_panel_filters} \nGROUP BY request_full_path\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Paths; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Hostname",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT request_host AS Hostname, count() AS Count\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter()\n  AND ${main_panel_filters} \nGROUP BY request_host\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Hosts; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Client Device Type",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT toString(clf_client_device_type) AS \"Client Device Type\", count() AS Count\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter()\n  AND ${main_panel_filters} \nGROUP BY clf_client_device_type\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Client Device Type; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Client ASN",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT toString(client_asn) AS \"Client ASN\", count() AS Count \nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter()\n  AND ${main_panel_filters} \nGROUP BY client_asn\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Client ASN; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Client IP",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT toString(client_ip) AS \"Client IP\", count() AS Count \nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter()\n  AND ${main_panel_filters} \nGROUP BY client_ip\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Source IPs; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Country",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT client_country_iso_code AS Country, count() AS Count \nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter()\n  AND ${main_panel_filters} \nGROUP BY client_country_iso_code\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Country Count; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT request_protocol AS \"HTTP Version\", count() AS Count \nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter()\n  AND ${main_panel_filters} \nGROUP BY request_protocol\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=HTTP Versions; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT toString(response_status_code) AS \"HTTP Status Code\", count() AS Count \nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter()\n  AND ${main_panel_filters} \nGROUP BY response_status_code\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Edge status codes; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "User Agent",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT request_user_agent AS \"User Agent\", count() AS Count \nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter()\n  AND ${main_panel_filters} \nGROUP BY request_user_agent\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Source user agents; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Data Center",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT edge_pop AS \"Data Center\", count() AS Count \nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter()\n  AND ${main_panel_filters} \nGROUP BY edge_pop\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Data Center; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Cache Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT clf_cache_cache_status AS \"Cache Status\", count() AS Count \nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter()\n  AND ${main_panel_filters} \nGROUP BY clf_cache_cache_status\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Cache statuses; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "X-Requested-With Headers",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT clf_client_x_requested_with AS \"X-Requested-With Headers\", count() AS Count \nFROM ${table}\nWHERE $__timeFilter(${timestamp})\n  AND $__adHocFilter()\n  AND ${main_panel_filters} \nGROUP BY clf_client_x_requested_with\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=X-Requested-With Headers; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "logs",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "rawSql": "SELECT *\t\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter() \nORDER BY ${timestamp} DESC\nLIMIT 1000"
      }
     ]
    }
   ]
  }
 ]
}