{
 "title": "Akamai SIEM",
 "description": "Akamai SIEM powered by Hydrolix dashboard for security analytics\r\n",
 "tags": [
  "v0.9",
  "Security",
  "SIEM"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "table", "query": "${VAR_TABLE}" },
   { "name": "logs", "query": "${VAR_LOGS}" },
   {
    "name": "host",
    "label": "Host",
    "query": "SELECT DISTINCT count() as count, host\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nGROUP BY host ORDER BY count DESC LIMIT 50"
   },
   {
    "name": "method",
    "label": "Method",
    "query": "SELECT DISTINCT count() as count, method\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nGROUP BY method ORDER BY count DESC LIMIT 50"
   },
   {
    "name": "status",
    "label": "Status Code",
    "query": "200,201,202,204,205,206,301,302,304,307,308,400,401,403,404,405,406,408,409,410,411,412,413,414,415,416,417,421,425,428,429,431,451,500,501,502,503,504,505,506,511"
   },
   {
    "name": "clientIP",
    "label": "Client IP",
    "query": "SELECT DISTINCT count() as count, clientIP\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nGROUP BY clientIP ORDER BY count DESC LIMIT 50"
   },
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT DISTINCT count() as count, country\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nGROUP BY country ORDER BY count DESC LIMIT 50"
   },
   {
    "name": "ruleActions",
    "label": "Rule Action",
    "query": "monitor, alert, allow, tarpit, deny"
   },
   { "name": "message", "label": "Rule Message" },
   { "name": "tags", "label": "Rule Tags" },
   { "name": "path", "label": "Path" },
   { "name": "requestHeadersName", "label": "requestHeaders Name" },
   { "name": "responseHeadersName", "label": "responseHeaders Name" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Traffic vs SIEM Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(reqTimeSec) as time,\ncount() as total\nFROM ${logs}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${status:sqlstring}), $status)\nAND $__conditionalAll( reqHost IN (${host:sqlstring}), $host)\nAND $__conditionalAll( reqMethod IN (${method:sqlstring}), $method)\nAND $__conditionalAll( reqPath IN (${path:sqlstring}), $path)\nAND $__conditionalAll( cliIP IN (${clientIP:sqlstring}), $clientIP)\nAND $__conditionalAll( country IN (${country:sqlstring}), $country)\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Total Traffic vs SIEM Traffic; du=${__user.login}'"
    },
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time,\ncount() as total\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__conditionalAll(host IN (${host:sqlstring}), $host)\nAND $__conditionalAll(method IN (${method:sqlstring}), $method)\nAND $__conditionalAll(status IN (${status:sqlstring}), $status)\nAND $__conditionalAll(country IN (${country:sqlstring}), $country)\nAND $__conditionalAll(clientIP IN (${clientIP:sqlstring}), $clientIP)\nAND $__conditionalAll(path IN (${path:sqlstring}), $path)\nAND $__conditionalAll(arrayJoin(ruleMessages)  ILIKE '%${message}%', $message)\nAND $__conditionalAll(arrayJoin(ruleTags) ILIKE '%${tags}%', $tags)\nAND $__conditionalAll(arrayJoin(ruleActions) ILIKE '%${ruleActions}%', $ruleActions)\nAND if ('${requestHeadersName:text}' = '', true, mapContainsKeyLike(requestHeaders, '%${requestHeadersName:text}%'))\nAND if ('${responseHeadersName:text}' = '', true, mapContainsKeyLike(responseHeaders, '%${responseHeadersName:text}%'))\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Total Traffic vs SIEM Traffic; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "SIEM Logs Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT arrayJoin(ruleActions) as ruleAction,\ncount(),\n$__timeInterval(timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__conditionalAll(host IN (${host:sqlstring}), $host)\nAND $__conditionalAll(method IN (${method:sqlstring}), $method)\nAND $__conditionalAll(status IN (${status:sqlstring}), $status)\nAND $__conditionalAll(country IN (${country:sqlstring}), $country)\nAND $__conditionalAll(clientIP IN (${clientIP:sqlstring}), $clientIP)\nAND $__conditionalAll(path IN (${path:sqlstring}), $path)\nAND $__conditionalAll(arrayJoin(ruleMessages)  ILIKE '%${message}%', $message)\nAND $__conditionalAll(arrayJoin(ruleTags) ILIKE '%${tags}%', $tags)\nAND $__conditionalAll(arrayJoin(ruleActions) ILIKE '%${ruleActions}%', $ruleActions)\nAND if ('${requestHeadersName:text}' = '', true, mapContainsKeyLike(requestHeaders, '%${requestHeadersName:text}%'))\nAND if ('${responseHeadersName:text}' = '', true, mapContainsKeyLike(responseHeaders, '%${responseHeadersName:text}%'))\nGROUP BY time, ruleAction\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=SIEM Logs Count; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "SIEM Logs per Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT toString(status) as status_code, count(),\n$__timeInterval(timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__conditionalAll(host IN (${host:sqlstring}), $host)\nAND $__conditionalAll(method IN (${method:sqlstring}), $method)\nAND $__conditionalAll(status IN (${status:sqlstring}), $status)\nAND $__conditionalAll(country IN (${country:sqlstring}), $country)\nAND $__conditionalAll(clientIP IN (${clientIP:sqlstring}), $clientIP)\nAND $__conditionalAll(path IN (${path:sqlstring}), $path)\nAND $__conditionalAll(arrayJoin(ruleMessages)  ILIKE '%${message}%', $message)\nAND $__conditionalAll(arrayJoin(ruleTags) ILIKE '%${tags}%', $tags)\nAND $__conditionalAll(arrayJoin(ruleActions) ILIKE '%${ruleActions}%', $ruleActions)\nAND if ('${requestHeadersName:text}' = '', true, mapContainsKeyLike(requestHeaders, '%${requestHeadersName:text}%'))\nAND if ('${responseHeadersName:text}' = '', true, mapContainsKeyLike(responseHeaders, '%${responseHeadersName:text}%'))\nGROUP BY time, status_code\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=SIEM Logs per Status Code; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 100 Message",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT count(),\narrayJoin(ruleMessages) AS message\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__conditionalAll(host IN (${host:sqlstring}), $host)\nAND $__conditionalAll(method IN (${method:sqlstring}), $method)\nAND $__conditionalAll(status IN (${status:sqlstring}), $status)\nAND $__conditionalAll(country IN (${country:sqlstring}), $country)\nAND $__conditionalAll(clientIP IN (${clientIP:sqlstring}), $clientIP)\nAND $__conditionalAll(path IN (${path:sqlstring}), $path)\nAND $__conditionalAll(arrayJoin(ruleMessages)  ILIKE '%${message}%', $message)\nAND $__conditionalAll(arrayJoin(ruleTags) ILIKE '%${tags}%', $tags)\nAND $__conditionalAll(arrayJoin(ruleActions) ILIKE '%${ruleActions}%', $ruleActions)\nAND if ('${requestHeadersName:text}' = '', true, mapContainsKeyLike(requestHeaders, '%${requestHeadersName:text}%'))\nAND if ('${responseHeadersName:text}' = '', true, mapContainsKeyLike(responseHeaders, '%${responseHeadersName:text}%'))\nGROUP BY message\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 100 Message; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 100 Tags",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT count(),\narrayJoin(ruleTags) AS tags\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__conditionalAll(host IN (${host:sqlstring}), $host)\nAND $__conditionalAll(method IN (${method:sqlstring}), $method)\nAND $__conditionalAll(status IN (${status:sqlstring}), $status)\nAND $__conditionalAll(country IN (${country:sqlstring}), $country)\nAND $__conditionalAll(clientIP IN (${clientIP:sqlstring}), $clientIP)\nAND $__conditionalAll(path IN (${path:sqlstring}), $path)\nAND $__conditionalAll(arrayJoin(ruleMessages)  ILIKE '%${message}%', $message)\nAND $__conditionalAll(arrayJoin(ruleTags) ILIKE '%${tags}%', $tags)\nAND $__conditionalAll(arrayJoin(ruleActions) ILIKE '%${ruleActions}%', $ruleActions)\nAND if ('${requestHeadersName:text}' = '', true, mapContainsKeyLike(requestHeaders, '%${requestHeadersName:text}%'))\nAND if ('${responseHeadersName:text}' = '', true, mapContainsKeyLike(responseHeaders, '%${responseHeadersName:text}%'))\nGROUP BY tags\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 100 Tags; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 100 Path",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT count(),\npath\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__conditionalAll(host IN (${host:sqlstring}), $host)\nAND $__conditionalAll(method IN (${method:sqlstring}), $method)\nAND $__conditionalAll(status IN (${status:sqlstring}), $status)\nAND $__conditionalAll(country IN (${country:sqlstring}), $country)\nAND $__conditionalAll(clientIP IN (${clientIP:sqlstring}), $clientIP)\nAND $__conditionalAll(path IN (${path:sqlstring}), $path)\nAND $__conditionalAll(arrayJoin(ruleMessages)  ILIKE '%${message}%', $message)\nAND $__conditionalAll(arrayJoin(ruleTags) ILIKE '%${tags}%', $tags)\nAND $__conditionalAll(arrayJoin(ruleActions) ILIKE '%${ruleActions}%', $ruleActions)\nAND if ('${requestHeadersName:text}' = '', true, mapContainsKeyLike(requestHeaders, '%${requestHeadersName:text}%'))\nAND if ('${responseHeadersName:text}' = '', true, mapContainsKeyLike(responseHeaders, '%${responseHeadersName:text}%'))\nGROUP BY path\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 100 Path; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 100 Client IP",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT count(),\nclientIP\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__conditionalAll(host IN (${host:sqlstring}), $host)\nAND $__conditionalAll(method IN (${method:sqlstring}), $method)\nAND $__conditionalAll(status IN (${status:sqlstring}), $status)\nAND $__conditionalAll(country IN (${country:sqlstring}), $country)\nAND $__conditionalAll(clientIP IN (${clientIP:sqlstring}), $clientIP)\nAND $__conditionalAll(path IN (${path:sqlstring}), $path)\nAND $__conditionalAll(arrayJoin(ruleMessages)  ILIKE '%${message}%', $message)\nAND $__conditionalAll(arrayJoin(ruleTags) ILIKE '%${tags}%', $tags)\nAND $__conditionalAll(arrayJoin(ruleActions) ILIKE '%${ruleActions}%', $ruleActions)\nAND if ('${requestHeadersName:text}' = '', true, mapContainsKeyLike(requestHeaders, '%${requestHeadersName:text}%'))\nAND if ('${responseHeadersName:text}' = '', true, mapContainsKeyLike(responseHeaders, '%${responseHeadersName:text}%'))\nGROUP BY clientIP\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 100 Client IP; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 100 Host",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT count(),\nhost\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__conditionalAll(host IN (${host:sqlstring}), $host)\nAND $__conditionalAll(method IN (${method:sqlstring}), $method)\nAND $__conditionalAll(status IN (${status:sqlstring}), $status)\nAND $__conditionalAll(country IN (${country:sqlstring}), $country)\nAND $__conditionalAll(clientIP IN (${clientIP:sqlstring}), $clientIP)\nAND $__conditionalAll(path IN (${path:sqlstring}), $path)\nAND $__conditionalAll(arrayJoin(ruleMessages)  ILIKE '%${message}%', $message)\nAND $__conditionalAll(arrayJoin(ruleTags) ILIKE '%${tags}%', $tags)\nAND $__conditionalAll(arrayJoin(ruleActions) ILIKE '%${ruleActions}%', $ruleActions)\nAND if ('${requestHeadersName:text}' = '', true, mapContainsKeyLike(requestHeaders, '%${requestHeadersName:text}%'))\nAND if ('${responseHeadersName:text}' = '', true, mapContainsKeyLike(responseHeaders, '%${responseHeadersName:text}%'))\nGROUP BY host\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Top 100 Host; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Geo Map",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Geo Map",
     "type": "geomap",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT country, count()\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__conditionalAll(host IN (${host:sqlstring}), $host)\nAND $__conditionalAll(method IN (${method:sqlstring}), $method)\nAND $__conditionalAll(status IN (${status:sqlstring}), $status)\nAND $__conditionalAll(country IN (${country:sqlstring}), $country)\nAND $__conditionalAll(clientIP IN (${clientIP:sqlstring}), $clientIP)\nAND $__conditionalAll(path IN (${path:sqlstring}), $path)\nAND $__conditionalAll(arrayJoin(ruleMessages)  ILIKE '%${message}%', $message)\nAND $__conditionalAll(arrayJoin(ruleTags) ILIKE '%${tags}%', $tags)\nAND $__conditionalAll(arrayJoin(ruleActions) ILIKE '%${ruleActions}%', $ruleActions)\nAND if ('${requestHeadersName:text}' = '', true, mapContainsKeyLike(requestHeaders, '%${requestHeadersName:text}%'))\nAND if ('${responseHeadersName:text}' = '', true, mapContainsKeyLike(responseHeaders, '%${responseHeadersName:text}%'))\nGROUP BY country\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Geo Map; du=${__user.login}'"
      }
     ]
    }
   ]
  }
 ]
}