{
 "title": "Security Analysis",
 "description": "Web Security Analytics on TrafficPeak",
 "tags": [
  "Security",
  "SIEM",
  "v0.9"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "table", "query": "${VAR_TABLE}" },
   { "name": "timestamp", "query": "${VAR_TIMESTAMP}" },
   {
    "name": "attack_type",
    "label": "Attack Type",
    "query": "WAF, DoS, Reputation, Bot, Custom"
   },
   {
    "name": "ruleActions",
    "label": "Rule Action",
    "query": "monitor, alert, allow, tarpit, delay, deny, slow, serve_alt_4361"
   },
   {
    "name": "ruleTags",
    "label": "Rule Tags",
    "query": "SELECT DISTINCT arrayJoin(ruleTags) as tags\nFROM ${table}\nWHERE ${timestamp} > now() - INTERVAL 1 HOUR\nGROUP BY tags\nORDER BY COUNT() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=ruleTags; du=${__user.login}'"
   },
   {
    "name": "ruleMessages",
    "label": "Rule Messages",
    "query": "SELECT DISTINCT \narrayJoin(ruleMessages) as messages\nFROM ${table}\nWHERE ${timestamp} > now() - INTERVAL 1 HOUR\nGROUP BY messages\nORDER BY COUNT() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=ruleMessages; du=${__user.login}'"
   },
   {
    "name": "rulesID",
    "label": "Rule ID",
    "query": "SELECT DISTINCT \narrayJoin(rules) as rules\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nGROUP BY rules\nORDER BY COUNT() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=rulesIDs; du=${__user.login}'"
   },
   {
    "name": "ruleSelectors",
    "label": "Rule Selector",
    "query": "SELECT DISTINCT \narrayJoin(ruleSelectors) as selector\nFROM ${table}\nWHERE ${timestamp} > now() - INTERVAL 1 HOUR\nAND notEmpty(selector)\nGROUP BY selector\nORDER BY COUNT() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=ruleSelectors; du=${__user.login}'"
   },
   {
    "name": "ruleData",
    "label": "Rule Data",
    "query": "SELECT DISTINCT \narrayJoin(ruleData) as data\nFROM ${table}\nWHERE ${timestamp} > now() - INTERVAL 1 HOUR\nAND notEmpty(data)\nGROUP BY data\nORDER BY COUNT() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; var=ruleData; du=${__user.login}'"
   },
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background-color: #990000; color: #CCCCCC; padding: 15px; padding-bottom: 0; border-radius: 5px 5px 0 0;\">\n      <h1 style=\"color: #CCCCCC; margin-top: 0;\">Akamai / Hydrolix Internal - Please read:</h1>\n  <br><p style=\"color: #CCCCCC;\">This <b>TrafficPeak Certified Reference <i>Security Analysus</i></b> dashboard has SIEM table dependencies and requires additional configuration after importing it manually to a customer's Grafana organization in order to work correctly.</p>\n\n  <p style=\"color: #CCCCCC; margin-bottom: 0;\">If you would like to provide a customer with this particular dashboard or an entire set of TrafficPeak Certified Reference dashboards, we highly recommend reaching out to Hydrolix support via <a href=\"mailto:akamai-ps@hydrolix.io\">akamai-ps@hydrolix.io</a> to ensure all dependencies are met and the dashboards are configured as needed.</p>\n  <p style=\"color: #CCCCCC; margin-bottom: 0;\">In case you really need to manually import this dashboard to a customer's Grafana organisation and you are sure all dependencies are already in place, please find the instructions below. Please read and follow the instructions carefully.</p>\n</div>\n<details style=\"margin-top: 0; margin-bottom: 0;\">\n<summary style=\"cursor: pointer; font-weight: bold; background-color: #990000; color: #CCCCCC; padding: 15px; margin-top: 0; margin-bottom: 0;\">Click to expand instructions</summary>\n<div style=\"background-color: #990000; color: #CCCCCC; padding: 15px; padding-top: 0; border-radius: 5px 5px 0 0; margin-top: 0;\">\n      <h3 style=\"color: #CCCCCC; margin-top: 0;\">Steps to export the dashboard</h3>\n  <ul style=\"color: #CCCCCC;\">\n    <li>Click on the \"Export\" button in the top right section of the dashboard, then click on \"Export as JSON\"</li>\n    <li>In the sidebar that opened, enable the toggle to \"Export the dashboard to use in another instance\"</li>\n    <li>Click on \"Download file\" to download a copy of the JSON file to your computer</li>\n  </ul>\n<br>\n  <h3 style=\"color: #CCCCCC;\">Steps to import the dashboard</h3>\n  <ul style=\"color: #CCCCCC;\">\n    <li>Go to the customer's Grafana organisation and navigate to the \"TrafficPeak Certified Reference Dashboards\" / \"Security\" folder</li>\n    <li>Click on the \"New\" button, then click \"Import\"</li>\n    <li>Click on the \"Upload dashboard JSON file\" banner and select the dashboard JSON file you downloaded in the steps described above</li>\n    <li>In the \"Import dashboard\" page, it is necessary to adjust some variables depending on the customer type (dedicated or shared):\n      <ul>\n        <li>Do not change the name, folder or UID of the dashboard</li>\n        <li>Select the \"hydrolix-hydrolix-datasource\" available (there should only be one available option per customer)</li>\n        <li><i>Table</i> variable configuration:\n          <ul>\n            <li>For <b>dedicated</b> customers, leave all values as-is</li>\n<li>For <b>shared</b> customers, please replace the values for the variables mentioned below with the following values (replacing example <i>customer_x</i> with the correct shared customer name): \n<br>\n <br> <table style=\"border-collapse: collapse; margin-left: 20px;\">\n    <tr>\n      <th style=\"background-color: #990000; border: 1px solid #CCCCCC; padding: 8px; text-align: left;\"><b>Variable</b></th>\n      <th style=\"background-color: #990000; border: 1px solid #CCCCCC; padding: 8px; text-align: left;\"><b>Value</b></th>\n    </tr>    \n    <tr>\n      <td style=\"border: 1px solid #CCCCCC; padding: 8px;\"><b>table</b></td>\n      <td style=\"border: 1px solid #CCCCCC; padding: 8px;\"><i>customer_x.siem</i></td>\n    </tr>\n  </table>\n</li>    \n          </ul>\n        </li>\n      </ul>\n    </li>\n      <p><li>Double check all inputs are in-line with the steps above, then click on \"Import\"</li></p>\n  </ul>\n<br>\n  <h3 style=\"color: #CCCCCC;\">Additional configuration</h3>\n  <p style=\"color: #CCCCCC;\">Due to a Grafana bug, there is an additional configuration step needed to make the new adhoc-filter work as expected:</p>\n  <ul style=\"color: #CCCCCC;\">\n    <li>Click on \"Edit\" in the top right section of the dashboard, then click on \"Settings\"</li>\n    <li>Click on the \"Variables\" tab, then click on the \"filter\" variable</li>\n    <li>Under the \"Ad-hoc options\", click on the \"Data Source\" dropdown menu and select the available Hydrolix data source</li>\n    <li>Now click on \"Save dashboard\" in the top right section, then click on the \"Save\" button in the right side menu bar that opened up</li>\n    <li>Re-open the dashboard and confirm the adhoc-filter is working as expected:\n      <ul>\n        <li>Click on the \"Filter by label values\" text box of the adhoc-filter in the top left section of the dashboard</li>\n        <li>Verify that a list of columns appears</li>\n        <li>If you see \"An error has occurred fetching labels. Click to retry\", please ensure you have performed the steps outlined above</li>\n      </ul>\n    </li>\n    <li>If you keep seeing the adhoc-filter error or any other unexpected behavior like panels not able to query the data, please reach out to the Hydrolix support (<a href=\"mailto:akamai-support@hydrolix.io\">akamai-support@hydrolix.io</a>), ideally including a screenshot and the error messages you are seeing.</li>\n  </ul>\n <br>\n  <h3 style=\"color: #CCCCCC;\">Banner Removal</h3>\n\n  <p style=\"color: #CCCCCC;\">Once the dashboard has been confirmed to be working as expected (including the adhoc-filter), it is essential to remove this informational banner:</p>\n  <ul style=\"color: #CCCCCC;\">\n    <li>Click on \"Edit\" in the top right section of the dashboard</li>\n    <li>Click on the three-dot menu on the top right corner of <b>this</b> text panel</li>\n    <li>Click on \"Remove\"</li>\n    <li>Now click on \"Save dashboard\" in the top right section, then click on the \"Save\" button in the ride side menu bar that opened up</li>\n  </ul>\n  </div>\n</details>\n<div style=\"background-color: #990000; color: #CCCCCC; padding: 15px; padding-top: 0; margin-top: 0;\"></div>\n<div style=\"background-color: #990000; color: #CCCCCC; padding: 15px; padding-top: 0; margin-top: 0;\"></div>  "
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "##  Security Analysis\n\nSIEM (Security Information and Event Management) is a comprehensive security solution that aggregates, analyzes, and correlates security data from across an organization's IT infrastructure in real-time"
   }
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Attack by Hostname",
   "type": "timeseries",
   "description": "Attack by Hostname by time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n\thost,\n\t$__timeInterval(timestamp) as time,\n\tcount()\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY time, host\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Attack by Hostname; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Rule Action Count",
   "type": "timeseries",
   "description": "Rule Action Count by time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT arrayJoin(arrayIntersect([${ruleActions:sqlstring}], ruleActions) ) as ruleAction,\n$__timeInterval(timestamp) as time,\ncount()\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY time, ruleAction\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Rule Action Count; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Attack Groups (Excluding Bot)",
   "type": "timeseries",
   "description": "High-level categories that organize multiple related attack types based on their nature and threat vector",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT arrayJoin(arrayFilter( x -> x != 'Bot', arrayIntersect([${attack_type:sqlstring}], attackTypes))) as attack,\ncount(),\n$__timeInterval(timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY time, attack\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Attack Groups (Excluding Bot); du=${__user.login}'"
    }
   ]
  },
  {
   "title": "WAF",
   "type": "timeseries",
   "description": "Attacks targeting web applications - SQL injection, XSS, path traversal by time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT arrayJoin(arrayMap( x -> if(position(x,':') !=0, 'Record Header', x), ruleTagsWAF)) as tag,\ncount(),\n$__timeInterval(timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND attack_waf = 1\nGROUP BY time, tag\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=WAF; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "DoS",
   "type": "timeseries",
   "description": "Attacks attempting to overwhelm systems/networks with traffic to make services unavailable.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT arrayJoin(arrayMap( x -> if(position(x,':') !=0, 'Record Header', x), ruleTagsDOS)) as tag,\ncount(),\n$__timeInterval(timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND attack_dos = 1\nGROUP BY time, tag\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=DoS; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Reputation",
   "type": "timeseries",
   "description": "Threats identified based on known malicious IP addresses, domains, or file hashes from threat intelligence feeds  by time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT ruleMessage,\ncount(),\n$__timeInterval(timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND isNotNull(ruleMessage)\nAND attack_reputation\nGROUP BY time, ruleMessage\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Reputation; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Bot",
   "type": "timeseries",
   "description": "Automated malicious activity - credential stuffing, scraping, spam bots, malicious crawlers",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT arrayJoin(arrayMap( x -> if(position(x,':') !=0, 'Record Header', x), ruleTagsBot)) as tag,\ncount(),\n$__timeInterval(timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND attack_bot\nGROUP BY time, tag\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Bot; du=${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 100 Rankings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host",
     "type": "table",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT count() as count,\nhost\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY host\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Host; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Path",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 4, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT count() as count,\npath\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY path\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Path; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Country",
     "type": "table",
     "gridPos": { "h": 9, "w": 3, "x": 10, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT count() as count,\ncountry\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY country\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Country; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "AS Number",
     "type": "table",
     "gridPos": { "h": 9, "w": 3, "x": 13, "y": 139 },
     "targets": [
      {
       "rawSql": "SELECT count() as count,\nasn\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY asn\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=AS Number; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Client IP",
     "type": "table",
     "gridPos": { "h": 9, "w": 4, "x": 16, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT count() as count,\nclientIP\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY clientIP\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Client IP; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Rule ID",
     "type": "table",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 139 },
     "targets": [
      {
       "rawSql": "SELECT\n  count() as count, rule\nFROM ${table}\nARRAY JOIN arrayDistinct( rules ) AS rule\nWHERE $__timeFilter(${timestamp})\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(rule IN (${rulesID:sqlstring}), ${rulesID})\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY rule\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Rule ID; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Rule Tag",
     "type": "table",
     "gridPos": { "h": 11, "w": 5, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT\n  count() as count, \n  arrayJoin(arrayDistinct(arrayMap( x ->  if (position(x , ':') !=0, 'Record Header', x), ruleTags))) AS tag\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(tag IN (${ruleTags:sqlstring}), ${ruleTags})\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY tag\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Rule Tag; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Rule Message",
     "type": "table",
     "gridPos": { "h": 11, "w": 6, "x": 5, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT count() as count,\narrayJoin(ruleMessages) AS message\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(message IN (${ruleMessages:sqlstring}), ${ruleMessages})\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY message\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Rule Message; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "User-Agent",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 11, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT count() as count, UA, REPLACE(UA, ',', '__gfc__') AS escaped_UA\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY UA\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=User-Agent; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Sec-CH-UA",
     "type": "table",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT count() as count,\nCH_UA,\nREPLACE(CH_UA, ',', '__gfc__') AS escaped_CH_UA\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nAND has_CH_UA\nGROUP BY CH_UA\nORDER BY count() DESC\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Sec-CH-UA; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Samples - request-level view",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Samples",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 243 },
     "targets": [
      {
       "rawSql": "SELECT requestId, formatDateTime(timestamp, '%F %T') AS Time, clientIP, asn, country, method, protocol, host, path, status, ruleActions, ruleTags\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Samples; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Headers",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 254 },
     "targets": [
      {
       "rawSql": "SELECT toString(requestHeaders) AS RequestHeaders, toString(responseHeaders) AS ResponseHeaders\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nLIMIT 1\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Headers; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Details",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 258 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT requestId, (arrayJoin(arrayZip(ruleActions, ruleTags, ruleMessages, ruleSelectors, ruleData)) as t).1 as action,\nt.2 as tag,\nt.3 as message,\nt.4 as selector,\nt.5 as data\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(action IN (${ruleActions:sqlstring}), ${ruleActions})\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(message IN (${ruleMessages:sqlstring}), ${ruleMessages})\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(tag IN (${ruleTags:sqlstring}), ${ruleTags})\nAND $__conditionalAll(selector IN (${ruleSelectors:sqlstring}), ${ruleSelectors})\nAND $__conditionalAll(data IN (${ruleData:sqlstring}), ${ruleData})\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Details; du=${__user.login}'"
      }
     ]
    },
    {
     "title": "Raw Log by requestId",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 267 },
     "targets": [
      {
       "rawSql": "SELECT requestId, * EXCEPT (requestId)\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nLIMIT 1\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Raw Log by requestId; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Count by Geo Map",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hits per Country",
     "type": "geomap",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 302 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT country, count() as count\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nGROUP BY country\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Geo Map; du=${__user.login}'"
      }
     ]
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Logs",
     "type": "logs",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 532 },
     "targets": [
      {
       "rawSql": "SELECT ruleActions, * EXCEPT(ruleActions)\nFROM ${table}\nWHERE $__timeFilter(${timestamp})\nAND $__adHocFilter()\nAND $__conditionalAll(hasAny([${ruleActions:sqlstring}], ruleActions), $ruleActions)\nAND $__conditionalAll(hasAny([${attack_type:sqlstring}], attackTypes), $attack_type)\nAND $__conditionalAll(hasAny([${ruleMessages:sqlstring}], ruleMessages), $ruleMessages)\nAND $__conditionalAll(hasAny([${rulesID:sqlstring}], rules), $rulesID)\nAND $__conditionalAll(hasAny([${ruleTags:sqlstring}], ruleTags), $ruleTags)\nAND $__conditionalAll(hasAny([${ruleSelectors:sqlstring}], ruleSelectors), $ruleSelectors)\nAND $__conditionalAll(hasAny([${ruleData:sqlstring}], ruleData), $ruleData)\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='db=${__dashboard}; dp=Raw Logs; du=${__user.login}'"
      }
     ]
    }
   ]
  }
 ]
}