{
 "title": "Cascade - Cloudfront",
 "time": { "from": "now-1h", "to": "now-1m" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "response_status_code",
    "label": "HTTP Status Code",
    "query": "200,201,202,204,205,206,301,302,304,307,308,400,401,403,404,405,406,408,409,410,411,412,413,414,415,416,417,421,425,428,429,431,451,500,501,502,503,504,505,506,511"
   },
   {
    "name": "request_host",
    "label": "Request Host",
    "query": "SELECT arrayJoin(topK(50)(request_host))\nFROM __TABLE__ WHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}"
   },
   {
    "name": "request_method",
    "label": "Request Method",
    "query": "SELECT arrayJoin(topK(50)(request_method))\nFROM __TABLE__ WHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}"
   },
   {
    "name": "response_content_type",
    "label": "Content Type",
    "query": "SELECT arrayJoin(topK(50)(response_content_type))\nFROM __TABLE__ WHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}"
   },
   {
    "name": "cache_behavior_path_pattern",
    "label": "Cache Config Pattern",
    "query": "SELECT arrayJoin(topK(50)(cache_behavior_path_pattern))\nFROM __TABLE__ WHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}"
   },
   {
    "name": "pop",
    "label": "Pop",
    "query": "SELECT arrayJoin(topK(50)(pop))\nFROM __TABLE__ WHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}"
   },
   {
    "name": "client_country_iso_code",
    "label": "Country",
    "query": "SELECT arrayJoin(topK(50)(client_country_iso_code))\nFROM __TABLE__ WHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}"
   },
   {
    "name": "cache_edge_result_type",
    "label": "cache_edge_result_type",
    "query": "Hit,RefreshHit,Miss,LimitExceeded,CapacityExceeded,Error,Redirect"
   },
   { "name": "edge_request_id" },
   { "name": "client_ip" },
   { "name": "request_user_agent" },
   { "name": "request_path" },
   {
    "name": "header",
    "query": "SELECT arrayJoin(request_header_names) as headers_names\nFROM __TABLE__\nWHERE $__timeFilter(timestamp)\nAND ${filters}\nGROUP BY headers_names"
   },
   {
    "name": "header_value",
    "query": "SELECT request_header_values[indexOf(request_header_names, '${header}')] as  header_value\nFROM __TABLE__\nWHERE $__timeFilter(timestamp)\nAND ${filters}\nGROUP BY header_value"
   },
   { "name": "table", "query": "mux.cdn" },
   {
    "name": "column_name",
    "query": "SELECT name\nFROM system.columns\nWHERE database = splitByChar('.', '__TABLE__')[1]\nAND table = splitByChar('.', '__TABLE__')[2]\nAND type NOT IN ('DateTime', 'DateTime64(3)', 'Array')"
   },
   {
    "name": "column_type",
    "query": "SELECT type\nFROM system.columns\nWHERE database = splitByChar('.', '__TABLE__')[1]\nAND table = splitByChar('.', '__TABLE__')[2]\nAND name = '${column_name}'"
   },
   {
    "name": "evaluation",
    "query": "SELECT multiIf(\n'${column_type}' ILIKE 'Map%',  'has',\n'${column_type}' ILIKE '%string%',  arrayJoin(['=', '!=','LIKE', 'ILIKE', 'NOT LIKE', 'NOT ILIKE']),\n'${column_type}' ILIKE '%int%',  arrayJoin(['<', '>','=', '!=']),\n'${column_type}' ILIKE '%float%',  arrayJoin(['<', '>','=','!=']),\n'=')"
   },
   {
    "name": "values_query",
    "query": "SELECT if('${column_type}' LIKE 'Map%', 'arrayJoin(mapKeys(${column_name}))', 'arrayJoin(topK(50)(${column_name}))')"
   },
   {
    "name": "values",
    "query": "SELECT ${values_query:raw}\nFROM __TABLE__ WHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}"
   },
   {
    "name": "timefilter",
    "query": " SELECT primary_key FROM system.tables WHERE database = splitByChar('.', '__TABLE__')[1]\nAND table = splitByChar('.', '__TABLE__')[2]"
   },
   { "name": "filters", "query": "1=1" },
   {
    "name": "query",
    "query": "SELECT if('${column_type}' LIKE 'Map%', 'mapContains(${column_name}, \\'${values}\\')', '${column_name} ${evaluation} \\'${values}\\'')"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://hydrolix-public.s3.us-east-2.amazonaws.com/Cascade-Logo.png\" align=\"left\" />\n<a href=\"/d/${__dashboard.uid}/${__dashboard}?${filters:queryparam} AND ${query:raw}\">Click here to add filter:</a>\n <code>${query:raw}</code>\nCurrent Filters:\n <code>${filters:raw}</code>"
   }
  },
  {
   "title": "HTTP Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT if(response_status_code > 0, response_status_code::String, null), count(), $__timeInterval(${timefilter}) as time\t\nFROM __TABLE__\nWHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(response_status_code IN (${response_status_code:sqlstring}),$response_status_code)\nAND $__conditionalAll(request_host IN (${request_host:sqlstring}),$request_host)\nAND $__conditionalAll(request_method IN (${request_method:sqlstring}),$request_method)\nAND $__conditionalAll(cache_behavior_path_pattern IN (${cache_behavior_path_pattern:sqlstring}),$cache_behavior_path_pattern)\nAND $__conditionalAll(pop IN (${pop:sqlstring}),$pop)\nAND $__conditionalAll(client_country_iso_code IN (${client_country_iso_code:sqlstring}),$client_country_iso_code)\nAND $__conditionalAll(cache_edge_result_type IN (${cache_edge_result_type:sqlstring}),$cache_edge_result_type)\nAND $__conditionalAll(edge_request_id IN (${edge_request_id:sqlstring}),$edge_request_id)\nAND $__conditionalAll(client_ip IN (${client_ip:sqlstring}),$client_ip)\nAND $__conditionalAll(request_user_agent IN (${request_user_agent:sqlstring}),$request_user_agent)\nAND $__conditionalAll(response_content_type IN (${response_content_type:sqlstring}),$response_content_type)\nAND $__conditionalAll(request_path IN (${request_path:sqlstring}),$request_path)\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}\nGROUP BY time, response_status_code\nORDER BY time"
    }
   ]
  },
  {
   "title": "Cache Hit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT countIf (cache_edge_result_type = 'Hit') / count() * 100 as cache_hit_pct, $__timeInterval(${timefilter}) as time\t\nFROM __TABLE__\nWHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(response_status_code IN (${response_status_code:sqlstring}),$response_status_code)\nAND $__conditionalAll(request_host IN (${request_host:sqlstring}),$request_host)\nAND $__conditionalAll(request_method IN (${request_method:sqlstring}),$request_method)\nAND $__conditionalAll(cache_behavior_path_pattern IN (${cache_behavior_path_pattern:sqlstring}),$cache_behavior_path_pattern)\nAND $__conditionalAll(pop IN (${pop:sqlstring}),$pop)\nAND $__conditionalAll(client_country_iso_code IN (${client_country_iso_code:sqlstring}),$client_country_iso_code)\nAND $__conditionalAll(cache_edge_result_type IN (${cache_edge_result_type:sqlstring}),$cache_edge_result_type)\nAND $__conditionalAll(edge_request_id IN (${edge_request_id:sqlstring}),$edge_request_id)\nAND $__conditionalAll(client_ip IN (${client_ip:sqlstring}),$client_ip)\nAND $__conditionalAll(request_user_agent IN (${request_user_agent:sqlstring}),$request_user_agent)\nAND $__conditionalAll(response_content_type IN (${response_content_type:sqlstring}),$response_content_type)\nAND $__conditionalAll(request_path IN (${request_path:sqlstring}),$request_path)\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}\nGROUP BY time, cache_edge_result_type\nORDER BY time"
    }
   ]
  },
  {
   "title": "Bytes Delivered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT sum(response_content_bytes) as sum_bytes, $__timeInterval(${timefilter}) as time\t\nFROM __TABLE__\nWHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(response_status_code IN (${response_status_code:sqlstring}),$response_status_code)\nAND $__conditionalAll(request_host IN (${request_host:sqlstring}),$request_host)\nAND $__conditionalAll(request_method IN (${request_method:sqlstring}),$request_method)\nAND $__conditionalAll(cache_behavior_path_pattern IN (${cache_behavior_path_pattern:sqlstring}),$cache_behavior_path_pattern)\nAND $__conditionalAll(pop IN (${pop:sqlstring}),$pop)\nAND $__conditionalAll(client_country_iso_code IN (${client_country_iso_code:sqlstring}),$client_country_iso_code)\nAND $__conditionalAll(cache_edge_result_type IN (${cache_edge_result_type:sqlstring}),$cache_edge_result_type)\nAND $__conditionalAll(edge_request_id IN (${edge_request_id:sqlstring}),$edge_request_id)\nAND $__conditionalAll(client_ip IN (${client_ip:sqlstring}),$client_ip)\nAND $__conditionalAll(request_user_agent IN (${request_user_agent:sqlstring}),$request_user_agent)\nAND $__conditionalAll(response_content_type IN (${response_content_type:sqlstring}),$response_content_type)\nAND $__conditionalAll(request_path IN (${request_path:sqlstring}),$request_path)\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}\nGROUP BY time\nORDER BY time"
    },
    {
     "rawSql": "SELECT sum(response_content_bytes) as bytes, $__timeInterval(${timefilter}) as time, cache_edge_result_type\nFROM __TABLE__\nWHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(response_status_code IN (${response_status_code:sqlstring}),$response_status_code)\nAND $__conditionalAll(request_host IN (${request_host:sqlstring}),$request_host)\nAND $__conditionalAll(request_method IN (${request_method:sqlstring}),$request_method)\nAND $__conditionalAll(cache_behavior_path_pattern IN (${cache_behavior_path_pattern:sqlstring}),$cache_behavior_path_pattern)\nAND $__conditionalAll(pop IN (${pop:sqlstring}),$pop)\nAND $__conditionalAll(client_country_iso_code IN (${client_country_iso_code:sqlstring}),$client_country_iso_code)\nAND $__conditionalAll(cache_edge_result_type IN (${cache_edge_result_type:sqlstring}),$cache_edge_result_type)\nAND $__conditionalAll(edge_request_id IN (${edge_request_id:sqlstring}),$edge_request_id)\nAND $__conditionalAll(client_ip IN (${client_ip:sqlstring}),$client_ip)\nAND $__conditionalAll(request_user_agent IN (${request_user_agent:sqlstring}),$request_user_agent)\nAND $__conditionalAll(response_content_type IN (${response_content_type:sqlstring}),$response_content_type)\nAND $__conditionalAll(request_path IN (${request_path:sqlstring}),$request_path)\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}\nGROUP BY time, cache_edge_result_type\nORDER BY time"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT countIf(response_status_code > '400') / count() * 100 as error_rate, $__timeInterval(${timefilter}) as time\t\nFROM __TABLE__\nWHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(response_status_code IN (${response_status_code:sqlstring}),$response_status_code)\nAND $__conditionalAll(request_host IN (${request_host:sqlstring}),$request_host)\nAND $__conditionalAll(request_method IN (${request_method:sqlstring}),$request_method)\nAND $__conditionalAll(cache_behavior_path_pattern IN (${cache_behavior_path_pattern:sqlstring}),$cache_behavior_path_pattern)\nAND $__conditionalAll(pop IN (${pop:sqlstring}),$pop)\nAND $__conditionalAll(client_country_iso_code IN (${client_country_iso_code:sqlstring}),$client_country_iso_code)\nAND $__conditionalAll(cache_edge_result_type IN (${cache_edge_result_type:sqlstring}),$cache_edge_result_type)\nAND $__conditionalAll(edge_request_id IN (${edge_request_id:sqlstring}),$edge_request_id)\nAND $__conditionalAll(client_ip IN (${client_ip:sqlstring}),$client_ip)\nAND $__conditionalAll(request_user_agent IN (${request_user_agent:sqlstring}),$request_user_agent)\nAND $__conditionalAll(response_content_type IN (${response_content_type:sqlstring}),$response_content_type)\nAND $__conditionalAll(request_path IN (${request_path:sqlstring}),$request_path)\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Request Path Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Analysis",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT request_host,request_path,  count(), sum(response_content_bytes) as sum_bytes, countIf(cache_edge_result_type = 'Hit') / count() * 100 as offload_hits, countIf(response_status_code > '400') / count() * 100 as error_rate\nFROM __TABLE__\nWHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(response_status_code IN (${response_status_code:sqlstring}),$response_status_code)\nAND $__conditionalAll(request_host IN (${request_host:sqlstring}),$request_host)\nAND $__conditionalAll(request_method IN (${request_method:sqlstring}),$request_method)\nAND $__conditionalAll(cache_behavior_path_pattern IN (${cache_behavior_path_pattern:sqlstring}),$cache_behavior_path_pattern)\nAND $__conditionalAll(pop IN (${pop:sqlstring}),$pop)\nAND $__conditionalAll(client_country_iso_code IN (${client_country_iso_code:sqlstring}),$client_country_iso_code)\nAND $__conditionalAll(cache_edge_result_type IN (${cache_edge_result_type:sqlstring}),$cache_edge_result_type)\nAND $__conditionalAll(edge_request_id IN (${edge_request_id:sqlstring}),$edge_request_id)\nAND $__conditionalAll(client_ip IN (${client_ip:sqlstring}),$client_ip)\nAND $__conditionalAll(request_user_agent IN (${request_user_agent:sqlstring}),$request_user_agent)\nAND $__conditionalAll(response_content_type IN (${response_content_type:sqlstring}),$response_content_type)\nAND $__conditionalAll(request_path IN (${request_path:sqlstring}),$request_path)\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}\nGROUP BY \trequest_path, request_host\nORDER BY count()\nLIMIT 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Geo Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Geo Delivery",
     "type": "geomap",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "rawSql": "SELECT client_country_iso_code, count(), sum(response_content_bytes) as sum_bytes, countIf(cache_edge_result_type = 'Hit') / count() * 100 as offload_hits, countIf(response_status_code > '400') / count() * 100 as error_rate\nFROM __TABLE__\nWHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(response_status_code IN (${response_status_code:sqlstring}),$response_status_code)\nAND $__conditionalAll(request_host IN (${request_host:sqlstring}),$request_host)\nAND $__conditionalAll(request_method IN (${request_method:sqlstring}),$request_method)\nAND $__conditionalAll(cache_behavior_path_pattern IN (${cache_behavior_path_pattern:sqlstring}),$cache_behavior_path_pattern)\nAND $__conditionalAll(pop IN (${pop:sqlstring}),$pop)\nAND $__conditionalAll(client_country_iso_code IN (${client_country_iso_code:sqlstring}),$client_country_iso_code)\nAND $__conditionalAll(cache_edge_result_type IN (${cache_edge_result_type:sqlstring}),$cache_edge_result_type)\nAND $__conditionalAll(edge_request_id IN (${edge_request_id:sqlstring}),$edge_request_id)\nAND $__conditionalAll(client_ip IN (${client_ip:sqlstring}),$client_ip)\nAND $__conditionalAll(request_user_agent IN (${request_user_agent:sqlstring}),$request_user_agent)\nAND $__conditionalAll(response_content_type IN (${response_content_type:sqlstring}),$response_content_type)\nAND $__conditionalAll(request_path IN (${request_path:sqlstring}),$request_path)\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}\nGROUP BY \tclient_country_iso_code\nORDER BY count()\nLIMIT 100"
      }
     ]
    },
    {
     "title": "Geo Delivery",
     "type": "table",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "rawSql": "SELECT client_country_iso_code, pop, count(), sum(response_content_bytes) as sum_bytes, countIf(cache_edge_result_type = 'Hit') / count() * 100 as offload_hits, countIf(response_status_code > '400') / count() * 100 as error_rate\nFROM __TABLE__\nWHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(response_status_code IN (${response_status_code:sqlstring}),$response_status_code)\nAND $__conditionalAll(request_host IN (${request_host:sqlstring}),$request_host)\nAND $__conditionalAll(request_method IN (${request_method:sqlstring}),$request_method)\nAND $__conditionalAll(cache_behavior_path_pattern IN (${cache_behavior_path_pattern:sqlstring}),$cache_behavior_path_pattern)\nAND $__conditionalAll(pop IN (${pop:sqlstring}),$pop)\nAND $__conditionalAll(client_country_iso_code IN (${client_country_iso_code:sqlstring}),$client_country_iso_code)\nAND $__conditionalAll(cache_edge_result_type IN (${cache_edge_result_type:sqlstring}),$cache_edge_result_type)\nAND $__conditionalAll(edge_request_id IN (${edge_request_id:sqlstring}),$edge_request_id)\nAND $__conditionalAll(client_ip IN (${client_ip:sqlstring}),$client_ip)\nAND $__conditionalAll(request_user_agent IN (${request_user_agent:sqlstring}),$request_user_agent)\nAND $__conditionalAll(response_content_type IN (${response_content_type:sqlstring}),$response_content_type)\nAND $__conditionalAll(request_path IN (${request_path:sqlstring}),$request_path)\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}\nGROUP BY \tclient_country_iso_code, pop\nORDER BY count()\nLIMIT 100"
      }
     ]
    }
   ]
  },
  {
   "title": "User Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uniq Client IP",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT uniq(client_ip) as uniq_ip, $__timeInterval(${timefilter}) as time\t\nFROM __TABLE__\nWHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(response_status_code IN (${response_status_code:sqlstring}),$response_status_code)\nAND $__conditionalAll(request_host IN (${request_host:sqlstring}),$request_host)\nAND $__conditionalAll(request_method IN (${request_method:sqlstring}),$request_method)\nAND $__conditionalAll(cache_behavior_path_pattern IN (${cache_behavior_path_pattern:sqlstring}),$cache_behavior_path_pattern)\nAND $__conditionalAll(pop IN (${pop:sqlstring}),$pop)\nAND $__conditionalAll(client_country_iso_code IN (${client_country_iso_code:sqlstring}),$client_country_iso_code)\nAND $__conditionalAll(cache_edge_result_type IN (${cache_edge_result_type:sqlstring}),$cache_edge_result_type)\nAND $__conditionalAll(edge_request_id IN (${edge_request_id:sqlstring}),$edge_request_id)\nAND $__conditionalAll(client_ip IN (${client_ip:sqlstring}),$client_ip)\nAND $__conditionalAll(request_user_agent IN (${request_user_agent:sqlstring}),$request_user_agent)\nAND $__conditionalAll(response_content_type IN (${response_content_type:sqlstring}),$response_content_type)\nAND $__conditionalAll(request_path IN (${request_path:sqlstring}),$request_path)\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}\nGROUP BY time\nORDER BY time"
      }
     ]
    },
    {
     "title": "Uniq Client Session",
     "type": "timeseries",
     "description": "A session is a combination of uniq(IP, User-Agent)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT uniq(client_ip, request_user_agent) as uniq_ip, $__timeInterval(${timefilter}) as time\t\nFROM __TABLE__\nWHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(response_status_code IN (${response_status_code:sqlstring}),$response_status_code)\nAND $__conditionalAll(request_host IN (${request_host:sqlstring}),$request_host)\nAND $__conditionalAll(request_method IN (${request_method:sqlstring}),$request_method)\nAND $__conditionalAll(cache_behavior_path_pattern IN (${cache_behavior_path_pattern:sqlstring}),$cache_behavior_path_pattern)\nAND $__conditionalAll(pop IN (${pop:sqlstring}),$pop)\nAND $__conditionalAll(client_country_iso_code IN (${client_country_iso_code:sqlstring}),$client_country_iso_code)\nAND $__conditionalAll(cache_edge_result_type IN (${cache_edge_result_type:sqlstring}),$cache_edge_result_type)\nAND $__conditionalAll(edge_request_id IN (${edge_request_id:sqlstring}),$edge_request_id)\nAND $__conditionalAll(client_ip IN (${client_ip:sqlstring}),$client_ip)\nAND $__conditionalAll(request_user_agent IN (${request_user_agent:sqlstring}),$request_user_agent)\nAND $__conditionalAll(response_content_type IN (${response_content_type:sqlstring}),$response_content_type)\nAND $__conditionalAll(request_path IN (${request_path:sqlstring}),$request_path)\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}\nGROUP BY time\nORDER BY time"
      }
     ]
    },
    {
     "title": "Request Analysis",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "rawSql": "SELECT client_ip,request_user_agent,  count(), sum(response_content_bytes) as sum_bytes, countIf(cache_edge_result_type = 'Hit') / count() * 100 as offload_hits, countIf(response_status_code > '400') / count() * 100 as error_rate\nFROM __TABLE__\nWHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(response_status_code IN (${response_status_code:sqlstring}),$response_status_code)\nAND $__conditionalAll(request_host IN (${request_host:sqlstring}),$request_host)\nAND $__conditionalAll(request_method IN (${request_method:sqlstring}),$request_method)\nAND $__conditionalAll(cache_behavior_path_pattern IN (${cache_behavior_path_pattern:sqlstring}),$cache_behavior_path_pattern)\nAND $__conditionalAll(pop IN (${pop:sqlstring}),$pop)\nAND $__conditionalAll(client_country_iso_code IN (${client_country_iso_code:sqlstring}),$client_country_iso_code)\nAND $__conditionalAll(cache_edge_result_type IN (${cache_edge_result_type:sqlstring}),$cache_edge_result_type)\nAND $__conditionalAll(edge_request_id IN (${edge_request_id:sqlstring}),$edge_request_id)\nAND $__conditionalAll(client_ip IN (${client_ip:sqlstring}),$client_ip)\nAND $__conditionalAll(request_user_agent IN (${request_user_agent:sqlstring}),$request_user_agent)\nAND $__conditionalAll(response_content_type IN (${response_content_type:sqlstring}),$response_content_type)\nAND $__conditionalAll(request_path IN (${request_path:sqlstring}),$request_path)\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}\nGROUP BY \tclient_ip, request_user_agent\nORDER BY count()\nLIMIT 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Logs",
     "type": "logs",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 51 },
     "targets": [
      {
       "rawSql": "SELECT *\t\nFROM __TABLE__\nWHERE $__timeFilter(${timefilter})\nAND $__conditionalAll(response_status_code IN (${response_status_code:sqlstring}),$response_status_code)\nAND $__conditionalAll(request_host IN (${request_host:sqlstring}),$request_host)\nAND $__conditionalAll(request_method IN (${request_method:sqlstring}),$request_method)\nAND $__conditionalAll(cache_behavior_path_pattern IN (${cache_behavior_path_pattern:sqlstring}),$cache_behavior_path_pattern)\nAND $__conditionalAll(pop IN (${pop:sqlstring}),$pop)\nAND $__conditionalAll(client_country_iso_code IN (${client_country_iso_code:sqlstring}),$client_country_iso_code)\nAND $__conditionalAll(cache_edge_result_type IN (${cache_edge_result_type:sqlstring}),$cache_edge_result_type)\nAND $__conditionalAll(edge_request_id IN (${edge_request_id:sqlstring}),$edge_request_id)\nAND $__conditionalAll(client_ip IN (${client_ip:sqlstring}),$client_ip)\nAND $__conditionalAll(request_user_agent IN (${request_user_agent:sqlstring}),$request_user_agent)\nAND $__conditionalAll(response_content_type IN (${response_content_type:sqlstring}),$response_content_type)\nAND $__conditionalAll(request_path IN (${request_path:sqlstring}),$request_path)\nAND $__conditionalAll(has(request_header_names, '${header}'), $header)\nAND $__conditionalAll(has(request_header_values, '${header_value}'), $header_value)\nAND ${filters}\nORDER BY timestamp DESC\nLIMIT 1000"
      }
     ]
    }
   ]
  }
 ]
}