"""Auto-detection engine for two-track CI pipeline.

Determines whether a bundle's assets are raw (pre-Stage 2) or configured (post-Stage 2),
and routes to the appropriate pipeline track.
"""

import json
import os
import glob as glob_mod


def classify_bundle_state(bundle_dir: str) -> str:
    """Classify a bundle directory as 'raw', 'configured', or 'ambiguous'.

    Inspects asset markers to determine if the bundle has been through Stage 2 configuration.
    """
    raw_signals = 0
    configured_signals = 0

    # Check for bundle.json (auto-generated by Stage 2)
    if os.path.isfile(os.path.join(bundle_dir, "bundle.json")):
        configured_signals += 1
    else:
        raw_signals += 1

    # Check dashboard files for configured markers
    _check_dashboards(bundle_dir, raw_signals, configured_signals)
    dashboard_raw, dashboard_configured = _check_dashboards(bundle_dir, 0, 0)
    raw_signals += dashboard_raw
    configured_signals += dashboard_configured

    # Check summary SQL for template variables
    sql_raw, sql_configured = _check_summary_sql(bundle_dir)
    raw_signals += sql_raw
    configured_signals += sql_configured

    # Classify based on scoring
    if configured_signals >= 3 and raw_signals == 0:
        return "configured"
    if raw_signals >= 3 and configured_signals == 0:
        return "raw"
    if configured_signals > raw_signals and configured_signals >= 2:
        return "configured"
    if raw_signals > configured_signals and raw_signals >= 2:
        return "raw"
    return "ambiguous"


def detect_track(bundle_dir: str, changed_files: list[str], repo_root: str) -> str:
    """Determine which pipeline track a bundle should run on.

    Returns 'full' (Stage 1+2+3) or 'validate-only' (Stage 3 only).
    Raises ValueError if Track 1 is detected but bundle-config.json is missing.
    """
    rel_bundle = os.path.relpath(bundle_dir, repo_root)
    originals_dir = os.path.join(repo_root, ".originals", rel_bundle)
    originals_prefix = os.path.join(".originals", rel_bundle)

    # If any changed files are under .originals/<bundle>/, always full pipeline
    for f in changed_files:
        normalized = f.replace("\\", "/")
        if normalized.startswith(originals_prefix.replace("\\", "/")):
            _require_bundle_config(bundle_dir)
            return "full"

    # Check if .originals/ exists for this bundle
    has_originals = os.path.isdir(originals_dir)

    if has_originals:
        # .originals/ exists — classify the changed assets
        state = classify_bundle_state(bundle_dir)
        if state == "raw":
            _require_bundle_config(bundle_dir)
            return "full"
        _require_bundle_json(bundle_dir)
        return "validate-only"  # configured or ambiguous → safe default

    # No .originals/ — first run or legacy
    has_config = os.path.isfile(os.path.join(bundle_dir, "bundle-config.json"))
    if not has_config:
        return "validate-only"  # Legacy grandfathered bundle

    state = classify_bundle_state(bundle_dir)
    if state == "raw":
        return "full"  # First run — will create .originals/
    if state in ("configured", "ambiguous"):
        _require_bundle_json(bundle_dir)
        return "validate-only"

    raise ValueError(f"Unexpected bundle state '{state}' for {bundle_dir}")


def _require_bundle_config(bundle_dir: str):
    """Raise ValueError if bundle-config.json is missing."""
    if not os.path.isfile(os.path.join(bundle_dir, "bundle-config.json")):
        raise ValueError(
            f"Cannot run full pipeline without bundle-config.json in {bundle_dir}. "
            "Add one or use skip-bundle-format label."
        )


def _require_bundle_json(bundle_dir: str):
    """Raise ValueError if bundle.json is missing for a validate-only bundle."""
    if not os.path.isfile(os.path.join(bundle_dir, "bundle.json")):
        raise ValueError(
            f"Bundle routed to validate-only but bundle.json is missing in {bundle_dir}. "
            "Either:\n"
            "  1. Submit raw assets with a bundle-config.json so Track 1 generates bundle.json, or\n"
            "  2. Include a valid bundle.json alongside configured assets.\n"
            "See HOW-TO-CONTRIBUTE.md for details."
        )


def _check_dashboards(bundle_dir: str, raw_count: int, configured_count: int) -> tuple[int, int]:
    """Check dashboard JSON files for raw vs configured markers."""
    raw = 0
    configured = 0

    dashboard_files = (
        glob_mod.glob(os.path.join(bundle_dir, "dashboards", "**", "*.json"), recursive=True)
        + glob_mod.glob(os.path.join(bundle_dir, "grafana", "**", "*.json"), recursive=True)
    )

    for path in dashboard_files:
        try:
            with open(path) as f:
                data = json.load(f)
        except (json.JSONDecodeError, OSError):
            continue

        # Wrapped in {"dashboard": ...} = configured
        if "dashboard" in data and isinstance(data["dashboard"], dict):
            configured += 1
            dashboard_data = data["dashboard"]
        else:
            raw += 1
            dashboard_data = data

        # __inputs present = raw
        if "__inputs" in dashboard_data:
            raw += 1
        else:
            configured += 1

        # __DATASOURCE__ in content = configured
        content = json.dumps(dashboard_data)
        if "__DATASOURCE__" in content:
            configured += 1
        else:
            raw += 1

        # __elements with model.datasource = configured
        elements = dashboard_data.get("__elements", {})
        if isinstance(elements, dict) and "model" in elements:
            model = elements["model"]
            if isinstance(model, dict) and "datasource" in model:
                configured += 1
            else:
                raw += 1
        # Only count as raw signal if __elements exists but lacks the marker
        elif "__elements" in dashboard_data:
            raw += 1

    return raw, configured


def _check_summary_sql(bundle_dir: str) -> tuple[int, int]:
    """Check summary SQL files for raw vs configured markers."""
    raw = 0
    configured = 0

    sql_files = glob_mod.glob(os.path.join(bundle_dir, "summaries", "**", "*.sql"), recursive=True)

    for path in sql_files:
        try:
            with open(path) as f:
                content = f.read()
        except OSError:
            continue

        if "__PROJECT_NAME__.__TABLE_NAME__" in content:
            configured += 1
        else:
            raw += 1

    return raw, configured


def main():
    """CLI entry point for detect_track.py."""
    import argparse

    parser = argparse.ArgumentParser(description="Auto-detect pipeline track for a bundle.")
    parser.add_argument("--bundle-dir", required=True, help="Path to bundle directory")
    parser.add_argument("--mode", choices=["classify", "track"], default="track",
                        help="'classify' returns raw/configured/ambiguous; 'track' returns full/validate-only")
    parser.add_argument("--changed-files", default="",
                        help="Comma-separated list of changed files (for track mode)")
    parser.add_argument("--repo-root", default="",
                        help="Repository root (default: parent of scripts/)")
    args = parser.parse_args()

    repo_root = args.repo_root or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    if args.mode == "classify":
        result = classify_bundle_state(args.bundle_dir)
        print(result)
    else:
        changed = [f.strip() for f in args.changed_files.split(",") if f.strip()]
        result = detect_track(args.bundle_dir, changed, repo_root)
        print(result)


if __name__ == "__main__":
    main()
