folders:
  hdx-main-folder: # folder uid
    name: TrafficPeak Certified Reference Dashboards
    children:
      hdx-security-folder: # folder uid
        name: Security
dashboards:
  hdx-bot-insights-cdn-1770227511016:
    dashboard:
      __extend__: dashboards/bot_insights_cdn_1770227511016.json
    folderUid: hdx-main-folder
    inputs:
      DS_HYDROLIX-HYDROLIX-DATASOURCE: hdx-hydrolix-datasource
      VAR_SUMMARY_HOUR: demo_customer.bot_summary_hour
      VAR_SUMMARY_DAY: demo_customer.bot_summary_day
      VAR_SUMMARY_MONTH: demo_customer.bot_summary_month
