folders:
  hdx-main-folder:
    name: TrafficPeak Certified Reference Dashboards
    children:
      hdx-cdn-folder:
        name: CDN
dashboards:
  hdx-raw-logs:
    dashboard:
      __extend__: dashboards/raw_logs.json
    folderUid: hdx-cdn-folder
    inputs:
      DS_HYDROLIX-HYDROLIX-DATASOURCE: hdx-hydrolix-datasource
  hdx-cdn-dashboard-default:
    dashboard:
      __extend__: dashboards/cdn_dashboard_default.json
    folderUid: hdx-cdn-folder
    inputs:
      DS_HYDROLIX-HYDROLIX-DATASOURCE: hdx-hydrolix-datasource
  hdx-cdn-global-view:
    dashboard:
      __extend__: dashboards/cdn_global_view.json
    folderUid: hdx-cdn-folder
    inputs:
      DS_HYDROLIX-HYDROLIX-DATASOURCE: hdx-hydrolix-datasource
